enthought/traits

traits/etsconfig/tests/test_etsconfig.py
=> Avoid creating top-level blah, .blah and .enthought directories in test.

docs/source/traits_user_manual/advanced.rst
Reworked version of PR #151.  Thanks to Pierre Haessig for proposing this.
=> Add note about use of __traits_version__ key in HasTraits pickle protocol.

docs/source/traits_user_manual/defining.rst
1. Fix syntax highlighting in existing code snippet for `Enum`
2. Added a note about making the list of values dynamic
=> Doc improvement Enum

docs/source/traits_api_reference/traits.rst, traits/adaptation/adaptation_manager.py, traits/trait_types.py
This PR:
- fixes some documentation build warnings.
- updates some of the docstrings in the adaptation subpackage.
=> Fix documentation warnings

appveyor-install.cmd, appveyor-test.cmd, appveyor.yml
This PR sets up appveyor to run tests using python 2.7, python 3.3 and python 3.4 on commits and PRs
=> Add appveyor

.travis.yml, travis-ci-requirements.txt
This PR cleans up the travis configuration file using the new requirements format supported by pip.
=> Travis configuration cleanup

CHANGES.txt, traits/ctraits.c, traits/tests/test_regression.py
Fixes #259.  ~~I'll add a regression test shortly.~~ Test added.
=> Fix object reference leak from delegation.

.travis.yml, appveyor-install.cmd, traits/tests/test_regression.py
Attempt to fix test failure in the #268 CI runs.  (I haven't managed to reproduce the failures locally.)
=> Fix continuous integration issues due to new coverage version.

traits/has_traits.py
I can never remember which one returns a boolean and which returns a UI object. Add that information to the docstrings so it's easier to find.
=> Add return values to edit_traits() and configure_traits() methods

traits/tests/test_float.py, traits/tests/test_traits.py, traits/trait_types.py
=> Allow Float and BaseFloat trait types to accept longs.

setup.py, traits/ctraits.pyx
Third time's the charm: this is the old https://github.com/enthought/traits/pull/296, but against #294.
=> Fixes for the cython port

traits/tests/test_trait_list_dict.py, traits/trait_handlers.py
=> Fix TraitSetObject issues

.travis.yml
Modify `.travis.yml` to only build on pushes to master.
=> Only build on pushes to master.

traits/tests/test_disallow.py
@sjagoe This tests the case you brought up in https://github.com/enthought/traits/pull/298#discussion_r67839796
=> Cython: Test attributes that aren't disallowed.

appveyor.yml
As discussed in https://github.com/enthought/traits/pull/323#issuecomment-239804828
(Disclaimer: I have no idea what I'm doing)
=> BUILD: Update pip invocation

LICENSE.txt, docs/source/conf.py, docs/source/traits_user_manual/intro.rst, setup.py
Small fixes to documentation and metadata.
=> Update websites and dates

docs/source/traits_user_manual/intro.rst
Ensure docs match current state from #345
=> Update Python versions supported in docs

traits/tests/test_editor_factories.py, traits/traits.py
=> Set auto_set/enter_set default once

traits/ctraits.c, traits/tests/test_regression.py
=> Clear exception from NumPy properly.

traits/has_traits.py, traits/tests/test_regression.py
=> Fix extended names in on_trait_change lists.

traits/has_traits.py, traits/tests/test_regression.py
=> FIX: Check function attributes upon class creation

traits/traits.py
Black is not white. Closes #416.
=> Fix Color and RGBColor docstrings

docs/source/_extensions/refactordoc/definition_items.py, docs/source/_extensions/refactordoc/line_functions.py, examples/tutorials/doc_examples/examples/delegate.py, examples/tutorials/traits_4.0/extended_trait_change/extended_trait_change.py, traits/testing/tests/test_unittest_tools.py, traits/trait_handlers.py, traits/util/clean_strings.py
Fix various invalid string escapes in the codebase, mostly either in docstrings or regular expression strings.
=> Fix invalid string escapes

.travis.yml, appveyor.yml, ci-doc-requirements.txt, etstool.py
=> CI for documentation

docs/source/conf.py
=> Fix the copyright footer

.travis.yml, appveyor.yml
Allow running of continuous integration on PRs against branches other than the master branch. [PR against release branch, for obvious reasons. Will cherry-pick back to master.]
=> Don't restrict CI to PRs against the master branch.

setup.py
I've just branched for the release of 5.1.0 (release branch not yet pushed); any changes on master are now aimed at 5.2.0.
=> Bump version on master for continued development towards 5.2.0

CHANGES.rst
[PR aimed at the release branch; will cherry-pick back into master later]
Changelog entry updates for the 5.1.0 release.
=> Update changelog for 5.1.0 release.

setup.py
[PR against release branch]
Bump version for eventual release of 5.1.0. I'll merge this PR last thing, after all other changes (changelog updates, etc.).
=> Update version for 5.1.0 release.

setup.py
Once #472 is merged, we'll need to make a new Traits release containing that bugfix.
=> Bump version for 5.1.1 release

CHANGES.rst, traits/_py2to3.py, traits/tests/test__py2to3.py
Cherry-pick changes from #472 (made against the release branch) to the master branch.
Will self-merge once CI signs off; the code changes have already been reviewed in #472.
=> Merge release-branch bugfix (str_find) into master

CHANGES.rst, setup.py, traits/util/tests/test_trait_documenter.py, traits/util/trait_documenter.py
Prepare for bugfix release of Traits:
- backport #494 to the release branch
- bump version number
- update CHANGELOG
Note: PR merge should use squash-and-merge.
=> Bugfix release 5.1.2

CHANGES.rst
Bring in changes from release/5.1.x branch.
=> Forward port changelog updates from release branch.

traits/category.py, traits/has_traits.py, traits/tests/test_category.py
This PR adds a DeprecationWarning that's issued for uses of Category.
The CI will fail until #509 is applied.
Closes #319.
=> Deprecate Category

traits/has_traits.py, traits/tests/test_sync_traits.py
=> Revert "Adjust slice calculation for sync trait items"

etstool.py
This PR makes it possible to use `etstool.py` to install and update in editable mode, making day-to-day development easier. (Almost every time I work on traits I get tripped up by making local changes and then finding that they haven't taken effect.)
=> Add --editable option for install and update commands.

docs/source/traits_user_manual/defining.rst
Fix needed because of change made in #520
=> Minor docs fix

traits/tests/test_float_range.py, traits/trait_types.py
This PR refactors `test_float_range.py` to remove duplication in the test model classes.
=> Refactor test_float_range to remove duplication

traits/ctraits.c
The `_trait_notification_handler` function is undocumented, untested, and unused in real projects; as such, it's an unnecessary maintenance burden. This PR removes it.
It's reasonable to want this kind of instrumentation available, but if available it should be tested and documented.
Resolves #618
=> Remove untested undocumented _trait_notification_handler

traits/ctraits.c, traits/trait_types.py
This PR:
- cleans up the C code used for validating instances with adaptation
- if the adaptation mode for `BaseInstance` or one of its subclasses is "no", bypasses the adaptation altogether in the C code. (This shouldn't actually make any difference, because we're no longer using case 19 of fast_validate in the case where no adaptation is requested, so this *should* be an unexercised C code path.)
- removes bare excepts from the validation: exceptions not related to failure of adaptation will be propagated as usual
See the Python code for the new logic; the C code should exactly mirror the Python code.
=> Clean up C code for adapted instance validation

traits/trait_handlers.py
This PR is case where a piece of functionality is broken, unused and untested, so the simple and efficient thing to do is to remove it.
`TraitInstance` accepts an `adapt` keyword. If its value is `"no"`, then no adaptation is performed and a simple instance check is used. If its value is "yes", then the *intent* is that adaptation is performed, but the reality is that no adaptation is performed, because the adaptation map used by the fast validator differs from the adaptation map used in this file: here `"no"` maps to `-1` and `"yes"` maps to `0`, but in the fast validator, `0` means do no adaptation and `1` means "adapt".
We can't remove `TraitInstance` itself (yet), though that's definitely in the long-term plan. But we can get rid of the adaptation support.
=> Remove adaptation support from TraitInstance

traits/ctraits.c
This PR adds a handful of expanded docstrings for cTrait methods.
=> Add more cTrait docstrings

traits/ctraits.c
OCD fixes for the `cTrait` and `CHasTraits` flags fields:
- make both `flags` fields unsigned
- be consistent about flag checks in code
- remove unnecessary parentheses
Closes #669.
=> Make flags field unsigned.

docs/source/traits_api_reference/trait_handlers.rst, traits/api.py, traits/trait_handlers.py
The TraitClass subclass of TraitHandler is untested, and unused in real code.
See also #697
=> Remove the TraitClass subclass of TraitHandler

traits/trait_types.py
=> Fix confusing error message when [None] passed into List(This(allow_none=False)) trait

traits/adaptation/tests/benchmark.py
Another small step on the road to flake8-cleanliness.
=> Style: make benchmark script flake8 clean

traits/tests/test_list.py, traits/tests/test_list_events.py, traits/trait_list_object.py
=> Add clear and copy methods to TraitListObject

traits/api.py, traits/editor_factories.py, traits/tests/test_editor_factories.py, traits/trait_types.py
=> DateTime trait

traits/trait_types.py
=> Rename init_fast_validator method as init_fast_validate

traits/constants.py, traits/tests/test_array_or_none.py, traits/tests/test_constants.py, traits/tests/test_ctraits.py, traits/tests/test_rich_compare.py, traits/tests/test_traits.py, traits/trait_numeric.py, traits/trait_type.py, traits/traits.py
closes #763
Depends on PR #758 and should be reviewed after that PR closed.
=> rename ComparisonMode enum members

docs/source/traits_api_reference/trait_handlers.rst, traits/api.py, traits/tests/test_deprecated_handlers.py, traits/trait_handlers.py, traits/traits.py
closes #177 
In lieu of PR #776.
=> delete ThisClass from traits code base and documentation.

CHANGES.rst, docs/source/changelog.rst, docs/source/index.rst
closes #650 
Adds changelog to the built documentation following the method used in traitsui.
=> Add Changelog to documentation

traits/editor_factories.py, traits/tests/test_editor_factories.py
Fixes #797 Removes the failing test.
Removes an unused module variable DateTimeEditor
=> Remove test for DateTimeEditor

traits/tests/test_editor_factories.py
=> Rename a test class to match the object being tested

traits/constants.py, traits/tests/test_array_or_none.py, traits/tests/test_constants.py, traits/tests/test_ctraits.py, traits/tests/test_rich_compare.py, traits/tests/test_traits.py, traits/trait_numeric.py, traits/trait_type.py, traits/traits.py
Recreation of #778 against master.
Closes #763
=> Rename comparison mode members

traits/ctraits.c
This PR completes and expands the documentation for the `CHasTraits` class and its methods.
=> DOC: Add CHasTraits documentation

traits/ctraits.c
This PR adds improved docstrings for the various cTrait properties.
=> DOC: Improved docstrings for cTrait properties

setup.py
Further development on the master branch is now aimed at Traits 6.1.0. Once this PR is merged to master, I'll branch the 6.0.x release branch from the immediately preceding commit.
=> Bump version number for continued development towards Traits 6.1.0

traits/ctraits.c, traits/tests/test_ctraits.py
Fixes #832 
I've so far failed to come up with a realistic example that exercises the problem; it would be good to have that, if possible.
EDIT: added a regression test. The regression test segfaults for me on current master.
=> Fix unsafe field setting in set_value

CHANGES.rst, traits/ctraits.c, traits/tests/test_ctraits.py
This is a backport of PR #844 from the master branch to the release branch.
=> Fix unsafe field setting (backport of #844)

CHANGES.rst, docs/source/traits_api_reference/trait_types.rst, traits/trait_types.py
This PR backports #843 from master to the release branch.
=> Improvements and formatting fixes for trait types. (#843 backport)

CHANGES.rst, docs/source/traits_api_reference/trait_numeric.rst, traits/adaptation/adapter.py, traits/etsconfig/etsconfig.py, traits/testing/unittest_tools.py, traits/trait_numeric.py, traits/util/event_tracer.py
This is a backport of #854 to the release branch.
=> Additional class docstring fixes (#854 backport)

CHANGES.rst
Bring changelog changes from the release branch back into master.
=> Forward port changelog changes from master

traits/ctraits.c
Rename some internal integer constants in ctraits.c for consistency and improved discoverability.
Also removes some trailing whitespace in ctraits.c
=> MAINT: Rename comparison mode integer constants in ctraits.c

docs/source/conf.py, docs/source/traits_user_manual/front.rst, docs/source/traits_user_manual/index.rst
This is a backport of PR #903 to the 6.0.x release branch.
=> Backport #903 (replace Traits 5 with Traits 6 in documentation)

CHANGES.rst
Bring in changes from the 6.0.x release branch.
=> Update changelog for Traits 6.0.0 final release

.github/pull_request_template, .github/pull_request_template.md
This PR adds a GitHub PR template to help developers.
=> Add GitHub PR template

setup.py
The master branch is now aimed at the Traits 6.2.0 release.
=> Bump version for continued development on master

CHANGES.rst, traits/tests/test_trait_dict_list_set_event.py
This PR fixes a test that was mutating global state. That test then failed when run repeatedly.
=> Fix mutation of global state by a test

CHANGES.rst, traits/tests/test_trait_prefix_list.py, traits/tests/test_traits.py
There a few module-level `DeprecationWarning` s generated by the test suite. This PR fixes them.
=> Fix some DeprecationWarnings from the test suite

CHANGES.rst, traits/tests/test_trait_list_object.py, traits/trait_list_object.py
This PR backports the fixes in #1172 and #1173 to the release branch.
=> Backport #1172 and #1173 to the release branch

CHANGES.rst
Bring two changelog updates from the release branch back into master.
=> Bring changelog updates from release branch to master

traits-stubs/LICENSE.txt, traits-stubs/MANIFEST.in, traits-stubs/README.rst, traits-stubs/setup.py, traits-stubs/traits-stubs/api.pyi
This PR was recreated against master from #1182 
- Update the README (removes most of the mypy-specific stuff)
- Update the setup script
- Add LICENSE and MANIFEST files
- Rename top-level `init.py` to `init.pyi`
- Add a missing license header to `api.pyi`
Closes #1132
=> Prepare traits-stubs for distribution

LICENSE.txt
Fix out-of-date end year in the LICENSE copyright statement.
=> Fix end-year in copyright statement

setup.py
This PR is a version bump on the release/6.1.x branch in preparation for backport of PRs for a 6.1.1 bugfix release.
=> Bump version for development towards the 6.1.1 bugfix release

CHANGES.rst, docs/source/traits_user_manual/notification.rst, traits/util/tests/test_trait_documenter.py, traits/util/trait_documenter.py
This PR:
- backports PRs #1195 and #1246 from the master branch
- updates the changelog accordingly
=> More PR backports for the 6.1.1 bugfix release

CHANGES.rst
This PR brings changelog updates from the 6.1.1 release branch back into the master branch.
=> Update changelog from 6.1.1 release branch

traits/tests/test_trait_dict_object.py
`test_update_with_tranformation` should be `test_update_with_transformation`
=> Fix typo in test method name

.travis.yml
**Checklist**
- [n/a] Update API reference (`docs/source/traits_api_reference`)
- [n/a?] Update User manual (`docs/source/traits_user_manual`)
- [n/a] Update type annotation hints in `traits-stubs`
For #1304. 
Python 3.9 final is now available on Travis CI.
=> Travis CI: Test 3.9 final

traits/tests/check_observe_timing.py
closes #1325 
**Checklist**
~- [ ] Tests~
=> Add script to benchmark performance of observe to compare with on_trait_change

traits/editor_factories.py
Trivial PR to address this comment: https://github.com/enthought/traits/pull/1446#discussion_r605908565 that was missed before #1446 got merged
=> Remove unneeded result temp variable

docs/source/traits_tutorial/introduction.rst, docs/source/traits_user_manual/listening.rst, examples/tutorials/doc_examples/examples/cached_prop.py, traits/examples/introduction/2_initialization.py, traits/examples/introduction/index.rst
=> fix: small error in docs

traits/tests/test_automatic_adaptation.py, traits/trait_types.py
This PR bypasses the `default_value_type` inference for `BaseClass` and `BaseInstance` subclasses. It also inlines the use of `_InstanceArgs`.
=> Remove default_value_type inference for BaseClass and BaseInstance

CHANGES.rst
This PR updates the changelog and sets the release date for the upcoming 6.3.2 bugfix release.
Note: this PR is intentionally against the main branch; I'll backport after it's merged.
=> Update the changelog in preparation for a Traits 6.3.2 bugfix release.

setup.py
This PR bumps the version on the maint/6.3 maintenance branch for continued development towards 6.3.3.
=> Bump version on maint/6.3 branch for development towards 6.3.3

docs/source/traits_user_manual/custom.rst, traits/traits.py
=> Document that the Trait factory function should not be used in new code

CHANGES.rst
This PR updates the changelog on the release branch in preparation for the 6.4.0 release.
=> Update changelog on 6.4 release branch

setup.py
This PR bumps the Traits version on the release branch for continued development towards 6.4.1.
=> Bump version for continued development towards 6.4.1

.github/workflows/release-to-pypi.yml, CHANGES.rst, traits-stubs/setup.py, traits-stubs/traits_stubs_tests/test_all.py, traits/testing/optional_dependencies.py
This PR backports recent fixes from the main branch to the 6.4 maintenance branch.
Note: ideally, this PR should be merged using a rebase rather than a squash, so that the individual commits retain their identities.
=> Backport #1709, #1710 and #1711 to maintenance branch

CHANGES.rst
This PR updates the changelog in the main branch to reflect the changes in the maint/6.4 branch.
=> Bring in changelog changes from maint/6.4 release branch

.github/workflows/test-from-pypi.yml, CHANGES.rst
This PR adds tests of the 3.11 wheels.
=> Add 3.11 to the wheel test workflow

traits/tests/test_ui_notifiers.py, traits/trait_types.py
This PR silences two sources of TraitsUI deprecation warnings.
=> Silence two causes of DeprecationWarnings from TraitsUI

setup.py
This PR bumps the version for continued development towards Traits 7.1.0 on the main branch.
=> Bump version for continued development towards 7.1.0

traits/trait_notifiers.py
Preserve behaviour of compiled methods
closes #1848
=> Fixed handling of compiled methods

.github/workflows/run-core-traits-tests.yml, .github/workflows/run-style-checks.yml, .github/workflows/run-traits-tests.yml, .github/workflows/test-documentation-build.yml
This PR updates the core tests and other workflows to enable running them via workflow dispatch.
=> Make it possible to run the core Traits tests via workflow dispatch
