MANIFEST.in
setup.py

This PR:
- removes `ctraits.c`, `py2to3.h`, the `fixers` package, and an unnecessary `README.txt` from the installed traits package.
- explicitly includes `fixers` in `MANIFEST.in` for the source distribution.
Fixes #128.

Remove extraneous installed files

---

traits/util/trait_documenter.py

The docs build was failing on Python 2.7.7 and later, thanks to a combination of [this fix](http://bugs.python.org/issue12691) in the Python core and our use of a line number of zero.  This PR fixes that.
@itziakos: Do you have time to review?

Fix invalid tokens (with line number zero) in trait_documenter machinery.

---

traits/testing/unittest_tools.py

As discussed in #212, the order of Trait event firings is not always well-defined.  This PR adds a note to the `assertTraitChanges` docstring.
Closes #212.

Add note about possibly ill-defined ordering in assertTraitChanges events.

---

README.rst
docs/make.bat
docs/source/conf.py

This PR adds a function in conf.py that will optionally mock the necessary modules and types to successfully build the documentation when traitsui is not available (e.g. on ReadTheDocs builds). For the function to work one needs to have the `mock` library installed.
note: I also added a make.bat to built the documentation on windows

Mock traitsui when building the documentation

---

CHANGES.txt
traits/ctraits.c
traits/tests/test_regression.py

There's an extra `Py_INCREF` call going on in `_has_traits_notifiers`, leading to creation of lists that never get garbage collected (despite having no referrers).  This PR fixes that. It also adds correct behaviour in the unlikely event that the `PyList_New` call fails.
Script to reproduce (thanks @itziakos for narrowing this down):
```
import gc
from traits.api import HasTraits
def callback():
pass
def main():
for index in range(100):
obj = HasTraits()
obj.on_trait_change(callback)
del obj
gc.collect()
object_count = len(gc.get_objects())
print "Iteration {}: object_count={}".format(index, object_count)
if __name__ == '__main__':
main()
```
To do: turn the above script into a unit test.

Fix reference counting bug (extra Py_INCREF) in _has_traits_notifiers.

---

.travis.yml
appveyor-install.cmd
setup.py

We'd like to write tests for trait_documenter (see issue #250 and PR #251).  But for that, we need Sphinx.

Add Sphinx to the CI dependencies

---

.travis.yml

This PR updates the travis-ci configuration to use the new docker based builds and caching. The PR builds should now start faster and run in parallel in roughly 1 minutes (total cumulative build time is now around 5 minutes vs 9 minutes using VMs).

Use travis ci containers

---

traits/util/tests/test_trait_documenter.py
traits/util/trait_documenter.py

Fixes the behavior from #250, by checking NL entries and adding the following entries to the next line. This way, the untokenizer does not complain for lack of order in the tokens.
For testing, I extracted the functionality in a private routine to simplify testing (which would depend on the sphinx infrastructure). Do we have a policy when it comes to testing private routines? Should I make it public if its public use is only through testing?

Fix for issue 250: Trait documenter failure for multiline traits.

---

appveyor-install.cmd

Appveyor builds have been failing recently: see #260 for an example.
The issue appears to be a bug in the newest version of babel.   See e.g., https://github.com/mitsuhiko/babel/issues/174.
This PR downgrades the babel version to 1.3 in an attempt to work around the issue.

Attempt to fix Appveyor failures on Python 3

---

CHANGES.txt
traits/tests/test_string.py
traits/trait_base.py

Currently, the `String` trait type doesn't accept NumPy `string_` instances, even though those instances are instances of `str`:
```python
Python 2.7.9 |Master 2.1.0.dev1806-fbbe7a1 (64-bit)| (default, May 20 2015, 20:01:56) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.6)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from traits.api import HasTraits, String
>>> class A(HasTraits):
...     foo = String
... 
>>> a = A()
>>> a.foo = np.string_('bob')
File "<stdin>", line 1, in <module>
File "build/bdist.macosx-10.6-x86_64/egg/traits/trait_types.py", line 739, in validate
File "build/bdist.macosx-10.6-x86_64/egg/traits/trait_types.py", line 763, in validate_str
File …
```

Make String trait type accept NumPy strings.

---

traits/tests/test_listeners.py
traits/trait_notifiers.py

In python 2, `sys.exc_info()` would return the last exception that had happened, even after the exception is not handled anymore. In python 3, `sys.exc_info()` returns `(None,None,None)` instead. Thus, the exception handler either has to be moved into the `except ...` clause, or the exception info should be stored and passed to the handler. Option 1 is backwards compatible, and thus was implemented here.

Trait exception handlers should be able to access the exception

---

traits/etsconfig/api.py
traits/etsconfig/etsconfig.py
traits/etsconfig/tests/test_etsconfig.py

With the change in the default ETSConfig toolkit in TraitsUI a pre-existing bug was uncovered where, if the toolkit isn't expressly set, you can:
* attempt to import a preferred toolkit implementation in one library (eg. wx backend for enable)
* have it incidentally (and sometimes sub-optimally, but that's a separate issue) import another library with a different backend preference (eg. qt backend for pyface)
* things go badly from there
This PR adds a new context manager method to the ETSConfig object that allows a library to provisionally choose a backend that other libraries will respect, but then undo that selection if a problem occurs in the context manager's block.  The intent is to wrap the import methods in the various toolkit selection methods with this context manager.
This is …

Context manager that provisionally sets the ETSConfig toolkit

---

traits/has_traits.py
traits/tests/test_dynamic_notifiers.py
traits/tests/test_ui_notifiers.py

This PR gets rid of the `*names` argument to the decorator, which never worked, and replaces the magic prefix on the pattern with a dictionary of explicit data and values.
The default values of the kwargs match those of the normal method.

Add `dispatch` and `priority` kwargs to `on_trait_change` decorator.

---

traits/util/trait_documenter.py

Replace `.next()` method with the `next()` builtin. This allows the traits documenter to work correctly in Python 3.

Fix TraitDocumenter for Python 3

---

traits/tests/test_bool.py
traits/trait_types.py

The fast validator for `Bool` accepts NumPy booleans, but the regular validator doesn't. This PR fixes the Python validator to accept NumPy objects of type `bool_`.
Fixes #299.

Fix Bool.validate to accept np.bool_

---

traits/ctraits.pyx
traits/tests/test_constant.py
traits/tests/test_cython.py
traits/tests/test_trait_list_dict.py
traits/trait_handlers.py
traits/util/trait_documenter.py

- Master merge;
- Fixes the [issue raised by @pberkes](https://github.com/enthought/traits/pull/298#issuecomment-222441190);
- Various small fixes to address compiler warnings.

Small fixes for the Cython branch

---

traits/tests/test_list.py
traits/trait_handlers.py

Fix for issue #283.
Also removes an odd-looking `try/except` where the exception message is about the values being assigned but the body of the `try` block has nothing to do with those values.

Fix slice length bug in TraitListObject.__setitem__ and TraitListObject.__delitem__

---

.travis.yml
traits/ctraits.pyx
traits/tests/test_bool.py
traits/tests/test_list.py
traits/tests/test_trait_exceptions.py
traits/trait_handlers.py
traits/trait_types.py

Contains a master merge and changes to `ctraits.pyx` to accommodate #243.
Note: The error message generated by an invalid attribute lookup in Cython is different from the message generated by the code in master (but it's still a `TypeError`). The reason is that the Cython-generated code first does a `PyObject_GenericGetAttr` before calling `__getattr__`, and if you supply an attribute name that is not a string, the former will catch the error and display a (slightly) different message. As a result, I had to change `test_trait_exceptions.py` a little to stop looking for the offending value in the error message.

MAINT: Backport #243

---

traits/etsconfig/etsconfig.py
traits/etsconfig/tests/test_etsconfig.py
traits/trait_base.py

At present the ETSConfig option looks to see if there is are items `-toolkit` and a toolkit name adjacent in `sys.argv`; if so it removes them and uses the supplied toolkit.  This is completely independent of any other command-line argument processing done by other code, and the processing is done when the toolkit is first requested (which could occur in any number of places, possibly as a side-effect of imports), which may or may not be before any other argument parsing is done.  This is a potential source of subtle bugs.
Additionally, the use of `-toolkit` vs. `--toolkit` may be surprising to some, as it goes against some conventions for command-line argument use.
This PR removes this code and corresponding tests.
This is obviously a backward-incompatible change, although I have never …

Remove command-line option for setting toolkit

---

traits/tests/test_bool.py
traits/trait_types.py

This PR changes the `Bool` trait type so that even when an `np.bool_` is put in, a Python `bool` comes out:
```
>>> from traits.api import HasTraits, Bool; import numpy as np
>>> class A(HasTraits):
...     foo = Bool
... 
>>> a = A(foo=np.bool_(True))
>>> type(a.foo)
<type 'bool'>
```
The motivation is twofold:
(1) Consistency with the `Int` trait type, where retrieval always gives a Python `int` or `long`. (Not a particularly strong argument, given that `Float` is a get-out-exactly-what-you-put-in type.)
(2) Avoid bugs of the form `do_something_with(a.foo)` where `do_something_with` expects a Python `bool` and breaks with an `np.bool_`. (#299 was a particular case of this that we ran into, since fixed, but it's not at all implausible that other examples of `np.bool_` intolerance exist …

Ensure that the result of retrieving a Bool trait is a Python bool

---

tox.ini

Allows for running the tests via [Tox](http://tox.readthedocs.io/en/latest/). Assuming that tox is installed,  the test suite can be run against all supported Pythons via `tox`, or against one specific Python via `tox -e pyXY`, where XY is one of 26, 27, 33, 34, 35.

DEV: run tests via Tox

---

docs/source/traits_api_reference/trait_types.rst
docs/source/traits_user_manual/defining.rst
traits/api.py
traits/tests/test_traits.py
traits/trait_types.py
traits/traits.py

Does what it says.  Resolves #328.
The `Bytes` trait is given an `encoding` attribute.  If this is not `None` it is used to specify a codec that the editor uses to decode the bytes to a unicode string, and to re-encode when changed.  If the encoding is none, the bytes are displayed as a hexadecimal value (with no spaces).
To do:

Add Bytes Trait and Related Traits

---

.travis.yml
README.rst
appveyor-install.cmd
appveyor.yml
appveyor/appveyor-install.cmd
appveyor/appveyor-test.cmd
appveyor/run_with_env.cmd
setup.py
travis-ci-requirements.txt

This PR drops support for Python 2.6 and Python 3.x with x < 4.
WIP because I want to add 3.5 (and possibly 3.6) to the CI setups before this is merged.

Drop support for older Python versions.

---

traits/tests/test_get_traits.py

Besides being inappropriate here, this `expectedFailure` decorator also results in the following odd-looking output from our test suite, since nose [doesn't understand it](https://github.com/nose-devs/nose/issues/33):
```
/opt/python/2.7.9/lib/python2.7/unittest/case.py:340: RuntimeWarning: TestResult has no addExpectedFailure method, reporting as passes
```

Fix a misuse of the unittest.expectedFailure decorator.

---

traits/has_traits.py
traits/tests/test_traits.py

Fixes #352. There was some stale code that "fixes up" `This` traits to act like `Instance(Foo, allow_none=False)` traits. `ctraits.c` has the codepaths to handle `This` traits as-is, so I just removed the "fixup" code.

BUG: Fix validation of This traits.

---

traits/ctraits.c
traits/tests/test_regression.py

This PR modifies `cTrait.default_value_for` to raise `ValueError` when asked for the default value of a trait that doesn't have one (for example, a `Property` trait).
Fixes #336.
---
EDIT: Updated to return `None` rather than raising `ValueError`.

Don't segfault when asked for the default value of a trait that doesn't have one.

---

docs/source/traits_user_manual/defining.rst

The commonly useful `Either` trait was difficult to discover in the docs and unexplained, so I fixed some errant `n/a`s in the table of predefined traits to make it more obvious to find and added a short section with a description and an example.

DOC: add description and example of Either trait type

---

traits/tests/test_trait_change_event_tracer.py
traits/trait_notifiers.py

and use the new context manager in tests, to avoid test interactions.
Fixes #363.

Add a context manager for temporarily changing the trait-change-event tracer

---

traits/tests/test_regression.py

@mdickinson Would you mind giving this a quick review? This came up while I was trying to merge master in the Cython branch; the first argument of `default_value_for` should apparently be a `HasTraits` object, but it looks like a class was passed in instead in this particular test. The C implementation is happy with this (it just casts a pointer) but the Cython implementation stumbled over the types...

MAINT: Instantiate HasTraits object in test.

---

appveyor/appveyor-install.cmd
traits/util/tests/test_trait_documenter.py
traits/util/trait_documenter.py
travis-ci-requirements.txt

I have applied the following patch in our project to work around #380 and figured I would submit the fix upstream as well in case it was something you all wanted to incorporate. 
I also tried to add some testing, but it required adding mock to the CI requirements. Let me know if that is going to cause issues.
Closes #380

FIX: Support unicode on trait documenter on Python 2.7

---

traits/trait_handlers.py
traits/trait_types.py
traits/traits.py

This now treats `List(Instance(Foo))`, `List(Foo)`, `Trait(TraitList(Foo))`, etc. all in the same way with common code to create the editor.  It also removes a broken usage of `TableEditor` for the `Set` trait, replacing it with a simple `TextEditor` for now (the same as `Dict`).

Unify and fix default list editors

---

traits/testing/unittest_tools.py

This PR renames the `trait` attribute of `_TraitsChangeCollector` to fix #342. There is no change at the constructor signature but I add a deprecation warning that prompts users to stop using `trait`

Fix issue #342

---

traits/has_traits.py
traits/tests/test_get_traits.py

Closes #320
This PR adds a `__dir__` method to the `HasTraits` class which returns the list of `trait_names` minus the `trait_added` and `trait_modified` attributes which most users will not be looking for when trying to tab complete.
GIF below:

Add __dir__ method to HasTraits to allow for IPython tab completion

---

traits/adaptation/cached_adapter_factory.py
traits/tests/test_dynamic_notifiers.py
traits/traits_listener.py
traits/util/tests/test_weakidddict.py
traits/util/weakiddict.py

The Traits listener machinery uses weak-key dicts to track some of the bookkeeping for attaching and unattaching dynamic listeners. The intention of the code assumed that `HasTraits` instances kept the Python 2 default `__hash__` and `__eq__` semantics, which are based on identity, not value. Python 3 has changed those defaults, and there are some places where we do modify `__eq__` to do value comparisons (e.g. `codetools.contexts`).
Here, I introduce a new `WeakIDKeyDict` that mostly works like a `weakref.WeakKeyDictionary`, but the key objects are hashed and compared only by their identity and entirely ignore the `__hash__` and `__eq__` implementations on the keys.
This also replaces a usage of `WeakKeyDictionary` in the adaptation framework, which has similar issues, though that part …

Free HasTraits subclasses from hashing/comparing by identity

---

traits/interface_checker.py

This avoids `DeprecationWarning`s on Python 3.

Fix use of deprecated getargspec function

---

docs/source/traits_api_reference/has_traits.rst
docs/source/traits_user_manual/advanced.rst
traits/api.py
traits/has_traits.py
traits/tests/test_has_required_traits.py

From the docstring: This class builds on the functionality of HasStrictTraits and ensures that any object attribute with the metadata required=True must be passed as an argument on object initialization.
This came up as there were situations where a class had a few 'key' traits and the others were derived from them. It made sense to try and provide a more formal implementation of this pattern!
Things that I'm not sure about:
- What else to test for
- Whether using TraitError is appropriate (It doesn't really use any of the extra functionality TraitError provides)

HasRequiredTraits class

---

traits/ctraits.c
traits/tests/test_float.py
traits/trait_types.py

This PR cleans up validation for `Float` and `BaseFloat` traits, in preparation for applying similar fixes to the `Range` traits. The changes are:
- Allow anything with a `__float__` method to be assigned to a `Float` or `BaseFloat` trait. Previously, `BaseFloat` only accepted integers or `float` instances (so e.g., a `np.float32` instance would be rejected), and `Float` only accepted integers, `float` instances or `np.floating` instances.
- On assignment, the value is converted to an object of exact type `float`.
- So on retrieval, accessing the value of a `Float` trait will only ever give a Python `float`.
- Any exception _other_ than `TypeError` raised by `__float__` is propagated. A `TypeError` is interpreted as a non-type-match, so will either get converted to a `TraitError`, or …

Clean up Float and BaseFloat validation

---

traits/ctraits.c
traits/tests/test_regression.py

This PR fixes an odd error message and wrong exception type `TypeError` that should have been `TraitError` when attempting to assign a disallowed name in a `HasStrictTraits` subclass (for example).
Looking at the code, there are likely other instances of this pattern that need to be fixed, but that's not a reason not to fix this one (which has been encountered independently by several people).
Fixes #399 (and #415).

Fix exception message and type for Unicode HasStrictTraits attribute name.

---

README.rst
docs/source/conf.py

This mirrors the documentation setup for TraitsUI, where we try to use the [enthought-sphinx-theme](https://github.com/enthought/enthought-sphinx-theme) and fall back to the older defaults if this is not available. Though this presumably should only happen for someone building the docs locally, since anyone building them to upload to the website should probably just download the enthought theme!
This also fixes a bug where the docs would not build without a version of traitsui. This was due to the `DocMock` class calling `getattr(self, _mock_methods)` recursively on initialisation. 
There are some new warnings due to Traits having classes exclusive to python 2 - however sphinx effectively ends up just skipping these rather than it causing any problems (as far as I can tell anyway!). These …

Enthought Sphinx Theme for Docs

---

CHANGES.txt
docs/source/conf.py
docs/source/traits_user_manual/front.rst
docs/source/traits_user_manual/index.rst
setup.py

Note that the commit - https://github.com/enthought/traits/pull/438/commits/73ba9fcb0b5967ad88c3358fe12de91f80642d39 will be tagged with the 5.0.0 release.

Release traits v5

---

CHANGES.rst
traits/_py2to3.py
traits/adaptation/adaptation_manager.py
traits/api.py
traits/etsconfig/tests/test_etsconfig.py
traits/has_traits.py
traits/testing/tests/test_unittest_tools.py
traits/tests/test_class_traits.py
traits/tests/test_dynamic_notifiers.py
traits/tests/test_extended_notifiers.py
traits/tests/test_float.py
traits/tests/test_list.py
traits/tests/test_property_delete.py
traits/tests/test_traits.py
traits/trait_base.py
traits/trait_handlers.py
traits/trait_types.py
traits/traits.py

~NOTE : There is still one place where `sys.version_info`~
~I don't see any uses of `python_version`
but I'm not sure if we want to/can remove it completely.~
Replace it's usage with six.PY2/six.PY3 instead
and remove outdated pieces of code which added workarounds for
python < 2.7 and < 3.4
With this PR, #364 can be closed, as 2to3 have been replaced and 
sys.version_info usage has been removed.

Remove usage of sys.version_info

---

traits/tests/test_trait_types.py

There was an awkward test that needed to, in order, (1) try importing numpy to see whether the test should run at all, then (2) import traits.traits_types in an environment where numpy wasn't already imported. We were doing that by clearing out numpy-related entries in sys.modules, and that went wrong in #441. This PR replaces that test by one which runs the necessary imports in a subprocess, uncontaminated by previous NumPy imports.
Fixes #441

Avoid sys.modules hackery that was causing a NumPy-related test to fail.

---

traits/tests/test_file.py
traits/trait_types.py

Currently, the `exists` attribute of the Trait doesn't have any impact on the `FileEditor`. Without this fix, the editor we get for the following code:
```
from traits.api import HasTraits, File
class A(HasTraits):
f = File(exists=False)
```
is still the `open` version:
With this fix, we get the expected dialog:

ENH: Control dialog_style based on the Trait attribute.

---

setup.py

Quick drive-by PR addressing an OCD nitpick: use the full commit hash in the version file, rather than the 7 hex-digit abbreviated hash.

Use full commit hash instead of abbreviated hash in _version.py.

---

traits/has_traits.py
traits/tests/test_regression.py

#373 made instance traits (not `Instance` traits![*]) pickleable. While the aim was a good one, the change introduced a variety of unintended consequences and breakages, so I'm reverting it here. We may be able to do it again properly one day.
The main issues are:
1. Pickling instance traits requires that the corresponding `TraitType` objects are pickleable (whereas for class-level traits, we only need to pickle the trait values). Many `TraitType` objects currently _aren't_ pickleable, especially in Python 2. That could certainly be fixed: see #457 for some work in that direction, but there's much more to do.
2. Even in the absence of use of `add_trait` (which is relatively rare in most Traits projects), the `_instance_traits` dictionary has entries added to it whenever a listener is …

Revert enthought/traits#373: instance traits are no longer pickleable

---

traits/tests/test_file.py

This adds a `skipUnless` to a test that requires Traits UI, to ensure that that test doesn't fail if Traits UI is not installed.

Test fix: skip test that requires Traits UI if Traits UI is not available.

---

CHANGES.rst

#467 was merged to the release branch without a changelog entry (but can be folded into the entry for #451, since there hasn't been a release since #451); #466 should have been included in the earlier changelog update #465.

Add missing changelog entries for #466 and #467.

---

.travis.yml
CHANGES.rst
appveyor.yml
traits/tests/test_file.py

Bring changes from the release branch back into master:
- Conditionally skip a test that requires TraitsUI (#467)
- Update changelog (#465, #468)
- Update Appveyor and Travis CI configurations to run tests for all PRs; not just those against master.

Updates from release branch

---

CHANGES.rst
traits/_py2to3.py
traits/tests/test__py2to3.py

Fix failure of str_rfind for Unicode inputs

---

.travis.yml

Update the way the framebuffer is started to be compatible with Ubuntu Xenial.
Also tweaks a couple of other Travis CI settings along the way:
- don't fail fast
- don't send notifications to an email address that no-one listens to
cf: enthought/envisage#159

Fix Travis CI configuration for Xenial rollout

---

.travis.yml
etstool.py

- update travis config to handle cron jobs, using the `TRAVIS_EVENT_TYPE` environment variable. See https://docs.travis-ci.com/user/cron-jobs/ for more info.
- update the `install` command to install packages from source, specifically github, when a specific flag is passed to the command `--source`.
Together, we will not be able to test the traits package regularly using the master branches of dependencies e.g. `traitsui`.
Note that the cron job itself will need to be added manually from the settings pane of the travis project page.

Test packages from source using cron jobs

---

traits/testing/unittest_tools.py

Fix "who's" typo in docstrings

---

etstool.py

- Make `update` work again (it was using `python setup.py install`, where `install` was using `pip install .`).
- Add help and improved error reporting for the `--runtime` option.
- Various typo and grammar fixes.
- Fix top-level usage: now says "Usage: python etstool.py [OPTIONS] COMMAND [ARGS]...", instead of "Usage: etstool.py [OPTIONS] COMMAND [ARGS]...".
Fixes #508.

Various cleanups, fixes and enhancements in etstool.py

---

traits/has_traits.py
traits/tests/test_category.py

A second Category extension of a HasTraits subclass caused `Category` itself to be modified. This PR fixes that issue and provides a regression test.
Fixes #507.

Fix inadvertent modification of the Category base class.

---

etstool.py

Add `help` text to click.option
Click.option should ideally have a `help` text defined to be useful.

Click.option-s should have help text

---

etstool.py

`python etstool.py install` installs Traits from EDM (as a dependency of Traits UI), but doesn't uninstall it before `pip install`ing Traits from source. The result is that `site-packages/traits` ends up holding the contents of both the released and the new version of Traits. (It's a bit worrying/surprising to me that the `pip install` doesn't warn, or fail entirely.) The problem became visible when manually testing #515: we were ending up with both a `version.py` _and_ a `_version.py` file in the installed environment.
This PR fixes that.

Fix: remove EDM-installed traits before installing from source.

---

traits/__init__.py

Some cleanups to the top-level `__init__.py`:
- `NullHandler` is in the standard library since Python 2.7, and we don't support Python 2.6. Remove the redefinition and use the std. lib. version
- Add copyright header.

Remove redefinition of NullHandler

---

.gitattributes
setup.py

This PR adds the necessary Git magic to make it possible to retrieve the commit that an archive was generated from. This could help support building directly from a GitHub download.
Related: #515, enthought/envisage#190.

Make git commit hash available to archives.

---

setup.py

Previously, if a user tried installing traits from a source archive, the setup script would raise an error as it wont find a version file and it wont find a git source tree.
This PR adds support for local installation from source archives. It use the version information and archive info from setup.py (see PR #526 ) when generating version file for a source archive e.g. a git download archive
Note that the version number for an installation from source for an unreleased version will be of the form "a.b.c.dev-unknown" as the setup machinery will not be able to infer the rev list count to calculate the approriate dev number. Note that the git revision is still preserved to help debug any issues with such installations.
Note that these changes are borrowed from similar work in envisage.

Support installation from source archives

---

traits/util/weakiddict.py

This is deprecated since python 3.3, see https://docs.python.org/3.7/library/collections.html and will be remove in python 3.8.
It also removes the following warning:
```
/opt/miniconda3/lib/python3.7/site-packages/traits/util/weakiddict.py:25: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
class WeakIDDict(collections.MutableMapping):
```

Fix deprecated collections.MutableMapping import 

---

traits/has_traits.py
traits/tests/test_sync_traits.py

Closes #540 
The logic for computing the slice for a synced list trait when it was a partial slice was a little broke.
Small adjustment to assume if `event.index == None`, the slice starts at the first index, `0`.

Adjust slice calculation for sync trait items

---

traits/trait_types.py

Fix one odd-looking use of `super` that was using the `AdaptedTo` alias for `Supports` instead of using `Supports` directly.
While we're here, change one other use of `AdaptedTo` in a comment, so that we're consistently using `Supports` everywhere outside the support for the backwards compatibility alias.

Replace two occurrences of AdaptedTo with Supports.

---

traits/has_traits.py
traits/tests/test_sync_traits.py
traits/tests/test_traits.py
traits/trait_handlers.py

Previously, `myobj.mylist[:2] = new_list` would generate a `TraitListEvent` with `index=None`, while `myobj.mylist[0:2] = new_list` would generate a `TraitListEvent` with `index=0`. This PR changes the `TraitListEvent` creation so that the `index` is `0` in both cases.
This is an extension of @tmreay's PR #545 that keeps the existing test but uses a fix closer to the source of the problem.
Fixes #540.

Ensure TraitListEvent.index is always an integer

---

traits/tests/test_listeners.py
traits/tests/test_pickle_validated_dict.py
traits/tests/test_property_notifications.py
traits/tests/test_trait_list_dict.py
traits/util/tests/test_trait_documenter.py

This PR is preparation for changing the continuous integration to use unittest instead of nose.
We had only a handful of nose-style tests (i.e., tests not based on `TestCase`); this PR changes those to use unit test, and makes some minor renames to avoid some not-tests being picked up by nosetests.
With these changes, I see exactly 569 tests on master, with both `nosetests` and `unittest discover`.
And yes, some of these tests are horrible and in need of more work. But not in this PR.

Make sure that all tests are unittest-compatible.

---

etstool.py
tox.ini
traits/tests/test_traits.py

This PR switches the test runner used by etstool.py from `nosetests` to `unittest discover`. It also removes some other spurious or outdated occurrences of `nose` from the codebase and removes a non-working `tox.ini`.

Use unittest to run tests in continuous integration

---

traits/etsconfig/tests/test_etsconfig.py
traits/testing/tests/test_unittest_tools.py
traits/tests/test_category.py
traits/tests/test_interface_checker.py

Silence warnings and remove a `print` in a test.

Clean up test output

---

appveyor.yml

The "finish fast" setting is unhelpful: we sometimes still want to know whether things work on Python 3.5 / 3.6 even if the 2.7 job has failed.

Build update: don't finish fast.

---

traits/tests/test_cythonized_traits.py

Somewhat experimental PR to clean up the Cython tests:
- Cythonize with "language_level=3" to suppress warnings from Cython in the test output. (There's still an unreachable code warning from the compiler; there doesn't appear to be much we can do about that.)
- Factor out common code.
- Don't test whether Cython is usable in order to decide whether to skip tests: assume that if Cython is installed, then it's usable. This removes an import-time side-effect and simplifies the code.
- Remove a test that was designed solely to record an existing failing case; I've turned that into an issue instead (see #554).

Clean up Cython tests

---

.travis.yml
appveyor.yml
install-edm-linux.sh
install-edm-osx.sh
install-edm-windows.cmd

Update Travis CI and Appveyor to use EDM 2.0.0.
This should fix the issues we're seeing with CI on Python 3.6 (see CI runs for #559).
```
OkonomiyakiError: Unsupported PKG-INFO metadata format: u'2.1'
```

Update to EDM 2.0.0.

---

docs/source/traits_api_reference/has_traits.rst

`ViewElement` comes from TraitsUI, not Traits. It should be documented there. (It looks as though that's not currently the case; I'll open a separate issue in TraitsUI.)
This autodoc entry was causing some of the TraitsUI source to be included in the Traits documentation.
Fixes #492.

DOC: Don't autogenerate documentation for ViewElement

---

CHANGES.rst

This PR updates the changelog with all relevant changes between the 5.1.2 release and the upcoming 5.2.0 release.

Update changelog in prep for release

---

setup.py

Prepare for the 5.2.0 release. The changelog is ready; all we need to do is bump the version.

Bump Traits version for the 5.2.0 release.

---

README.rst

The badges on the [PyPI page](https://pypi.org/project/traits/5.2.0/) look fuzzy to my eyes; this PR fixes them to use .svg images instead of .png images. SVG is supported by all mainstream browsers these days, and the failure mode if it isn't should not be catastrophic.
Screenshot from PyPI:
For comparison, here's Envisage:

Use SVG badges in README

---

traits/ctraits.c
traits/has_traits.py

This PR removes the `HasTraits.trait_monitor` method: the current implementation is broken, undocumented, untested, and (as far as I can tell) unused elsewhere. As such, it's not worth the maintenance burden.
Closes #569

Remove HasTraits.trait_monitor

---

traits/has_traits.py
traits/tests/test_configure_traits.py

Two fixes to `configure_traits` when used with the `filename=` argument.
- Fixes use of undefined name "sm".
- Allows the specific filename to refer to a file that does not exist, as described in the documentation.
- Adds minimal unit tests, with `view_application` mocked.
Fixes #571

Fix issues with filename argument to configure_traits

---

traits/adaptation/tests/benchmark.py

The adaptation benchmark script was non-functional on Python 3. This PR fixes it.

Fix missing import in the adaptation benchmark script.

---

traits/ctraits.c
traits/tests/test_float_range.py

This PR changes the floating-point flavour of the `Range` trait to accept the same collection of values that the `Float` trait accepts: namely, instances of `float` (including objects whose type is a strict subclass of `float`), and objects whose type provides a `__float__` method.
This PR is self-contained, but doesn't fix all our range-related woes. There's more post-merge work to do on:
- equivalent changes for integer ranges
- refactoring to remove duplication of the range check code
- equivalent fixes for `BaseRange`
- dealing with float-like or int-like low and high
- equivalent changes for the `Range` trait handler

Fix floating-point Range to accept float-like values

---

traits/ctraits.c
traits/tests/test_float_range.py

This PR refactors the parts of `ctraits.c` having to do with range validation for float-based `Range` traits. It removes most of the duplication in the range-checking code.

Refactor duplicated range checks.

---

traits/ctraits.c

Minor cleanup in the ctraits.c code: clarify which case each of the entries in the `validate_handlers` table corresponds to.

CLN: Annotate validators with corresponding cases.

---

traits/tests/test_integer_range.py
traits/trait_types.py

This is the integer-analogue of #579.
This PR modifies the `Range` validation for integer-type ranges to match the validation used for the `Int`-type: any integer-like object that's within the `Range` bounds should be accepted.
Here integer-like means: either an instance of a subclass of `int`, or an object whose type provides the `__index__` method.
There's currently one known test failure on Python 3.6, which is fixed by #581.

Fix integer Range to accept integer-like objects

---

traits/tests/test_float_range.py
traits/trait_types.py

This PR fixes `BaseRange` for floating-point ranges so that it accepts the same values as `Range` does.
There's an expected test failure (for a test involving `BadFloatLike`), which should be fixed by #581.

Fix BaseRange to accept the same values as Range

---

traits/trait_types.py

Minor consistency fixes in numeric checks:
- Add `_validate_int` function to parallel `_validate_float`; all coercions to `int` should go through this function.
- Use `is` instead of `==` for a type comparison.
- Refactor `BaseInt` validation to use `_validate_int`.
- Refactor `int_validate` in `BaseRange` to match `float_validate`
- Fix bare excepts in validation for `CFloat`, `CInt` and `CComplex`.

Make float and int checks consistent

---

docs/source/traits_api_reference/trait_handlers.rst
docs/source/traits_user_manual/custom.rst
examples/tutorials/doc_examples/examples/use_custom_th.py
traits/api.py
traits/tests/test_traits.py
traits/trait_handlers.py

This PR removes the `TraitRange` subclass of `TraitHandler`. We've recently made a number of fixes to the `Range` and `BaseRange` traits, with the result that those trait types have diverged from `TraitRange`. Since `TraitRange` is essentially unused, it seems better to remove it than to try to propagate those fixes to it.

Remove TraitRange

---

traits/tests/test_traits.py

These tests were until recently tests for the now removed `TraitRange`; PR #587 opportunistically changed them to use `Range` instead of `TraitRange`. Unfortunately, the tests will fail with the newly refactored `Range`, due to a bug in the `Trait` type (see #592).
This PR removes the tests, which is probably what we should have originally done in #587.

Remove tests that depended on TraitRange

---

traits/util/clean_strings.py
traits/util/tests/test_clean_strings.py

This PR replaces the `clean_filename` function with a version that we've been using on other projects, and adds tests.
- Fix: `clean_filename` now returns a `str` instead of a `bytes` instance on Python 3
- Change: the set of permitted characters is further restricted to exclude "." and upper-case characters
- Enhancement: `clean_filename` takes a second argument, to be used as a replacement in case the cleaned string is empty
While subjective, the slugification is somewhat more user-friendly than it was: accented characters are replaced by unaccented ASCII equivalents where those exist, whitespace is replaced with hyphens.

Fix and improve clean_filename

---

traits/tests/test_extended_trait_change.py

Will mark as expected failures for now.  When #537 and #538 are resolved expected failures should be removed.

Add tests for extended trait change issues #537 and #538

---

traits/has_traits.py
traits/trait_types.py

This PR removes a small handful of unused imports and local variables, as identified by `flake8`.

CLN: Remove some unused imports and variables

---

traits/ctraits.c

The `Py_CLEAR` and `Py_VISIT` macros are avialable in Python 2.4  and later.
The `Py_CLEAR` macro in Python 2.7 is - https://github.com/python/cpython/blob/e6499033032d5b647e43a3b49da0c1c64b151743/Include/object.h#L780-L821 - which is the same as the macro definition in our codebase.
But the macro definition is different in Python 3.6 -  https://github.com/python/cpython/blob/0716056c49e9505041e30386dad9b2e788f67aaf/Include/object.h#L798-L839 .
The `Py_VISIT` macro in Python 2.7 is - https://github.com/python/cpython/blob/e6499033032d5b647e43a3b49da0c1c64b151743/Include/objimpl.h#L334-L346 - which is the same as the macro definition in our codebase and the macro definition is the same on Python 2.7 and Python 3.6

Remove definitions of unnecessary macros

---

traits/trait_handlers.py

The `BaseTraitHandler.repr` method was originally deprecated in traits version 3.0.3 and this PR removes it.

Remove deprecated method on BaseTraitHandler

---

traits/ctraits.c

Python version 2.5 is no longer supported.
For reference, here are the docs for `PyErr_format` - https://docs.python.org/3.6/c-api/exceptions.html#c.PyErr_Format - where the format characters are defined in - https://docs.python.org/2.7/c-api/string.html#c.PyString_FromFormat and https://docs.python.org/3.6/c-api/unicode.html#c.PyUnicode_FromFormat

Remove branch which handled python < and >= version 2.5

---

docs/source/traits_api_reference/trait_base.rst
docs/source/traits_user_manual/custom.rst
traits/trait_handlers.py

`TypeType` was originally defined in Python 2's `types` module, but was removed in Python 3 because it's an exact synonym for `type`.

Replace TypeType with type

---

etstool.py

This PR adds `--verbose` and `--quiet` options to the `python etstool.py test` command. It's convenient to run tests in quiet mode when looking for spurious test output (for example, deprecation warnings).

Make it possible to run tests quietly.

---

edm.yaml
etstool.py

Debugging without readline is painful, and EDM won't allow `gnureadline` to be installed after the fact, since it considers the development environment to be broken (as a result of uninstalling the traits package even though TraitsUI depends on it). This PR includes `gnureadline` in the development dependencies for platforms other than Windows.

Add gnureadline as a development dependency on macOS and Linux

---

traits/traits.py

Simple drive-by cleanup: make use of decorator syntax for `CTrait` properties.

CLN: Use decorator syntax for properties

---

traits/api.py
traits/has_traits.py

The abc module is available on both Python 2.7 and 3.6, which are supported by the traits package at the moment.
The code was originally added in https://github.com/enthought/traits/pull/15 , in Mar 2012, at which point Python 2.6 and 2.7 made the abc module available via the standard library. I'm not sure if the codebase had support for those versions of Python at that point in time, which is why the imports needed to be conditional.
Note that the PR added a test which also included conditional imports but that test module has been updated to remove the conditional imports (ref https://github.com/enthought/traits/pull/121/)

CLN : Remove the try/except around the abc import

---

traits/tests/test_trait_list_dict.py
traits/trait_handlers.py
traits/traits.py

This PR:
- fixes more uses of magic integers representing `default_value_type` constants
- adds a missing entry for `TRAIT_SET_OBJECT_DEFAULT_VALUE` to the `KindMap`
- rewrites the `_default_value_type` function to avoid magic, and to add checks for `TraitListObject`, `TraitDictObject` and `TraitSetObject`. Note that the `_default_value_type` code now very closely resembles corresponding code in `trait_handlers.py`.
- refactors to use the same default_value_type inference function in both `traits.py` and `trait_handlers.py`.

Fix more use of default magic constants

---

traits/api.py
traits/has_traits.py
traits/tests/test_view_elements.py

This is a refactor of the way that `ViewElements` are constructed, making it lazy.  The changed code now:
1. collects all `ViewElement` instances as part of `update_traits_class_dict` and extract them into a simple dictionary in `cls.__view_traits__`, no longer doing `Include` injection or base class analysis.
2. when we need to do something with the ViewElements, if `cls.__view_traits__` is a dict, then we do the initialization and replace the dictionary with the `ViewElement` instance.
Assumptions are that the only places that use `cls.__view_traits__` directly are `HasTraits.trait_views` and `HasTraits.clas_trait_view_elements` and so we only need to perform initialization here.
This is working towards #610.

Compute ViewElements lazily

---

traits/testing/optional_dependencies.py
traits/tests/test_configure_traits.py

This PR allows testers who require `traitsui` to do:
```
from traits.testing.optional_dependencies import requires_traitsui, traitsui
```
and then use `traitsui.api.<thing>` in a test without the need for further imports.
Motivated by #614

Make sure traitsui.api is available when traitsui is.

---

traits/api.py
traits/has_traits.py

This is the second part of solving #610  
This creates and ABC `AbstractViewElement` class and then registers `traitsui.view_element.ViewElement` as implementing the API when `traits.api` is imported.  This is an improvement over the current situation, as we can now get rid of the TraitsUI dependency in `traits.api` by:
1. Making `ViewElement` inherit from/register as `AbstractViewElement` when defining it in TraitsUI.
2. After sufficient time, when we can reasonably expect users to have updated their TraitsUI versions or explicitly require a version of TraitsUI that includes (1), we can remove the import.

Create an ABC for ViewElements

---

traits/ctraits.c
traits/has_traits.py
traits/tests/test_ctraits.py
traits/trait_handlers.py
traits/trait_value.py
traits/traits.py

Currently, the `cTrait.default_value` method does double duty: it's used both to set and to get the default value information for a Trait.
This PR refactors to add a separate method `cTrait.set_default_value` for setting, and deprecates the use of the `default_value` method for setting the default value.

Add cTrait.set_default_value

---

traits/tests/test_interfaces.py
traits/trait_types.py

Currently if `ISomeInterface` inherits from `Interface` (or more properly, is an instance of `MetaInterface`) and a value `value` is assigned to a trait of the form:
```
foo = Instance(ISomeInterface)
```
then the Traits interface checker kicks in and checks that `type(value)` conforms to the interface `ISomeInterface`.
This PR removes that check and replaces it with a simple `isinstance(value, ISomeInterface)`. With the reworked interfaces machinery, this should almost always be the right way to check for conformance to an interface.
Note: for ease of review and discussion, I've isolated the behaviour change in this PR. There's a lot more non-behaviour-changing cleanup that can be done once this goes in.

Change Instance(ISomeInterface) to use isinstance

---

docs/source/traits_api_reference/trait_types.rst
traits/trait_types.py

This PR soft-deprecates the various convenience trait types (`ListStr` and friends), marking them as deprecated in the documentation but not issuing any `DeprecationWarning`.
Rationale for the deprecation:
- In many cases these traits have surprising behaviour, because they're based on the old `TraitCoerceType` machinery rather than the new `TraitType` machinery. For example, `List(Float)` will accept NumPy floats, but `ListFloat` will not.
- The traits are unnecessary, and extra work to maintain (see the failed PR #622 for an example)
- These are trivial to replace with the right things. (For example, `ListStr` with `List(Str)`.)

Deprecate ListStr, DictStrFloat, ..., false, true convenience trait types

---

traits/has_traits.py
traits/trait_handlers.py

This simple PR extracts just two of the changes in #604. This fixes two places where the codebase uses `Missing` as a handy singleton, unrelated to the actual purpose of `Missing`.

Remove abuses of Missing

---

traits/ctraits.c
traits/trait_types.py

This is a follow-up to #630. Now that `validate_implements` merely does an `isinstance` check, we don't need to call it from the C code any more.
This PR replaces uses of `validate_implements` in both `ctraits.c` and `trait_types.py` with the corresponding `isinstance` check, and does some minor cleanup on that portion of `ctraits.c` in passing. It then removes `validate_implements` along with the private hook that makes that function available to `ctraits.c`.

Clean up BaseInstance and Instance validation

---

docs/source/traits_api_reference/trait_handlers.rst
traits/trait_handlers.py

This PR removes the `TraitWeakRef` subclass of `TraitHandler`. `TraitWeakRef` is ancient, untested, unused (at least within ETS), and superseded by the `WeakRef` trait type. More to the point, its removal takes us one step closer to being able to remove `TraitInstance`.

Remove ancient, untested and superseded TraitWeakRef class

---

traits/ctraits.c
traits/tests/test_integer.py

This PR changes the "type 12" fast validation to do an exact type check instead of an isinstance check in its fast path, before falling back to the usual slow path. This ensures that instances of subclasses of the target type are properly converted to the target type.
Fixes #646

Fix coercion fast validation to do an exact type check instead of an instance check

---

traits/has_traits.py
traits/tests/test_regression.py
traits/trait_value.py

This is a semi-automated drive-by fix.
The `_notifiers` methods of `CHasTraits` and `CTrait` expect one argument that tells the method whether to create a list of notifiers if one doesn't already exist.  Most calls to this use 1 and 0, but it would be clearer if they used `True` and `False` instead.
This PR applies that change.

Clearer calls to _notifiers methods

---

traits/ctraits.c

This PR fixes (all) three uses of `->ob_type` in `ctraits.c`.  This fixes build failures of the form:
```
traits/ctraits.c:975:21: error: no member named 'ob_type' in 'struct _trait_object'
assert( PyTrait_CheckExact( trait ) );
~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
traits/ctraits.c:53:39: note: expanded from macro 'PyTrait_CheckExact'
#define PyTrait_CheckExact(op) ((op)->ob_type == ctrait_type)
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
(__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
^
traits/ctraits.c:1001:13: error: no member named 'ob_type' in 'struct _trait_object'
assert( PyTrait_CheckExact( trait ) );
~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
traits/ctraits.c:53:39: note: …
```

Fix uses of ->ob_type

---

traits/ctraits.c

Follow-up to #561 
- Parse the "force_create" argument as a boolean, just for a consistent duck-typing approach
- Add a better docstring for the method.

Improve docstring for cTrait._notifiers; make argument a boolean

---

traits/ctraits.c

Fixes #662 
This simply removes the method and no more.

Remove cast method from cTrait class

---

traits/ctraits.c

This is a quick clean-up to allow functions and methods in ctraits.c that expect boolean values (represented as integers) to accept any truthy or falsey value by using the `p` "predicate" argument for `PyArg_ParseTuple`.
Also cleans up some indentation.

Convert boolean int "i" parameters to predicate "p" parameters.

---

traits/ctraits.c
traits/tests/test_ctraits.py
traits/trait_handlers.py
traits/trait_types.py
traits/traits.py

These are exposed as properties.  Where it makes sense, they are settable. Work is likely needed on names.
This might be used as a basis for removing certain `cTrait` methods, notably `is_mapped`, `setattr_original_value` and `post_setattr_original_value`, and the uses of those in traits has been modified to use the flags directly (they are not used in ETS outside of traits).
Fixes #193.

Exposure of cTrait flags to Python

---

traits/ctraits.c
traits/tests/test_ctraits.py
traits/trait_handlers.py
traits/trait_types.py
traits/traits.py

Renames flag properties to more natural names, removes setter methods
that are now unusued or conflict with property names.
(cherry picked from commit 065f2f26c22f736d05dcd014e00b81f5df3b10c6)
This is a recreation of #672 on top of master; recreating was easier than fixing the merge conflicts.

Refactor of flags and the methods that set them.

---

README.rst
docs/source/conf.py

- Remove use of mocking from the configuration file. The Traits documentation no longer documents anything from Traits UI, so this is unnecessary.
- Fix a deprecated autodoc option, which is removed in Sphinx 3.0
- Require Sphinx >= 1.8. (The replacement autodoc option for the above was introduced with Sphinx 1.8).

Sphinx configuration cleanups: no more mocking, fix deprecated option

---

docs/source/traits_api_reference/trait_handlers.rst
traits/trait_handlers.py

`TraitCallable` is untested, and unused within ETS and within ETS-using projects that I have access to the source for. Let's remove it for 6.0.

Remove TraitCallable

---

docs/source/traits_api_reference/trait_handlers.rst
traits/trait_handlers.py

Like `TraitCallable`, `TraitExpression` is untested, and unused either within Traits or elsewhere in ETS or any project code that I have access to. This PR removes it.
See also #697.

Remove TraitExpression

---

traits/util/tests/test_clean_strings.py

The ASCII decimal digits were being specified twice in `LEGAL_CHARS`, for no apparent reason.

Fix unnecessarily repeated characters in a test

---

traits/ctraits.c

A drive-by cleanup extracted from some more functional changes:
- Use `METH_NOARGS` for two functions instead of validating explicitly that there are no arguments using `PyArg_ParseTuple`
- Make sure that a second argument is always supplied for `METH_NOARGS` functions, and suppress compiler warnings about that second argument being unused.

Clean up METH_NOARGS functions

---

traits/ctraits.c
traits/tests/test_has_traits.py

This PR adds a `_class_traits` method to `CHasTraits` for introspection purposes. There's currently no other reliable and obvious way to get the `_class_traits` dictionary that a `CHasTraits` instance is actually using at any particular moment; in particular, the returned dictionary may or may not match the result of `my_has_traits_object.class_traits()`.

Add a CHasTraits._class_traits() method

---

traits/ctraits.c
traits/tests/test_has_traits.py

This PR adds new private methods on `CHasTraits` to allow introspection of the `HASTRAITS_NO_NOTIFY` and `HASTRAITS_VETO_NOTIFY` flags. In current master, those flags can be set, but cannot be directly read.
- `CHasTraits._trait_notifications_enabled` reports whether notifications are currently enabled for this object.
- `CHasTraits._trait_notifications_vetoed` reports whether notifications are currently vetoed for this object.
Closes #703

Expose HASTRAITS_NO_NOTIFY and HASTRAITS_VETO_NOTIFY flags

---

traits/trait_handlers.py
traits/trait_types.py
traits/util/import_symbol.py
traits/util/trait_documenter.py

We are leaving the `exec`-based dynamic import alone `TraitClass` in favour of removing completely in #710 
Using import_module removes the need to use `getattr` to step down through the packages.

Replace uses of __import__ with import_module

---

traits/ctraits.c

This PR:
- fixes some premature optimization in `ctraits.c` (precomputed `empty_tuple` and `empty_dict` constants)
- simplifies some tuple building

Remove empty_tuple and empty_dict globals from ctraits.c

---

docs/source/traits_api_reference/constants.rst
traits/api.py
traits/constants.py
traits/tests/test_constants.py

This PR:
- moves the `NO_COMPARE` aliases from `api.py` to `constants.py`, and imports them in `api.py`
- documents those aliases (including documenting that they're deprecated)
- adds tests for the aliases
- fixes formatting issues in the existing `ComparisonMode` documentation
Closes #695.

Move and document ComparisonMode member aliases

---

traits/has_traits.py
traits/tests/test_static_notifiers.py

Traits was manually performing the double-underscore name-mangling without taking into account a corner-case.

BUG: Fix name-mangling of __methods in _Classes

---

traits/util/tests/test_trait_documenter.py

This PR fixes a warning about behaviour change of `DocumenterBridge`, which is used explicitly in the `trait_documenter` tests.
Closes #690.

Fix a Sphinx deprecation warning in tests.

---

traits/ctraits.c

Add note to clear up potentially confusing reference counting details in ctraits.c

Add note that get_prefix_trait returns a borrowed reference.

---

traits/tests/test_anytrait_static_notifiers.py
traits/tests/test_dynamic_notifiers.py
traits/tests/test_extended_notifiers.py
traits/tests/test_static_notifiers.py
traits/tests/test_traits.py

Checking for reference leaks involves running test modules repeatedly and looking at the way that the total reference count changes. Unfortunately, some of our tests fail when run repeatedly. This PR fixes most of those tests to avoid mutating global state, or at least to reset the state so that the test doesn't fail when run a second time.
Related: #725.

Make tests repeatable

---

traits/tests/test_new_notifiers.py

Fix `test_new_notifiers` to join the threads that it implicitly creates. This means that refleak testing no longer reports a reference leak for this test.
Also replaces a `time.sleep` with code which explicitly waits for the desired result.
Related to #725.
Fixes #727.

Fix test to join implicitly-created threads

---

.clang-format
traits/ctraits.c

This PR introduces a `.clang-format` file and applies two automated reformatting steps to ctraits.c, to bring it much closer to the PEP 7 recommended style, and in particular to deal with unusual and inconsistent spacing around function names and arguments.
This is intended as a one-time change for cleanup purposes, and not as a style that will be enforced on new contributions. Future file-wide reformattings like this one should be rare.
For the record, the two steps applied are given below; they'll need adjustment for different development setups. I was using Clang 9.0.
```
$ /opt/local/bin/clang-tidy-mp-9.0 traits/ctraits.c -checks=readability-braces-around-statements --fix -- -I/opt/local/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8
$ …
```

Reformat ctraits.c

---

etstool.py

This PR:
- adds a new `--error-on-warn` option to the `python etstool.py docs` command
- makes `--error-on-warn` the default.
This means that the CI will fail for future PRs that cause new documentation warnings. If that proves excessive (there are false positives that we can't easily work around), we might change the default here, or run the documentation build in a separate job that can be ignored for PR approval purposes.
Closes #743.

Turn warnings into errors in documentation build

---

traits/adaptation/api.py
traits/api.py
traits/etsconfig/api.py
traits/testing/api.py
traits/util/api.py

This is part of work towards making the Traits codebase a little bit more clean, and eventually introducing flake8 checks to keep it that way.
This PR fixes false flake8 positives about unused imports from the `api.py` modules. (The other way of fixing this is to introduce and use `__all__` everywhere, but that results in a *lot* of duplication, especially in the top-level `api.py`).
For consistency, I've removed the `__all__` from `traits.utils.api`.

Fix flake8 warnings from api imports

---

traits/ctraits.c
traits/tests/test_ctraits.py

closes #721 
- also added a test to assert a `ValueError` is raised.

Raise ValueError for invalid args to ctrait.comparison_mode

---

docs/source/conf.py
traits/util/tests/test_trait_documenter.py
traits/util/trait_documenter.py

We no longer need these: file encoding defaults to UTF-8 for Python 3.

Remove coding cookies

---

traits/tests/test_container_events.py
traits/tests/test_str_handler.py
traits/tests/test_traits.py

This PR removes some unnecessary `print`s from the test suite. There are still `print`s in `test_property_notifications.py`, which needs a closer look (see #751).

Remove print statements from test suite

---

copyright_header/copyright_header.py
copyright_header/setup.py

This PR adds a flake8 plugin for checking copyright headers on files.
Usage:
- `pip install copyright_header/`
- `flake8 <target_file>`
Or to just see the header errors:
- `flake8 --select=H <target_file>`
Working towards #692.

Add flake8 plugin for checking copyright statements

---

traits/trait_set_object.py

closes #733 
- As explained in the issue, this is no longer needed in Python 3.

remove TraitSetObject.copy

---

etstool.py
setup.cfg

Minor tweak to the flake8 configuration: put the exclusion of the "examples" directory into the flake8 config in `setup.cfg`.
This makes it easier to run flake8 during development: when inside the development environment, a developer can simply run `flake8` instead of having to go through `etstool`.

Keep flake8 configuration in a single place

---

traits/trait_handlers.py

contributes to #697
- copied the methods from`ThisClass` to `TraitInstance`.

implement TraitInstance to inherit directly from TraitHandler

---

docs/source/traits_api_reference/trait_types.rst
examples/tutorials/traits_4.0/interfaces/adaptation.py
traits/trait_types.py

Fixes #723 
Should the change be made to the examples (`examples/tutorials/traits_4.0/interfaces/adaptation.py `)as well ? 
Why is it under a folder named "traits_4.0" ?

Move AdaptedTo to list of deprecated traits

---

traits/tests/test_property_notifications.py

Fixes #751 
PR removes print statements and checks a stream output to check if values are written there.
Unsure if this is a better way to test.

Remove print statement and fix test_property_notfications

---

.travis.yml
traits/ctraits.c

This is an experimental PR, intended to make CI fail on compiler warnings. At the moment, it's way too easy to miss important warning messages from gcc/clang when testing local changes to ctraits.c.

Abort CI on compiler warnings

---

traits/tests/test_list_events.py
traits/tests/test_traits.py
traits/trait_list_object.py

Closes #742
Updates the behaviour of list events when setting or deleting list objects via a slice with step size != 1.
Previously the added and deleted elements would be wrapped in an extra containing list:
https://github.com/enthought/traits/blob/d8d851e72ae9d32920eb9216a583484dda0dc4e1/traits/tests/test_traits.py#L1110-L1115
This PR removes this containing list to bring the behaviour more in line with that of other list actions.
Note there is still some bugwards-compatibility code in `TraitListObject`'s `__setitem__` and `__delitem__` that is out-of-scope of this PR: the `index` of certain events is 0 in cases where the expectation would be a slice:
https://github.com/enthought/traits/blob/d8d851e72ae9d32920eb9216a583484dda0dc4e1/traits/tests/test_traits.py#L1100-L1105
Opened #772 for …

Remove containing list around added and removed items in some list events

---

docs/source/traits_api_reference/trait_handlers.rst
traits/tests/test_deprecated_handlers.py
traits/trait_handlers.py

closes #697
Added deprecation warning messages to these handlers
```
ThisClass
TraitDict
TraitEnum
TraitFunction
TraitList
TraitMap
TraitPrefixList
TraitTuple
```

Deprecate non-essential trait handlers

---

traits/traits.py

Remove the unused and empty `SpecialNames` dictionary, and remove commented out date and time trait definitions.

Remove commented-out and unused code

---

.travis.yml

We have various C-level `assert`s in `ctraits.c`. Right now, those do us no good at all because the extension is being built with `-DNDEBUG`. This PR adds `-UNDEBUG` to the build flags, which cancels the `-DNDEBUG` out.

Enable C asserts

---

docs/source/traits_api_reference/trait_converters.rst
traits/api.py
traits/tests/test_trait_converters.py
traits/trait_converters.py

closes #755.
- Also re-implemented `trait_cast` as a wrapper around `as_ctrait`.

Add `as_ctrait` converter function to traits api

---

traits/trait_converters.py
traits/trait_type.py
traits/traits.py

Refactor trait converters to use `as_ctrait`

---

traits/has_traits.py
traits/tests/test_configure_traits.py

Fix a sneaky `True` that was telling `configure_traits` to use pickle protocol 1 when writing. Now that we're Python 3 only, there's little excuse for using anything lower  than protocol 3.
See also #792.

Use pickle protocol 3 in configure_traits

---

traits/has_traits.py
traits/tests/test_configure_traits.py

Somewhat related to #787, we should deprecate the use of pickles for saving state between invocations of `configure_traits`.

Add a DeprecationWarning for configure_traits() pickles

---

traits/ctraits.c
traits/tests/test_callable.py

Fix validation of a `Callable` trait inside an `Either`.
Fixes #793

Fix validation of Callable in a compound trait

---

docs/source/conf.py
docs/source/traits_user_manual/notification.rst
traits/trait_dict_object.py
traits/trait_list_object.py
traits/trait_set_object.py

This PR improves the documentation of the `TraitListObject`, `TraitSetObject` and `TraitDictObject` and the corresponding `TraitListEvent`, `TraitSetEvent` and `TraitDictEvent` classes.
In particular it details the behaviour of `TraitListObject`s which have slices set or deleted.  It also generally improves the documentation of `_<name>_items_changed()` and associated infrastructure.
This should fix #772 (I don't think we should change the behaviour as it will likely break code, but we may want to open a new issue).
Finally, because I needed to test whether new index entries were included, this fixes #809.

Improve documentation of trait container objects

---

traits/trait_types.py

`ValidateTrait.int_range` is unsupported, and documented as unused. This PR removes a line of code that (a) uses it, but (b) never actually gets executed in practice, to eliminate the danger of that line of code being used in the future.
Closes #684

Make it less likely that we use ValidateTrait.int_range accidentally

---

traits/api.py
traits/editor_factories.py
traits/trait_types.py

Rename DateTime trait to Datetime trait

---

traits/tests/test_property_notifications.py
traits/tests/test_traits.py

This PR moves creation of a class that uses `TraitList` into the `setUp` method of the test that uses it, so that we can suppress the associated `DeprecationWarning`.
Closes #803

Suppress deprecation warning from test suite

---

traits/trait_handler.py
traits/trait_handlers.py

The docstrings for the TraitHandlers (and TraitHandler) had a number of issues:
- examples not formatted properly
- `__init__` docstrings instead of class docstrings for parameters
- confusion between parameters and attributes
- incorrectly formatted "Returns" sections
- assorted other minor problems
This PR cleans all of that up.

Fix TraitHandlers documentation

---

docs/source/traits_api_reference/ctraits.rst
docs/source/traits_api_reference/index.rst

This PR adds `traits.ctraits` to the API documentation.
Note that the module section title in this PR is inconsistent with master, but consistent with the changes in #823.
Closes #822

Include traits.ctraits in API documentation

---

docs/source/traits_api_reference/base_trait_handler.rst
docs/source/traits_api_reference/constants.rst
docs/source/traits_api_reference/ctrait.rst
docs/source/traits_api_reference/editor_factories.rst
docs/source/traits_api_reference/has_traits.rst
docs/source/traits_api_reference/index.rst
docs/source/traits_api_reference/interface_checker.rst
docs/source/traits_api_reference/trait_base.rst
docs/source/traits_api_reference/trait_converters.rst
docs/source/traits_api_reference/trait_dict_object.rst
docs/source/traits_api_reference/trait_errors.rst
docs/source/traits_api_reference/trait_factory.rst
docs/source/traits_api_reference/trait_handler.rst
docs/source/traits_api_reference/trait_handlers.rst
docs/source/traits_api_reference/trait_list_object.rst
docs/source/traits_api_reference/trait_notifiers.rst
docs/source/traits_api_reference/trait_numeric.rst
docs/source/traits_api_reference/trait_set_object.rst
docs/source/traits_api_reference/trait_type.rst
docs/source/traits_api_reference/trait_types.rst
docs/source/traits_api_reference/traits.adaptation.rst
docs/source/traits_api_reference/traits.etsconfig.rst
docs/source/traits_api_reference/traits.protocols.rst
docs/source/traits_api_reference/traits.rst
docs/source/traits_api_reference/traits.testing.rst
docs/source/traits_api_reference/traits.util.rst
docs/source/traits_api_reference/traits_listener.rst
docs/source/traits_api_reference/version.rst

Fix module references in the API documentation. Module titles are now of the form "traits.trait_types" rather than simply "trait_types".  (We could fix the references *and* have the module titles simply be the name of the module, but I prefer having the full package path in the section titles.)
Also:
- Remove the `traits.protocols.rst` stub. The `protocols` package was removed a long time ago, now, and is ancient history.
- Remove the extra section titles for the traits subpackages (`traits.testing`, `traits.adaptation`, ...).
- Add missing module `traits.testing.optional_dependencies`

DOC: Fix module references

---

traits/tests/test_configure_traits.py

Fix one more warning about the deprecated filename argument to configure_traits.

Fix one more DeprecationWarning from the test suite

---

traits/tests/test_property_notifications.py

`test_property_notifications` mutated global state so that running it a second time failed. This PR fixes that.
Closes #801

Make test_property_notifications repeatable

---

docs/source/conf.py

The coverage extension is valuable for discovering which objects, classes, methods, etc. are undocumented. Use it with (for example) `sphinx-build -b coverage source/ build/` from the `docs` directory.

Enable the coverage extension

---

traits/trait_base.py
traits/trait_types.py

Revert enum defaults to using index 0 except for `enum.Enum`s, which instead use the first value returned from the iterator.
This restores the default behaviour to exactly what it was before the introduction of support for `enum.Enum` other than special-casing default values for `enum.Enum`.

Revert Enum default computation

---

traits/ctraits.c

Add a defensive C `assert` to catch the case of an invalid validator code.

Defensive assert on failed fast_validator

---

CHANGES.rst

This is a first cut at a changelog for the 6.0.0rc0 release.
Still to do:

Update changelog for the 6.0.0rc0 release.

---

traits/tests/test_editor_factories.py

Fixes #847 
Needs backport to the 6.0 release branch.

Fix test for DatetimeEditor to avoid failure if TraitsUI not installed

---

CHANGES.rst
traits/tests/test_editor_factories.py

Backport of #848 from master branch to the 6.0.x release branch

Fix DatetimeEditor test ImportError when traitsui not installed (#848 backport)

---

docs/source/traits_api_reference/trait_types.rst
traits/trait_types.py

General overhaul of docstrings in the `traits.trait_types` module.
- Moved parameters from __init__ to class docstrings
- Added class attributes.
- Cleaned up exposition where it was needed.

Improved API documentation for trait_types

---

traits/api.py

Closes #856 
No unit tests because we don't test contents of `traits.api`. Perhaps we should.

Make DefaultValue, ValidateTrait and TraitKind available in traits.api

---

docs/source/traits_api_reference/trait_numeric.rst
traits/adaptation/adapter.py
traits/etsconfig/etsconfig.py
traits/testing/unittest_tools.py
traits/trait_numeric.py
traits/util/event_tracer.py

This cleans up a few more class docstrings where there was an `__init__` docstring, either moving the information to the class docstring, or removing entirely when it was non-informative.
This includes a couple of drive-by cleanups of functions with bare `return` statements at the end.

Additional class docstring fixes

---

CHANGES.rst
traits/api.py

This is a backport of #857 from master to the release branch.

Add new enumeration types to traits.api (#857 backport)

---

docs/source/traits_user_manual/custom.rst

Related to #385 but I also ran into missing the get_value in the get method luckily I knew where to go this time, but it should be in the documentation.

Add details on creating custom trait properties

---

traits/tests/test_trait_base.py
traits/trait_base.py

Also adds some unit tests for `safe_contains`.
Fixes #853

Avoid containment-related DeprecationWarning on Python 3.7

---

CHANGES.rst
traits/tests/test_trait_base.py
traits/trait_base.py

Backport of #855 from the master branch to the release branch.

Fix Enum-related safe_contains DeprecationWarning (#855 backport)

---

docs/source/conf.py
setup.py
traits/etsconfig/tests/test_etsconfig.py
traits/has_traits.py
traits/tests/test_trait_types.py
traits/util/event_tracer.py
traits/util/resource.py
traits/util/tests/test_record_containers.py
traits/util/tests/test_record_events.py
traits/util/tests/test_trait_documenter.py

- Always specify an encoding for text files.
- Use a `with` statement to open the file where possible.
- Replace some leftover uses of `io.open` with `open` (the two are identical in Python 3; the `io.open` version was present for backwards compatibility with Python 2).

CLN: Follow best practices when opening files

---

docs/source/conf.py
examples/tutorials/doc_examples/examples/adapt_metadata.py
examples/tutorials/doc_examples/examples/add_class_trait.py
setup.cfg
traits/adaptation/adaptation_manager.py
traits/adaptation/adaptation_offer.py
traits/adaptation/tests/test_adapter.py
traits/base_trait_handler.py
traits/constants.py
traits/etsconfig/etsconfig.py
traits/has_traits.py
traits/testing/unittest_tools.py
traits/tests/test_listeners.py
traits/trait_base.py
traits/trait_dict_object.py
traits/trait_errors.py
traits/trait_handlers.py
traits/trait_list_object.py
traits/trait_notifiers.py
traits/trait_numeric.py
traits/trait_types.py
traits/traits.py
traits/traits_listener.py
traits/util/resource.py

- Remove E501 (line too long) from the flake8 ignore list
- Fix existing violations of E501
- Opportunistically remove banner-style docstrings. (There are some remaining.)

Unignore long lines in flake8 check

---

traits/ctraits.c
traits/tests/test_ctraits.py

Fix #827 
Allow setting CTrait.post_setattr to None

Allow assigning None to CTrait.post_setattr

---

setup.py

[Broken out of #878 as an independently useful piece]
This PR adds an `extras_require` containing the optional dependencies of the test suite. This means that running the Traits test suite with minimal skipped tests is as easy as:
```bash
$ python -m venv --clear ~/.venvs/traits
$ source ~/.venvs/traits/bin/activate
$ pip install -e .[test]
$ python -m unittest
```

Add extras_require entry for testing

---

traits/testing/nose_tools.py
traits/testing/tests/test_nose_tools.py

We don't test the machinery in `traits.testing.nose_tools`, but ~there are other parts of ETS that still use it~. Those users are likely no longer using `nose` to run their test suites.
EDIT: I'm only seeing uses of `nose_tools` in etsproxy, which we don't care about at this point. No other uses of `nose_tools` in ETS. Still, there might be external uses that we don't know about, so we can't simply delete without warning.
Related: #852.

Deprecate traits.testing.nose_tools

---

docs/source/traits_api_reference/trait_types.rst
traits/api.py
traits/tests/test_prefix_list.py
traits/trait_types.py

Closes #676 
This PR creates a trait type `PrefixList` which has the same functionality as `TraitPrefixList` handler for a trait.
- No algorithm changes have been made for the validation.
- C level fast validation is not used for this trait.
- Assigning a `default_value` which is not part of the list of legal strings will throw a `ValueError` during trait declaration.
- If a `default_value` is unspecified, it is set to `None` (unsure if this is what we want)
TraitPrefixList is still available but could be deprecated in the future.

Add a PrefixList trait type

---

docs/source/traits_user_manual/notification.rst

Adds a note near the pattern names examples section for nested pattern names for list and dict. This is intended to make the special cases of supported handler signatures more discoverable.
Closes #893

DOC: Add note to list and dict special cases near examples

---

CHANGES.rst
setup.py

In the two weeks since the 6.0.0rc0 release, no blocking issues have emerged. So we'll re-release as 6.0.0 final.
This PR updates the changelog and bumps the version accordingly.
Once released, we still need to build and update docs.

Bump version, update changelog for the 6.0 final release

---

traits/ctraits.c
traits/tests/test_callable.py
traits/trait_types.py

Fixes #773 
PR adds a new optional argument `allow_none` to the `Callable` trait, which if set to `False`  prevents `None` from being assigned to the trait.
If not specified, defaults to `allow_none=True`, leaving the current behavior unchanged.

Add allow_none flag for Callable trait

---

docs/source/conf.py
docs/source/traits_user_manual/front.rst
docs/source/traits_user_manual/index.rst

Replace 'Traits 5' with 'Traits 6' in the documentation

---

docs/source/traits_api_reference/has_traits.rst
traits/has_traits.py
traits/tests/test_has_traits.py

Fix #881 
PR updates creates a Deprecated Classes section in the has_traits docs.

Deprecate SingletonHasTraits & related classes

---

traits/ctraits.c
traits/tests/test_callable.py

Fix ref count error issue #906

---

traits/ctraits.c

Since I already had this half-done in the meeting, here's a PR that cleans up remaining uses of `PyTuple_New(n)` with `n` a positive constant. One exception: I didn't replace the use of `PyTuple_New` to create a tuple of length 15 when pickling ...

Use PyTuple_Pack where possible

---

traits/ctraits.c
traits/tests/test_trait_get_set.py

Part of #914 
This PR:
(1) Makes `call_notifiers` terminates early if `trait_change_notify` is set to `True`.
(2) Adds two tests to exercise the public API `trait_set` and `trait_setq` relevant for the same logic.
The logic has been exercised by an existing test, e.g. if I commented out the relevant code in `ctraits.c`, the following existing test fails:
```
FAIL: test__trait_notifications_enabled (traits.tests.test_has_traits.TestHasTraits)
----------------------------------------------------------------------
File "/Users/kchoi/.edm/envs/traits-test-3.5/lib/python3.5/site-packages/traits/tests/test_has_traits.py", line 268, in test__trait_notifications_enabled …
```

Maint: Check trait_change_notify early in call_notifiers

---

traits/ctraits.c
traits/tests/test_ctraits.py
traits/tests/test_has_traits.py

Part of #914 
This PR refactors calling trait and object notifiers by concatenating the lists of notifiers and then call them all.
~This PR will have a trivial merge conflict with #917 due to the change in exit code name.~ Resolved.
*UPDATED*
There is a behaviour change, see comment 👇

Refactor ctraits.c for calling trait and object notifiers

---

traits/adaptation/adaptation_manager.py
traits/adaptation/adaptation_offer.py
traits/adaptation/tests/test_adaptation_manager.py
traits/etsconfig/etsconfig.py
traits/etsconfig/tests/test_etsconfig.py
traits/testing/unittest_tools.py
traits/tests/test_array.py
traits/tests/test_clone.py
traits/tests/test_container_events.py
traits/tests/test_copy_traits.py
traits/tests/test_delegate.py
traits/tests/test_dict.py
traits/tests/test_event_order.py
traits/tests/test_interface_checker.py
traits/tests/test_list.py
traits/tests/test_rich_compare.py
traits/tests/test_str_handler.py
traits/tests/test_undefined.py
traits/trait_set_object.py
traits/util/resource.py
traits/util/tests/test_import_symbol.py

This PR removes redundant return statements at the ends of functions and methods.
Note: with 3 exceptions (noted in review comments), these are all simply removal of a `return` at the end of a function or method.

Remove redundant return statements

---

etstool.py

- Install `mypy` from EDM instead of via `pip`
- Remove the `docs` argument to `install` (which prints a message about having installed `enthought_sphinx_theme` even when it's done no such thing).
- Fix space handling in `_get_install_command_string` to avoid double spaces

Tweaks to etstool.py

---

traits/tests/test_traits_listener.py

This PR adds unit tests for ListenerParser.
Most of the parsing logic are already covered in other tests on the integrations with `on_trait_change`. While this PR brings in small increase of coverage, the added tests serve as some kind of documentation for the current mini-language.
The coverage on the ListenerParser is still not 100%.

Maint: Add tests for parsing on_trait_change mini-language

---

traits/tests/test_extended_trait_change.py

This PR replaces `unittest.expectedFailure` with a more refined scope of expected assertion error.
This allows more of the test code to be exercised.  This also prevents new unexpected errors from getting silenced by `expectedFailure` (which does not differentiate test errors from test failures).
Motivation: For my understanding, I wanted to see the test failures that illustrate #537 and #538

Maint: Refine where the expected failures are

---

traits/has_traits.py
traits/tests/test_get_traits.py
traits/tests/test_has_traits.py

Fix #925 
Includes the names from `super().__dir__()` in the `HasTraits.__dir__`'s output.

Improve HasTraits introspection with `dir()`

---

traits/constants.py
traits/ctraits.c
traits/trait_base.py
traits/trait_handlers.py

This is a recreation of #688. This PR re-uses the *_DEFAULT_VALUE constants defined in `ctraits.c` in `constants.py`, instead  of duplicating the integer values.
This is pure refactor, so there should be no change in behaviour (and consequently, no new tests or documentation needed).
Closes #686.

Refactor: fix duplication of DEFAULT_VALUE constants

---

traits/editor_factories.py
traits/tests/test_editor_factories.py

This PR fixes the datetime to-and-from string conversions used in the `DatetimeEditor`:
- For str-to-datetime, allow the empty string to be converted to `None` (a `Datetime` trait allows `None` by default)
- For str-to-datetime, we can reasonably assume that the argument is a string, so the `is not None` check is pointless. Remove it.
- For datetime-to-str, make sure we always return a string, returning the empty string for an input of `None`. 
Fixes #936

Fix the datetime-to-str converters

---

traits-stubs/traits-stubs/trait_types.pyi
traits/tests/test_constant.py
traits/trait_types.py

Fixes #819 
This PR removes a restriction on the `Constant` trait where the `Constant` trait could not be initialized with mutable types such as `list` and `dict`.

Allow mutable values in Constant trait, add tests

---

traits/trait_list_object.py
traits/trait_set_object.py

Fix code that pretends it's returning a value, when it's not. It looks as though this was simply a hacky shortcut for calling the superclass for its side-effect and then doing a plain return.
The old code confuses some static analysis tools (like PyLint, for example).

Don't pretend to return a value when nothing is being returned

---

traits/tests/test_historical_unpickling.py

Nose identifies the `find_test_pickles` helper function as a test, and so a simple `nosetests .` fails.  This PR renames the function to avoid `nosetests` identifying it as a test.
Closes #943.

Rename find_test_pickles to avoid confusing nosetests

---

traits/tests/test_map.py

There is an assertion in test that is redundant - this PR removes it.
**Checklist**

Remove a redundant assertion in test

---

docs/source/traits_user_manual/defining.rst
traits/has_traits.py
traits/trait_handlers.py
traits/trait_types.py

Fix a Python example in a docstring (without this, the example code doesn't get syntax highlighted properly in the output).
EDIT: Added some more similar fixes after a search through the codebase.

Fix reST markup in a documentation example

---

traits-stubs/traits-stubs/trait_types.pyi
traits/trait_types.py

**Checklist**
~~- [ ] Tests~~ Exists
~~- [ ] Update API reference (`docs/source/traits_api_reference`)~~ Remains the same.
~~- [ ] Update User manual (`docs/source/traits_user_manual`)~~ Had no mention of if. 
This PR fixes #952
- Refactors the `PrefixMap` class to inherit from `TraitType` instead of `Map`
- Removes fast validation for `PrefixMap`

Refactor PrefixMap

---

traits/tests/test_prefix_list.py
traits/tests/test_prefix_map.py
traits/trait_types.py

This PR refactors the `PrefixMap.validate` and `PrefixList.validate` methods for simplicity, clarity and consistency with each other.
Along the way, it fixes #955 and #957.
~Additional tests on the way.~ No API changes, so no documentation updates or stub updates needed. Tests added. I didn't add a regression test specifically for #955 (the nested exception) since I don't think we should ever really care much in code whether an exception arises from another one; it's more of a cosmetic issue for those seeing the exception.

Refactor PrefixMap and PrefixList validation for clarity

---

docs/source/traits_api_reference/ctraits.rst
docs/source/traits_user_manual/index.rst
docs/source/traits_user_manual/internals.rst

This PR represents a start on documenting Traits internals. It only covers a very small part of the story so far, but I hope it'll expand over time. We're ultimately aiming for the internals documentation to be coherent and complete. For this PR, it's obviously incomplete but I hope it's not incoherent (and if reviewers find it incoherent, it should be fixed).
It also adds the ``_instance_traits`` and ``_class_traits`` introspection methods to the API documentation, so that they can be referred to.

Start documenting traits internals

---

traits/ctraits.c
traits/tests/test_has_traits.py

When doing `obj.attr_name` on a `HasTraits` object `obj`, if `attr_name` doesn't appear in either the class or instance dictionaries, Traits next tries to look it up as a regular Python attribute (via the `PyObject_GenericGetAttr` C-API function). If that lookup fails with an exception of any kind, the exception is swallowed and Traits then moves on to try the general prefix-trait machinery. In effect, there's a bare `except` here, but at C level.
This PR modifies the behaviour to replace the bare `except` with an `except AttributeError`, so that exceptions other than `AttributeError` will no longer be swallowed.
The fix itself is easy. Writing a regression test that worked was ... more interesting.
This fixes one case of #946.

Fix exception swallowing by Trait attribute access

---

traits/ctraits.c
traits/tests/test_ctraits.py

When an attribute is looked up on a `CTrait` object, `None` is returned on failed lookup, regardless of the actual exception that was raised. This means that (for example) logic errors from a `CTrait` method will be silenced.
This PR changes the behaviour to only return `None` if the attribute lookup raises `AttributeError`, and to propagate any other exception.
This is the `cTrait` analog to #959 for `CHasTraits`.
Along with #959, this fixes #946.

Fix another case of exception swallowing from PyObject_GenericGetAttr

---

traits/ctrait.py

A simple consistency fix: now that we've dropped compatibility with Python 2, it's safe to copy our collections using the copy method in all cases.
No behaviour changes.

Drive-by simplification

---

traits/tests/test_ctraits.py

There's a test in `test_ctraits` that uses `unittest.mock`, but `unittest.mock` isn't imported. That means that running `unittest` on just this module fails with a `NameError` (see test output below). This PR fixes that missing import.
Note that the CI runs weren't affected, presumably because some other module earlier in the test run does an `import unittest.mock`.
I haven't yet checked that there aren't other cases of this in the codebase. I'll do that.
```
(traits) mirzakhani:traits mdickinson$ python -m unittest traits.tests.test_ctraits
......E..............
ERROR: test_default_initialization (traits.tests.test_ctraits.TestCTrait)
----------------------------------------------------------------------
Traceback …
```

Fix a missing import that prevented a test module from being run standalone

---

traits/tests/test_enum.py
traits/trait_base.py
traits/trait_types.py

This PR:
- refactors some of the `BaseEnum` and `Enum` code to remove duplication and unify semantics
- changes the signature of `BaseEnum` to make the `values` argument explicit
- replaces the `is_collection` check (which is now a bit misleadingly named) with the essentially equivalent `isinstance(..., collections.abc.Iterable)` check
- removes `is_collection`, which is now unused
- removes `EnumTypes`, which we no longer need
- for static enumerations, **changes** the `name` attribute from the empty string to ``None``
- **fixes** a regression with the behaviour of ``Enum(3)``: in Traits 6.0 this is legal, while on master it raises
- adds some extra tests to improve coverage
- adds tests for the documented attributes
- reworks the ``BaseEnum`` and ``Enum`` docstrings, and ensures that …

BaseEnum and Enum fixes and cleanup

---

examples/tutorials/traits_4.0/trait_types/new_types.py
examples/tutorials/traits_4.0/trait_types/trait_types.py

**Checklist**
~~- [ ] Tests~~
~~- [ ] Update API reference (`docs/source/traits_api_reference`)~~
~~- [ ] Update type annotation hints in `traits-stubs`~~
PR fixes #486 
Make the `OddInt` example class inherit from `BaseInt` which does not have a fast validator.

Fix example class OddInt

---

docs/source/traits_user_manual/defining.rst

PR documents the `Map`, `PrefixMap` and `PrefixList` in the user manual.
Fixes #954 
**Checklist**
~~- [ ] Tests~~
~~- [ ] Update API reference (`docs/source/traits_api_reference`)~~
~~- [ ] Update type annotation hints in `traits-stubs`~~

Add documentation for Map, PrefixMap and PrefixList to the User manual

---

docs/source/traits_api_reference/trait_handlers.rst
traits/tests/test_deprecated_handlers.py
traits/trait_handlers.py

**Checklist**
~~- [ ] Update User manual (`docs/source/traits_user_manual`)~~ No changes
~~- [ ] Update type annotation hints in `traits-stubs`~~ Remains the same
PR deprecates `TraitMap`, `TraitPrefixMap` and `TraitPrefixList`
Fixes #941

Deprecate TraitMap, TraitPrefixMap and TraitPrefixList

---

traits/tests/test_trait_set_object.py
traits/trait_set_object.py

This PR targets #922 (not master!):
- Adds a few tests that fail with this [commit](https://github.com/enthought/traits/pull/922/commits/e67b08529315775d1ea99d6fcebc198be00a02fe) of #922 
- Add a few tests to extend test coverage (i.e. they are already passing with the said commit)
- Address a few minor docstring issues
Running the tests against this [commit](https://github.com/enthought/traits/pull/922/commits/e67b08529315775d1ea99d6fcebc198be00a02fe) results in the following failures:
<details>
<summary> python -m unittest discover -t . traits </summary>
```
ERROR: test_add_iterable (traits.tests.test_trait_set_object.TestTraitSet)
----------------------------------------------------------------------
Traceback (most …
```

Address issues on PR #922 for TraitSet

---

traits/tests/test_trait_list_object.py

PR Fixes #982 , catch `TypeError` and raise `TraitError` on validation fail for `int_validator`
**Checklist**
~~- [ ] Update API reference (`docs/source/traits_api_reference`)~~
~~- [ ] Update User manual (`docs/source/traits_user_manual`)~~
~~- [ ] Update type annotation hints in `traits-stubs`~~

Catch TypeError in int_validator & raise TraitError

---

traits/tests/test_trait_set_object.py
traits/trait_set_object.py

This PR is targeting #922 
It simplifies attribute checks in the `TraitSetObject.notifier` method to what we actually need, and add a test that would fail if we did not check `if self.name_items is None`.

Simplify checks in TraitSetObject.notifier and add the related test

---

docs/source/traits_api_reference/trait_type.rst
traits/ctrait.py
traits/ctraits.c
traits/has_traits.py
traits/tests/test_copyable_trait_names.py
traits/tests/test_ctraits.py
traits/tests/test_regression.py
traits/trait_type.py
traits/traits.py

**Checklist**
- ~~[ ] Update API reference (`docs/source/traits_api_reference`)~~ Not public API
- ~~[ ] Update User manual (`docs/source/traits_user_manual`)~~ Not public API
- ~~[ ] Update type annotation hints in `traits-stubs`~~ No trait API change
Fixes #825 
PR introduces two new functions in `ctraits.c` , a `_set_property` and a `_get_property` and removes the `_trait_property` function. The new functions together achieve the same purpose as `_trait_property`.  Ref : https://github.com/enthought/traits/pull/837#issuecomment-600073352
The `_get_property` only returns a tuple of 3 arguments (fget, fset and validate), not sure if there are any merits in returning the argument counts for the `fget`, `fset` and `validate` callables also.
It also introduces a new `property` method in …

Split ctraits property api to _set_property and _get_property

---

traits/tests/test_dict.py
traits/tests/test_trait_dict_object.py
traits/trait_dict_object.py

This PR is targeting #913
This PR adds a few tests that fail with commit b18feec652a6d949af8333ea49a8ee6631146b21 of #913, and then proceeds to fix them.
The tests that failed:
<details>
<summary> python -m unittest discover -t . -v traits</summary>
```
FAIL: test_validate_key (traits.tests.test_dict.TestDict)
----------------------------------------------------------------------
File "/Users/kchoi/Work/ETS/traits/traits/tests/test_dict.py", line 133, in test_validate_key
foo.mapping[1] = 1
AssertionError: TraitError not raised
FAIL: test_validate_value (traits.tests.test_dict.TestDict) …
```

Address issues in #913 for introducing TraitDict and reworking TraitDictObject

---

traits/has_traits.py
traits/tests/test_has_traits.py

The `HasTraits.__deepcopy__` method is unnecessarily complicated: Python's `deepcopy` machinery already takes care of memoization, so there's no need to do it ourselves.
I've added a test to double check that things are still memoized properly.
**Checklist**

Fix overcomplicated __deepcopy__ implementation

---

traits/tests/test_trait_list_object.py
traits/trait_list_object.py

Here's the promised `TraitList` / `TraitListObject` refactor that I suggested last week. The main change is that whole-list validation is gone from `TraitList`: instead of the previous `validator` argument, `TraitList` now takes an `item_validator` argument, and that argument is used to validate any items being added in a list operation.
In meetings last week we discussed the possibility of a subclass of `TraitList` implementing the length-constraint logic. It turned out to be simplest to merge that proposed subclass with `TraitListObject`.  So this PR doesn't introduce any new classes: we still have `TraitList` and `TraitListObject`, but length validation has moved into `TraitListObject`.
Rationale for the change:
- It's not obvious that the `validator` API will extend naturally to …

Refactor TraitList / TraitListObject

---

traits/tests/test_trait_list_object.py
traits/trait_list_object.py

Fix incorrect event index for slice with stop < start

---

traits/tests/test_trait_set_object.py
traits/trait_set_object.py

This PR refactors the new `TraitSet` implementation to try and match the refactored `TraitList` implementation. 
Some unresolved comments in PR #922 have been addressed here.

Refactor trait set container

---

traits/tests/test_dict.py
traits/trait_dict_object.py

This PR is targeting #913 (TraitDictObject) and is similar to #990 which was targeting TraitSetObject.
This PR simplifies the checks in `TraitDictObject.notifier` and add a test that would fail if we did not check for `if self.name_items is None`.

Simplify checks in TraitDictObject.notifier and add the related test

---

traits/tests/test_trait_dict_list_set_event.py
traits/trait_dict_object.py
traits/trait_list_object.py
traits/trait_set_object.py

Added `__repr__` to class TraitListEvent, TraitDictEvent and TraitSetEvent. 
The string returned by `__repr__` indicates only the modifications on the object (to keep it small), not the full modified object.
Fixes #993.

__repr__ implementation for TraitListEvent, TraitDictEvent and TraitSetEvent

---

traits/tests/test_trait_list_object.py
traits/trait_list_object.py

Motivated by #997: this PR changes the `index` used in `TraitList.notify` calls to be a plain int, where that makes sense (i.e., everywhere except `__delitem__` and `__setitem__` operations with an _extended_ slice). I believe that this makes the events more consistent with each other, easier to explain, and easier to interpret for consumers.
As a bonus, there's no longer a difference between the `index`, `added` and `removed` in the `TraitList.notify` calls and the attributes of the corresponding `TraitListEvent`s.
One other minor change (semi-bugfix) in this PR: `sort` and `reverse` no longer notify for zero-element lists. These were the only cases that could produce a `TraitListEvent` where both `removed` and `added` were empty.

Make TraitList notify index a plain int where possible

---

traits/trait_list_object.py

This is a simple documentation-only PR that adds missing "Raises" sections for `TraitList.__delitem__` and `TraitListObject.__delitem__`. Both of those operations can raise `IndexError`. We have that information for the `__setitem__` docstrings, but not for `__delitem__`.

Fix missing 'Raises' section in TraitList.__delitem__ 

---

traits/testing/optional_dependencies.py
traits/tests/test_enum.py

Related to #965 
Adds a GUI test for the `create_editor` method for the `Enum` trait.
**Checklist**
~~- [ ] Update API reference (`docs/source/traits_api_reference`)~~
~~- [ ] Update User manual (`docs/source/traits_user_manual`)~~
~~- [ ] Update type annotation hints in `traits-stubs`~~

Add a GUI test for Enum.create_editor

---

docs/source/traits_user_manual/notification.rst

This PR adds a Dos and Donts' subsection in the `Trait Notification` section and add one example.
**Checklist**
- ~Tests~

DOC: Add dos and donts for writing change handlers

---

docs/source/traits_user_manual/advanced.rst
docs/source/traits_user_manual/notification.rst
examples/tutorials/doc_examples/examples/post_init_notification.py

The behaviour seen in #94 wasn't obvious to me. This PR expands the documentation to clarify:
(1) instantiation with a specific value will be considered for firing a trait change event, if there is a change handler
(2) `post_init` can be used for use cases when firing change handler for values provided to `__init__` is not desirable. This `post_init` was never mentioned in the user documentation, but often mentioned in issues when this comes up.
**Checklist**
- ~Tests~

DOC: Clarify when default initializer is called and when handlers are registered

---

traits/has_traits.py

This PR makes pure cosmetic changes to the warning message when the attribute name uses one of the reserved prefixes.
Previously it looks like this:
```
The attribute named 'trait_view' of class HasDynamicViews uses one of the reserved prefixes: trait,_trait. Consider renaming it.
```
Now it looks like this:
```
The attribute named 'trait_view' of class HasDynamicViews uses one of the reserved prefixes: 'trait', '_trait'. Consider renaming it.
```
There are more line diffs than necessary because of flake8: the line got too long.

Minor cosmetic changes to the warning message for reserved prefixes

---

traits/tests/test_trait_list_object.py
traits/tests/test_traits.py
traits/trait_list_object.py

Closes #972 
This PR changes the behaviour of TraitListObject. From now on it will notify even if the underlying list doesn't change (it didn't before). An exception - notification is still suppressed if there is no structural change.
For example, given a class:
```
>>> class Foo(HasTraits):
...     bar = List([1, 2, 3])
...     @on_trait_change('bar[]')
...     def report_bar_change(self, obj, name, old, new):
...         print(f"Some bar values changed: {old} --> {new}")
...
>>> f = Foo()
```
all of the following will notify listeners:
```
>>> f.bar[0] = 1
Some bar values changed: [1] --> [1]
>>> f.bar[:2] = [1, 2]
Some bar values changed: [1, 2] --> [1, 2]
```
The exception - no structural change:
```
>>> f.bar[3:] = []
>>>
```
**Checklist**
- ~[ ] Update API reference …

Make TraitListObject notify even if list values stay the same

---

traits/editor_factories.py
traits/tests/test_editor_factories.py

Removes caching of editor factories. Fixes #1030 and helps with https://github.com/enthought/traitsui/issues/790
**Checklist**

Remove caching of editor factories

---

docs/source/traits_api_reference/traits.rst
docs/source/traits_user_manual/defining.rst
examples/tutorials/doc_examples/examples/event.py
traits/tests/test_traits.py
traits/traits.py

Closes #728 
Color, RBGColor and Font traits are now deprecated with the recommendation to use `traitsui` instead. 
Updated API references and docstrings. Description and Default Value sections seemed out of date (and sphinx was complaining) so I just removed them. Removed all references to these traits from User manual as well.
Also updated one example that uses `RGBColor`.
**Checklist**

Deprecate Color, RBGColor and Font traits

---

docs/source/traits_user_manual/defining.rst
traits/has_traits.py
traits/tests/test_warnings.py

Closes #705 
A few existing attribute/methods with the prefix "trait" have been advertised by traits for subclasses to redefine/override.
This PR whitelists those names and updates the documentation.  
**Checklist**

Whitelist names with trait prefix as being safe for subclass to redefine

---

traits/tests/test_traits.py

This PR wraps tests requiring traitsui with `requires_traitsui` so they can be skipped when traitsui is not importable.
The CI environment has traitsui (and a lot of other optional dependencies) so the tests are still run. However `traits` actually has no dependencies and test suite should still be expected to pass when one installs `traits` in a clean Python environment (e.g. `pip install traits` from PyPI).
**Checklist**

Allow tests requiring traitsui to be skipped when an environment does not have traitsui

---

traits/tests/test_trait_dict_list_set_event.py
traits/trait_set_object.py

This PR makes the `TraitSetEvent` arguments keyword-only, for safety, and for consistency with `TraitDictEvent`. I'd like to do the same for `TraitListEvent` too, but that needs changes in TraitsUI. See #1035 
**Checklist**

Make TraitSetEvent arguments keyword-only

---

traits/tests/test_trait_list_object.py
traits/tests/test_trait_set_object.py
traits/trait_base.py
traits/trait_dict_object.py
traits/trait_list_object.py
traits/trait_set_object.py

Closes #1014 
`accept_anything` validator was defined for each `TraitList`, `TraitSet` and `TraitDict` separately. This PR moves the validator to `trait_base` to be used by all three and renames it to `validate_everything` which hopefully is a more informative name of what the function does.
**Checklist**

Move accept_anything validator to trait_base and rename

---

docs/source/traits_api_reference/traits.rst
traits/base_trait_handler.py
traits/ctrait.py
traits/has_traits.py
traits/traits.py
traits/util/resource.py

Closes #1005 
Fixes following rendering issues:
- Unsupported `Usage` section in `HasRequiredTraits`. Replaced by `Examples` section.
- Incorrect placement of `Description` - removed section headers and moved descriptions to under the "one-line description"
- `Property` was referred to as `autoclass` when it should be `autofunction`
**Checklist**
- ~[ ] Tests~

Fix documentation rendering issues

---

.travis.yml
appveyor.yml
etstool.py

This PR drops CI runs on Python 3.5. We no longer build eggs for Python 3.5, so that makes it difficult to run against the latest version of Pyface and TraitsUI using our current EDM- and buildsystem-based infrastructure.
See also #687.

Don't run CI on Python 3.5

---

traits/api.py
traits/tests/test_view_elements.py

Closes #932
This import is no longer needed as `traitsui` takes care of registering `ViewElement` as `AbstractViewElement` subclass, so it is removed. Also added a test to verify that `ViewElement` imported from `traitsui.api` is indeed a subclass of `AbstractViewElement`.
**Checklist**

Remove conditional traitsui import (ViewElement)

---

traits/trait_types.py

Closes #965 
This PR:
- changes `value = self` (`self` is an instance of `Enum`) to `value = self.values`. Both works, but the latter is more correct.
- Workaround https://github.com/enthought/traitsui/issues/782 when the allowed values are defined statically and when the `format_func` is provided. I'd not recommend putting `format_func` in the definition of trait, but it needs to stay for backward compatibility.
For example, this:
```
from traits.api import HasTraits, Enum
class Foo(HasTraits):
true_or_false = Enum([0, 1], format_func=lambda v: str(bool(v)).upper())
foo = Foo()
foo.configure_traits()
```
We'd expect to see the dropdown contains `"TRUE"` and  `"FALSE"`.  https://github.com/enthought/traitsui/issues/782 causes us to see `"0"` and `"1"` instead.
**Checklist**
- Tests
Not …

Maint: Fix correctness in Enum default traitsui editor

---

etstool.py

This follows from https://github.com/enthought/traits/pull/1034#issuecomment-621071275
* add `configobj` dependency for running demos using `tutor.py` to `etstool.py`
* remove remaining references and code branches related to Python 3.5 from `etstool.py`
**Checklist**
- ~[ ] Tests~

Add configobj dependency and remove remaining 3.5 references in etstool.py

---

docs/source/traits_user_manual/internals.rst
docs/source/traits_user_manual/notification.rst

Added documentation about the new Trait container classes to the internals section, plus some minor clarifications to the section on TraitEvents
Fixes #997.
**Checklist**
- ~[ ] Tests~

Trait container documentation

---

traits-stubs/traits-stubs/trait_types.pyi
traits-stubs/traits_stubs_tests/examples/Instance.py

The fix was to use generic *args and **kwargs after the first argument since the `__init__` method potentially shuffles them.  This broke `Date`, `Datetime` and `Time`, so specific `__init__` methods were added for them.
Fixes #1062.
**Checklist**

Fix the Instance init stub

---

traits/observers/_trait_event_notifier.py
traits/observers/tests/test_trait_event_notifier.py

Related to #977
This PR removes the requirement on the event argument name for the dispatch callable, as the requirement unnecessarily forbids the use of other generic dispatch-like functions, such as `concurrent.futures.Executor.submit(callable, *args, **kwargs)`. With this, it will be possible to use something like `Executor.submit` as the dispatch callable. 
(Whether to expose this flexibility to the user API is a separate discussion though.)
**Checklist**

Maint: Avoid calling observe's dispatch with named arguments

---

traits/observers/_exceptions.py
traits/observers/_i_notifier.py
traits/observers/_i_observer.py
traits/observers/_observe.py
traits/observers/_testing.py
traits/observers/tests/test_observe.py

Closes #1021
Item 6 of #977
This PR adds a function `add_or_remove_notifiers` for adding/removing notifiers for a given `ObserverGraph`.
- The `IObserver` interface is expanded to support `add_or_remove_notifiers`.
- Added a `INotifier` interface to support `add_or_remove_notifiers`. The `TraitEventNotifier` (in #1000) and `ObserverChangeNotifier` (in #1007) implement the `INotifier` interface introduced here. It is possible that this PR might need changes per review outcome of #1000 and #1007. The formal registration can happen later... or not happen at all.
**Checklist**
- ~Update API reference (`docs/source/traits_api_reference`)~: Things here are still private. Module names are preceded with an underscore.
- ~Update User manual (`docs/source/traits_user_manual`)~: Things here are …

Implement logic for adding/removing notifiers for a given ObserverGraph

---

docs/source/traits_api_reference/index.rst
docs/source/traits_api_reference/traits.observers.rst
traits/observers/_trait_change_event.py
traits/observers/events.py
traits/observers/tests/test_trait_change_event.py

This PR adds the `TraitChangeEvent` object for wrapping CTrait change events.
This event object will be given to the user's handler registered using `observe`.
This event object will also be used by the `NamedTraitObserver` in #1069, the "FilteredTraitObserver" for observing traits using a filter, and the (internal-use-only) observer for `trait_added` events.
**Checklist**
- ~Update User manual (`docs/source/traits_user_manual`)~ WIP in #1060 

Add TraitChangeEvent object for wrapping CTrait change

---

.travis.yml

This PR attempts to add Slack notifications (to the internal #ets-bots channel on Enthought's Slack) for Travis CI builds. This is mostly to support the cron jobs, so that we get alerted when a cron job fails.
Right now I'm just making this PR to see if it works. Once it's working, we'll want to fine-tune the notification settings (e.g., only notify on failure).
For the record, here are my notes on the steps I took:
```
Notes on integrating Travis with Slack
- Get the Travis CLI:  https://github.com/travis-ci/travis.rb#readme
- With ruby (and "gem") installed, do: "gem install travis"
- For a MacPorts install, I needed to:
- $ port install ruby27
- $ sudo ln -s /opt/local/bin/ruby2.7 /usr/local/bin
- $ sudo ln -s /opt/local/bin/gem2.7 /usr/local/bin
- $ sudo gem2.7 install travis    
- $ …
```

Add notifications for the #ets-bots Slack channel

---

traits/observers/expression.py
traits/observers/tests/test_expression.py

This PR makes `trait("a") | trait("b")` to be considered as NOT equivalent to `trait("b") | trait("a")`.  Strictly speaking, this is true because the given change handler will be registered to "a" first and then to "b" when `observe(handler, trait("a") | trait("b"))` is called. When `observe(handler, trait("b") | trait("a"))` is called, the change handler will be registered to "b" first and then to "a".
The `__eq__` is not used by the internal machinery, it is there to help users learning the expression. Internal observe machinery uses `_as_graphs` instead. So if the users want to see these two being considered equal, we can change this back without affecting anything.
**Checklist**
- ~Update User manual (`docs/source/traits_user_manual`)~: Does not exist yet.
- ~Update type annotation …

Differentiate order in Expression equality function

---

traits/observers/_named_trait_observer.py
traits/observers/tests/test_named_trait_observer.py

`ListItemObserver` does not prevent its attributes to be mutated (see #1071). For consistency, this PR relaxes the protection on `NamedTraitObserver` too. 
These attributes should not be mutated despite this change.
**Checklist**

Relax immutability in NamedTraitObserver for consistency

---

docs/source/traits_api_reference/traits.observers.rst
traits/observers/expression.py
traits/observers/parsing.py
traits/observers/tests/test_expression.py
traits/observers/tests/test_parsing.py

This PR works towards finishing item 4 in #977
> Text parser for parsing traits domain specific language to an instance of Expression
- Add conversion logic from a syntax tree to an instance of Expression
- Add `parse` function to convert text to Expression. This function is exposed in the public API
- Add `trait` as a method on `Expression` for extending an expression for observing a trait with a given name.
- Add `trait` top-level function for creating an expression for a given trait name (this just wraps the method on an empty expression).
Note that parsing `"+metadata"` and `"items"` currently raise NotImplementedError as the observers required for these two are still being reviewed. This PR therefore adds some placeholders for them.
**Checklist**
- ~Update User manual …

Implement parsing logic for converting text to Expression

---

docs/source/traits_api_reference/index.rst
docs/source/traits_api_reference/traits.observers.rst
traits/observers/_dict_change_event.py
traits/observers/_dict_item_observer.py
traits/observers/events.py
traits/observers/tests/test_dict_change_event.py
traits/observers/tests/test_dict_item_observer.py
traits/trait_dict_object.py

This PR implements item 9 of #977:
> Implement the logic for attaching notifiers when the items of a dict changes
- Add `DictChangeEvent`. Note that the definition of `DictChangeEvent` is not the same as `TraitDict.notify`, see discussion in #1031
- Add `DictItemObserver` that implements the interface of `IObserver`:
- return the object for adding/removing notifiers. In this case, the observable is simply an instance of TraitDict.
- yield the **values** of the dict for the next observer(s) in an ObserverGraph. **values** is an obvious choice here because mutables should not be used as keys in dict.
- Like `ListItemObserver`, no filtering is done while yielding values for the next observer(s) on the observer graph. If the values are incompatible with the next observers, the latter can …

Implement DictItemObserver for observing mutations to a dict

---

docs/source/traits_api_reference/index.rst
docs/source/traits_api_reference/traits.observers.rst
traits/observers/_set_change_event.py
traits/observers/_set_item_observer.py
traits/observers/events.py
traits/observers/tests/test_set_change_event.py
traits/observers/tests/test_set_item_observer.py
traits/trait_set_object.py

This PR implements item 10 of #977 for observing mutations on a set (strictly speaking, TraitSet).
- Add `SetChangeEvent` to represent mutations on a set
- Implement `IObserver` interface to
- Return the TraitSet object for adding/removing notifiers
- Yield the content of the set for the next observer(s) in the observer graph.
- Define the notifier such that `SetChangeEvent` will be created for the user's change handler.
- Implement logic for maintaining downstream observers
- Implement the interface of `IObservable` for `TraitSet`. With that, any subclass of `TraitSet` can be used with SetItemObserver.
**Checklist**

Implement SetItemObserver for observing mutations on a set 

---

traits/ctrait.py
traits/trait_dict_object.py
traits/trait_list_object.py
traits/trait_set_object.py

This PR makes sure all observables are (virtual) subclasses of `IObservable`.
So far nothing does the subclassing check e.g. `issubclass` or `isinstance`, so the registeration is arguably unused.
This is more about explicitly declaring a type as observable and making observables more discoverable (e.g. one can do a global search on `IObservable`. Unfortunately registering virtual subclass does not allow reverse lookup from the `ABC`...)
Drive-by import and naming changes to make things more consistent.
**Checklist**
- ~Tests~

Register all observables to IObservable

---

docs/source/traits_user_manual/advanced.rst

Starting from a very basic HasTraits subclass without any notifications, defaults defined via a method with name `_name_default` are called when the trait is accessed the first time. This allows the method to be use as a lazy initializer post-instantiation, and allow the default to depend on post-instantiation attributes.  This works until the model grows and notifications are added, because the mental model of traits actually considers the default to have been defined pre-instantiation, and default initializers end up getting called early when notifications need to fire.
A couple of examples can be seen in https://github.com/enthought/traits/issues/94 and https://github.com/enthought/traits/issues/709
This PR attempts to clarify this concept in the user manual.
**Checklist**
- ~Tests~
- …

DOC: Clarify when dynamic default values are considered to have existed

---

traits/observers/_observe.py

This PR expands the docstring of `add_or_remove_notifiers` to aid code discovery.
While `add_or_remove_notifiers` was added together with the interface of `IObserver`, for anyone reading the code outside the context of a PR, they will likely start from the top-level `observe` function to this `add_or_remove_notifiers`. It is not clear the function should be understood with the interface defined in `IObserver`.
While the docstring of `ObserverGraph` does briefly mention `IObserver`, `ObserverGraph` does not actually enforce its nodes to be `IObserver` at all. `add_or_remove_notifiers` does.
**Checklist**
~Tests~
~Update API reference (`docs/source/traits_api_reference`)~
~Update User manual (`docs/source/traits_user_manual`)~
~Update type annotation hints in `traits-stubs`~

Doc: Add mention of IObserver in add_or_remove_notifiers docstring

---

traits/observers/_filtered_trait_observer.py
traits/observers/_testing.py
traits/observers/tests/test_filtered_trait_observer.py

This PR implements item 12 for #977
- Add `FilteredTraitObserver` for observing traits using a filter function `callable(name, trait) -> boolean`.  This observer can then be used for filtering traits with a metadata, and more.
- A lot of the logic is very similar to `NamedTraitObserver`, except no errors will be raised if the filter finds no traits to be observed.
- Support for `trait_added` is missing here. It can be added once #1077 is merged and the usage is going to be ~identical~ similar to that in `NamedTraitObserver`.
**Checklist**
- ~Update API reference (`docs/source/traits_api_reference`)~ Users will not instantiate this observer directly.

Add an observer for observing traits using an arbitrary filter

---

traits/observers/expression.py
traits/observers/tests/test_expression.py

Closes #1076
This PR moves the construction of a single observer to a separate expression object.
`Expression` remains to be user-facing: it aims at providing a user-friendly interface, e.g. instance methods for composing expressions.
The internal expression objects are hidden from the user, and all implement a common interface called `_IExpression`. (That interface is rather basic at the moment). Despite the name, `Expression` is not an instance of `_IExpression`.  An alternative naming suggestion (for either renaming `Expression` or renaming `_IExpression` is very welcome).
**Checklist**

Wrap single observer to a separate expression

---

traits/observers/_named_trait_observer.py
traits/observers/_testing.py
traits/observers/_trait_added_observer.py
traits/observers/tests/test_named_trait_observer.py
traits/observers/tests/test_trait_added_observer.py

This PR implements item 11 of #977
- Add an `TraitAddedObserver` for supporting other observers that need to handle `trait_added`. - Use `TraitAddedObserver` in `NamedTraitObserver`.
**Checklist**
- ~Update API reference (`docs/source/traits_api_reference`)~ this observer is for internal use.

Add trait_added support for observing a named trait

---

traits/ctraits.c

This PR is a minor refactor changing the format for `PyObject_CallMethod` calls with no arguments from `"()"` to `NULL`.
Fixes #1099.
May conflict with #1086. I'll hold off merging this until after #1086 is merged.

Use NULL for zero-argument PyObject_CallMethod format

---

traits/tests/test_union.py
traits/trait_types.py

If I try to create a trait type like this:
```
Union(Dict(), "none")
```
I get an error message:
```
Union trait declaration expects a trait type or an instance of trait type or None, but got none instead
```
This PR improves the error message so that it reads:
```
Union trait declaration expects a trait type or an instance of trait type or None, but got 'none' instead
```
which is much clearer about what went wrong.
**Checklist**

Improve error message when representing incompatible value for Union

---

traits/observers/_metadata_filter.py
traits/observers/tests/test_metadata_filter.py

This PR targets this item in #977:
> Implement the logic for observing traits whose metadata fulfils a given criterion (depends on 12). This will support the metadata method in Expression, and the use of "+" in the text parser.
- Add `MetadataFilter` to be used as the `filter` callable in `FilteredTraitObserver`.   Users typically create these observers via text `"+metadata"`, and a new `filter` instance will be created.  The reason why we need a separate class for this filter is for supporting equality check on the filter when the user requests an existing observer to be removed. 
- See `TestWithFilteredTraitObserver` for how this is used with an instance of `HasTraits`.
**Checklist**
- ~Update User manual …

Add MetadataFilter for observing traits using metadata

---

traits-stubs/traits-stubs/trait_types.pyi
traits/tests/test_none.py
traits/trait_types.py

Closes #1105
**Checklist**
- ~Tests~
- ~Update User manual (`docs/source/traits_user_manual`)~: never mentioned

Rename NoneTrait to make it private

---

.travis.yml
appveyor.yml

This PR removes the codecov triggers from the Travis CI configuration.
Fixes #919

Don't trigger codecov reports

---

traits/observers/_filtered_trait_observer.py
traits/observers/tests/test_filtered_trait_observer.py

Part of #977
This PR adds `trait_added` support for the observer that observes traits using a generic filter (`FilteredTraitObserver`).
When a new trait is added via `HasTraits.add_trait`, provided that the `trait_added` event is fired, the new trait will be tested against the filter defined in `FilteredTraitObserver`, and if the trait is a match, notifiers will be attached to the new trait. 
**Checklist**

Add trait_added support for FilteredTraitObserver

---

traits/observers/_dict_change_event.py
traits/observers/_list_change_event.py
traits/observers/_set_change_event.py
traits/observers/_trait_change_event.py
traits/observers/tests/test_dict_change_event.py
traits/observers/tests/test_list_change_event.py
traits/observers/tests/test_list_item_observer.py
traits/observers/tests/test_set_change_event.py

Closes #1084
This PR makes `object` exist in all 4 event objects in observe. 
**Checklist**

Rename the changed object as 'object' in all events

---

traits/observers/api.py
traits/observers/expression.py
traits/observers/parsing.py
traits/observers/tests/test_expression.py
traits/observers/tests/test_parsing.py

Part of #977
This PR:
- Add `metadata` in the expression for observing traits with a given metadata name
- Implement the parsing of `"+metadata_name"` in the mini-language
- Add `match` in the expression for wrapping the FilteredTraitObserver, useful for use cases not supported by the other expressions.
**Checklist**
- Update User manual (`docs/source/traits_user_manual`): Will be in a separate PR

Expose expressions for observing traits with filters

---

docs/source/traits_user_manual/defining.rst
traits/tests/test_none.py
traits/tests/test_union.py
traits/trait_types.py

Closes #1104 
This PR makes `Union` use `default_value` instead of `default` for defining static default. This name is consistent with other trait types.
Unfortunately `Either` uses `default` instead and is an anomaly. In order to help downstream code migrates, an error is raised if a metadata named `'default'` is found.
Expanded user manual to mention the different naming used for static defaults in `Either` and `Union`. 
**Checklist**
- ~Update type annotation hints in `traits-stubs`~: default_value is not mentioned there

Fix Union to use default_value for setting static default

---

traits/has_traits.py
traits/tests/test_expression.py

Closes #1096 
PR adds another check for `setattr_original_value` flag when copying an inherited trait and setting a new default value.
**Checklist**

Check setattr_original_value before setting inherited trait default

---

traits/observers/_has_traits_helpers.py
traits/observers/tests/test_has_traits_helpers.py

Part of #977
This PR adds a warning when item changes in a list/dict/set are observed, if the list/dict/set is a top-level container and the `comparison_mode` is set to equality.
*Motivation*: When a new container is assigned to a trait where the comparison mode is set to equality (the default), no change event will be fired if the new container compared equally to the old one. Consequently, mutation and extended trait change cannot be observed on the new container, and the old container (if it is still around) will continue to emit notifications. This would be an unexpected behaviour.
Changing the default comparison mode is going to break code. So instead, the warning instructs users to fix this by setting `comparison_mode` to identity, like this:
```
class Foo(HasTraits):
container = …
```

Add warning while observing container items with comparison mode set to equality

---

traits/has_traits.py
traits/observers/expression.py
traits/observers/observe.py
traits/observers/parsing.py
traits/observers/tests/test_expression.py

There is already an `Expression` in `trait_types`.  #977 introduces another expression object for the use of `observe`.  The name clash is unnecessary. It causes confusion in discussion and requires extra work for Sphinx to find the correct cross-reference.
This PR renames all `Expression` in `traits.observers` to `ObserverExpression` before this gets released. 
**Checklist**
- ~Tests~

Rename (observers) Expression to ObserverExpression

---

docs/source/conf.py
docs/source/index.rst
docs/source/traits_user_manual/index.rst

This PR:
- replaces the hard-coded "Traits 6" that appears in various places in the documentation and its configuration with an autogenerated "major.minor" version (e.g., Traits 6.1)
- Adds the version to the top-level documentation page (it used to read "Traits Documentation"; it now reads "Traits 6.1 Documentation)
Closes #908.

DOC: Autogenerate the version used in documentation

---

traits/observation/expression.py
traits/observation/parsing.py
traits/observation/tests/test_expression.py
traits/observation/tests/test_parsing.py

This PR renames `join_` to `join` in `traits.observation.expression`.
It was initially named `join_` for no good reasons.
**Checklist**

Rename observer expression join function

---

.travis.yml
appveyor.yml
etstool.py

We should be testing against PyQt 5 instead of PyQt 4 (which is long past its EOL).

Test against PyQt5 instead of PyQt4

---

traits/has_traits.py
traits/util/_traitsui_helpers.py
traits/util/tests/test_traitsui_helpers.py
traits/util/traitsui_helpers.py

Closes #1106
If the user has TraitsUI 6.x and Traits 6.1, using TraitsUI functionality could result in an error like this:
```
File "/Users/kchoi/Work/ETS/traits/traits/has_traits.py", line 1677, in edit_traits
args,
File "/Users/kchoi/.edm/envs/resist-py36/lib/python3.6/site-packages/traitsui/view.py", line 446, in ui
ui.ui(parent, kind)
File "/Users/kchoi/.edm/envs/resist-py36/lib/python3.6/site-packages/traitsui/ui.py", line 244, in ui
self.rebuild(self, parent)
... (excerpted)
File "/Users/kchoi/Work/ETS/traits/traits/has_traits.py", line 1667, in edit_traits
view = self.trait_view(view)
File "/Users/kchoi/Work/ETS/traits/traits/has_traits.py", line 1727, in trait_view
self,
File "/Users/kchoi/Work/ETS/traits/traits/has_traits.py", line 1772, in _trait_view
method = getattr(handler, …
```

Provide a nicer error message when upgrading Traits with an older version of TraitsUI

---

traits/observation/expression.py
traits/observation/observe.py
traits/observation/parsing.py

As promised, this PR removes import aliases just for adding a preceding underscore.
**Checklist**
- ~Tests~

Nit: Remove aliases just for preceding underscores

---

traits/observation/_named_trait_observer.py
traits/observation/_observer_graph.py

All except two of classes in `traits.observation` use class names for `__hash__`.
This PR fixes the other two so they are consistent with others.
**Checklist**
- ~Tests~

Use class name in hash consistently

---

traits/observation/_trait_change_event.py
traits/observation/tests/test_trait_change_event.py

This PR removes the "<>" around the representation of `TraitChangeEvent`, to be consistent with other events.
There are drive-by changes to the formatting, for consistencies as well.
**Checklist**

Fix TraitChangeEvent repr format to be consistent with others

---

docs/source/conf.py

This PR adds the intersphinx extension so that we can refer to TraitsUI docs from the Traits docs where necessary. (I've also added Pyface, in case we need it at some point.)

Add intersphinx extension

---

docs/source/traits_user_manual/notification.rst

This PR reformats the table of example `ObserverExpression` so that they are rendered as code and can be copy-and-pasted directly.
Now they look like this:
**Checklist**
- ~Tests~
-  ~Update API reference (`docs/source/traits_api_reference`)~

DOC: Reformat expression examples so they can be copied-and-pasted as code

---

docs/source/traits_user_manual/listening.rst

Sphinx >= 3.0 complains about the multiple method definitions for `on_trait_change` and `anytrait_changed`. This PR suppresses those warnings.
Closes #1045

Suppress Sphinx warnings about duplicate method definitions

---

traits/tests/test_prefix_map.py
traits/trait_types.py

Closes #1130
This PR applies the validation+transformation early when a PrefixMap is instantiated, such that a valid static default value can be used.
**Checklist**

Validate and transform static default value for PrefixMap

---

docs/source/traits_user_manual/notification.rst

Thanks to @rahulporuri pointing this out in https://github.com/enthought/traits/pull/1060#discussion_r429174328, this PR fixes a wrong attribute name in the mini-language semantics.
**Checklist**
- ~Tests~

Fix attribute name in documentation

---

traits/tests/test_prefix_list.py
traits/trait_types.py

Closes #1138 
This PR makes sure `PrefixList.__init__` raises `TraitError` for what is exactly a validation error.
I'd have wanted to use `value_for` like in #1139, however that change did not turn out to be as trivial as I hoped, so I will have to dig a bit to see if something else is wrong.
**Checklist**

Raise TraitError for validation error in PrefixList.__init__

---

docs/source/traits_user_manual/defining.rst
traits-stubs/traits-stubs/trait_types.pyi
traits-stubs/traits_stubs_tests/examples/PrefixList.py
traits/tests/test_prefix_list.py
traits/trait_types.py

Closes #1137 
This forces `PrefixList` to have ~at least~ exactly one positional argument, and that legal values must be provided via a list or a tuple.
**Checklist**

Restrict PrefixList signature to accept a list or tuple of values

---

traits/tests/test_trait_dict_list_set_event.py

This PR replaces some calls to the `__repr__` method in tests with calls to the `repr` function instead.

Tests: call the repr function rather than the corresponding dunder method

---

CHANGES.rst
traits/ctraits.c

#1088 introduced a reference leak; this PR fixes that leak.
No regression test, because (a) it's hard to test for, and (b) this is picked up by running Python-level reference leak tests.
Fixes #1145.

Add missing Py_DECREF to fix a reference leak

---

CHANGES.rst
docs/source/traits_user_manual/defining.rst

This PR expands the user manual to mention some points worth noting while migrating from Either to Union.
(There is already a section on migration from on_trait_change to observe. We could possibly have a separate index page for Traits 6.1 that references both sections.)
**Checklist**
- Tests

DOC: Expand user manual on migration from Either to Union

---

traits/observation/exception_handling.py
traits/observation/tests/test_exception_handling.py
traits/observation/tests/test_trait_event_notifier.py

Closes #1154
This PR removes the logging configuration on traits logger in `observe`, which was supposed to be consistent with `on_trait_change` (the logging configuration is still done there) ~, and adds warnings for any unexpected exceptions.~
This marks a slight difference from on_trait_change:
When a change handler using `on_trait_change` raises an exception, the error is always logged to the console regardless of whether the application wants it or not.
When a change handler using `observe` raises an exception, it is logged, and will depend on the last resort handler to get it to the console.
EDITED: ~a warning will be emitted to the console, forcing developers to deal with them.~
EDITED: ~the error is only visible if something else configures the logger on traits, or if a custom …

Remove logging configuration for logging observe's change handler failure

---

traits/trait_handlers.py

This PR simply removes an unused logger from the `trait_handler` module.

Remove an unused logger

---

CHANGES.rst

Following #1153, this PR adds a note in the changelog that links to the Either-to-Union migration guide.

Add changelog link to the Either-to-Union migration guide

---

traits/tests/test_trait_get_set.py

Remove an unused `catch_logs` context manager factory. Now that we've dropped Python 2 support, we can use unittest's `assertLogs` for checking log messages.

Remove unused catch_logs contextmanager

---

traits/editor_factories.py
traits/tests/test_editor_factories.py

We're now requiring TraitsUI >= 7.0, so we can reasonably assume that `DatetimeEditor` exists. This PR removes workarounds for an unavailable `DatetimeEditor`.
Also does a drive-by cleanup of the unused `cache_name` variable in several tests.

Assume DatetimeEditor exists

---

CHANGES.rst
traits/__init__.py
traits/tests/test_listeners.py
traits/trait_notifiers.py

The default handler for trait notification exceptions configures logging, adding a `StreamHandler` to the top-level `traits` logger. This has the (desirable) effect of ensuring that, in the absence of any logging configuration, errors occurring in listeners are visible to the user, printed on stderr.
However, it also makes it awkward for an application to configure logging, and particularly for an application to _suppress_ the traits log messages if it wants to: that application would have to mess with the handler that Traits has already set up.
Instead, we should follow the usual logging best practices and allow the application to configure logging, restricting Traits to simply emitting log messages.
This PR removes the log configuration.
We also remove the top-level `NullHandler`. That …

Don't configure logging for trait notification handler exceptions

---

CHANGES.rst
traits/tests/test_trait_list_object.py
traits/trait_list_object.py

Fix an error message that was mistakenly using the built-in type `object` in place of the `HasTraits` object that the trait lives on.
Fixes #1170

Fix error message for a list length violation

---

traits/util/tests/test_weakidddict.py

This PR changes one test to use an absolute import rather than a relative one. This makes the corresponding test script executable standalone.
This is the only test that needs fixing this way. The relative import was preventing a refleak test run from completing normally (with `python -E -Wd -m test -R: --testdir ../traits/util/tests`).

Use absolute import in a test

---

CHANGES.rst
traits/tests/test_trait_list_object.py
traits/trait_list_object.py

This PR is a workaround to make sure that we don't raise something that looks like a length error on an unconstrained list.
This isn't the solution I'd prefer - it's the least invasive solution that unblocks the Traits 6.1.0 release.
For Traits 6.2.0, I'd like to rework so that the `minlen` and `maxlen` attributes of a `List` trait are `None` for an unconstrained list, and have the rest of the code interpret that properly. But that feels like too invasive and risky a fix this close to the release, so for 6.1.0 we get this workaround instead.
Fixes #1171

Ensure length check on unconstrained list always passes

---

CHANGES.rst
docs/source/traits_user_manual/defining.rst

Fixes #1177.
EDIT: also replaces occurrences of `sys.maxint` (which doesn't exist in Python 3) with `sys.maxsize`.

Fix truncated List description in documentation

---

CHANGES.rst
setup.py

This PR makes some minor updates and changes to the setup script. The most notable change is to the short description.
- Adjust classifiers: remove "Programming Language :: C", since it's misleading, and add "Programming Language :: Python :: 3.9" for future-proofing purposes
- Update the description to "Observable typed attributes ..."; this captures the (to my mind) key benefit of Traits.
- Change the download url to point to PyPI (this seems to be fairly standard practice)
- Add explicit project URLs pointing to issues, documentation and source. (The homepage also points to docs, but that's not obvious to someone browsing PyPI, so I think it's worth having the explicit documentation link.)
- Remove the maintainer and maintainer email fields; these are redundant with the existing author …

Tweaks and fixes to setup keywords

---

CHANGES.rst
traits/ctraits.c
traits/tests/test_map.py
traits/trait_converters.py
traits/trait_types.py

This PR fixes the issue where shadow trait notifications were not being issued on the first change of the primary trait.
The essence of the change is to always call `post_setattr` (if it exists) when accessing a default value. That needs changes in two places:
- in `trait_getattr`, where there's already a block that calls `post_setattr`, but the call is skipped for mapped traits, for no clear reason; we re-enable that call
- in `trait_setattr`, where `default_value_for` is called if necessary to retrieve the old value for notifications. Here we add code to (1) poke the computed default value back onto the dictionary, just like we do already in `trait_getattr`, and (2) call `post_setattr`
There's scope for refactoring to remove the duplication, but I'd rather do that refactoring …

Fix shadow trait notifications

---

CHANGES.rst
traits/tests/test_map.py
traits/tests/test_prefix_map.py
traits/trait_types.py

This PR changes the default default value for `Map` and `PrefixMap`: if no default value is given, then it uses the first element of the provided mapping, in normal Python iteration order.
In Python 3.6 this gives something reasonable and deterministic. In Python 3.5, we'll get an arbitrary element (and possibly a different one from run to run).
~Still need to check the documentation to see what needs changing there.~
Closes #1187 
**Checklist**

Change the 'default default' for Map and PrefixMap

---

CHANGES.rst
docs/source/traits_user_manual/defining.rst
setup.py
traits/ctraits.c
traits/tests/test_map.py
traits/tests/test_prefix_map.py
traits/trait_converters.py
traits/trait_types.py

Backport #1178, #1185, #1188 and #1189 to the release branch.
- #1178: Fix truncated list description in user guide
- #1185: Minor updates to setup keywords
- #1188: Fix shadow trait notifications
- #1189: Change the default default value for Map and PrefixMap

Backport more PRs from master to 6.1 release branch

---

CHANGES.rst
setup.py

Bump the version in preparation for release.
Ideally, this should not be merged until after all other PRs targeted at the 6.1.0 release have been merged. (Currently, that's just #1167, but there may be more PRs as a result of testing.)

Bump version for 6.1.0 release

---

docs/source/traits_user_manual/notification.rst

This PR expands the user manual to highlight another difference in `observe`: `dispatch` is used while distinguishing observers.
Context: I was looking at TraitsUI code, and noticed that existing calls to remove change handlers do not specify `dispatch="ui"`. It works because `on_trait_change` does not differentiate it. 
https://github.com/enthought/traitsui/blob/f919dbd2044bcbff7280e5580286e93caa8a153a/traitsui/qt4/list_editor.py#L138-L140
https://github.com/enthought/traitsui/blob/f919dbd2044bcbff7280e5580286e93caa8a153a/traitsui/qt4/list_editor.py#L149-L151
`observe` does, and the call with `remove=True` in the above example will need to include `dispatch="ui"` when it is switched to use `observe`
**Checklist**
- ~Tests~
- …

DOC: Mention dispatch is used for distinguishing observers

---

traits-stubs/LICENSE.txt
traits-stubs/MANIFEST.in
traits-stubs/README.rst
traits-stubs/setup.py
traits-stubs/traits-stubs/api.pyi

This PR backports #1197 to the release branch.
I'm planning to tag the resulting commit as `traits-stubs/6.1.0` and then release to PyPI.

Prepare traits-stubs for distribution (backport of #1197)

---

docs/source/traits_user_manual/notification.rst

This PR fixes a sentence in the documentation that mentions a nonexisting feature of `metadata`: the feature was removed in https://github.com/enthought/traits/pull/1095 to defer adding a feature we are not sure if it'd be needed.
**Checklist**
- ~Tests~

DOC/FIX: User manual mentioning a nonexisting feature in metadata filter

---

traits/observation/tests/test_observe.py

This PR adds a small test to check a few different types of change handlers can be used with `observe`.
Not sure why would any of the builtin get used with `observe` in real projects, but they do work now (as long as they accept one argument). From the experience of manual testing, being able to use `print` (or just any callable accepting one positional argument) with `observe` was quite handy. If it should stop being supported, at least the test will alert us.
Note: `repr` could not be used with `on_trait_change`.
**Checklist**

Add a test to check for good change handler types

---

docs/source/traits_user_manual/notification.rst

This PR fixes a few spelling mistakes in the user manual.
This does not intend to be an exhaustive fix.
(Kit are never very good at speling and gramar.)
**Checklist**
- ~Tests~

Fix some spelling and grammar on the user manual

---

README.rst

This is a tiny PR to harmonize the descriptions of the Traits library: it makes the description in the README match the short description in the `setup.py` script (which now also matches the GitHub repository description).
And yes, the whole README likely needs rewriting. One step at a time.

Fix description in README to match the one in the setup script

---

setup.py
traits/util/tests/test_trait_documenter.py

This PR remove some backwards compatibility code needed for ancient Sphinx versions.
Just to be safe, we also add a minimum Sphinx version in the test requirements.
Closes #1054.

Require Sphinx 2.1 for trait_documenter tests

---

docs/source/traits_user_manual/notification.rst
examples/tutorials/doc_examples/examples/observe_different_events.py
traits/observation/tests/test_has_traits_helpers.py
traits/tests/test_observe.py

Minor cleanup PR: replace uses of magic numbers for comparison modes with the corresponding `ComparisonMode` elements. (The numbers should eventually become just an implementation detail; we  want to encourage all traits users to use the `ComparisonMode` constants instead.)

Use ComparisonMode constants instead of magic numbers

---

traits/tests/test_interface_checker.py

We're mutating global state at import time in a test module, potentially leading to test interactions and test dependence on import order. This PR fixes the test to mutate at `setUp` time instead, and undo that mutation at `tearDown`.
Fixes #1220.

Don't mutate global state at import time in a test module

---

traits/testing/optional_dependencies.py

Fix a comment that mistakenly refers to traits.api, when it means traitsui.api.

Fix typo in optional_dependencies

---

traits-stubs/traits-stubs/has_traits.pyi
traits/has_traits.py

The `HasTraits` machinery needs function and method checks at various points, mostly to look for magic-named methods like `_mytrait_changed` and `_myevent_fired`.
Those checks are currently performed inconsistently, and for methods written in Cython also rely on a rather fragile mechanism for recognising the method. (That mechanism also fails for C extensions other than Cython extensions.)
This PR:
- makes the checks consistent: they all now rely on the `_is_unbound_method_type` helper function.
- uses `inspect.ismethoddescriptor` as a better way to catch something that behaves like an unbound method without relying on Cython-specific details
- cleans up unused related functions and constants

Refactor and simplify HasTraits method checks

---

docs/source/traits_user_manual/notification.rst
examples/tutorials/doc_examples/examples/observe_different_events.py
traits/observation/tests/test_has_traits_helpers.py
traits/tests/test_observe.py

After #1165, we no longer need to set `comparison_mode` to `identity` in container traits in order to silence warnings and support `observe`. This PR cleans up such definitions in tests and documentation.
**Checklist**

Cleanup comparison mode setting in tests and documentation

---

traits/tests/test_interfaces.py

This PR enhances some of the tests in `test_interfaces.py`:
- Fix test classes that claim to provide given interfaces, to actually provide that interface. (Without this, these tests fail if `CHECK_INTERFACES` is set to `2`.)
- Add some additional `assertIsInstance` checks to verify that instances of those test classes do pass the appropriate `isinstance` checks.

Strengthen interface checks in tests

---

.travis.yml
appveyor.yml

A trivial build PR to cache pip eggs.
I plan to run the CI build twice: if this worked, the second run should be appreciably faster than that first.

Speed up CI builds by caching the pip directory

---

README.rst

This PR:
- updates incorrect and inconsistent capitalization in the README
- adds a PyPI link for Sphinx
- adds a PyPI link for the Enthought Sphinx Theme (the previous link was to GitHub)

Update PyPI links and capitalization in README.rst

---

traits/tests/test_python_properties.py

This PR adds tests that check that normal Python properties in a `HasTraits` subclass behave in the expected manner.
These tests should ~prevent~ deter any unthinking attempt to remove these lines in `HasTraits`, which are there to support exactly this use-case: https://github.com/enthought/traits/blob/e16be1004bde938f969895b543cae01317fd2756/traits/has_traits.py#L479-L480
I've verified that the new tests fail if the two lines above are removed.
Closes #947.

Add test for regular Python properties in HasTraits classes

---

traits/util/tests/test_trait_documenter.py
traits/util/trait_documenter.py

This PR fixes the trait_documenter Sphinx extension so that it no longer fails on regular Python properties. It does this by modifying the `can_document_member` function so that it doesn't recognise generic traits. This makes sense, since a generic trait is deliberately designed to behave like a standard Python `object` attribute.
Mostly fixes #1238, but independently of this fix, it would be good to fix the trait-documenter to be less fragile, so that if it fails in some other situation in the future then that failure doesn't prevent the Sphinx build from completing.
EDIT: See #1247 for the "make trait-documenter less fragile" fix.

Fix trait_documenter for properties

---

docs/source/traits_user_manual/advanced.rst
docs/source/traits_user_manual/appendix.rst
examples/tutorials/doc_examples/examples/cached_prop.py
traits/has_traits.py
traits/tests/test_has_traits.py
traits/tests/test_property_notifications.py
traits/traits.py

In very much the same way `depends_on` uses `on_trait_change` in `Property`, this PR extends the use of `observe` to the `Property` trait using a new metadata named "observe" ~(name to be confirmed)~.
This PR also marks the use of "depends_on" as an "older" API.
Objectives:
- Resolve issues such as #447, #481 (or #709, which is similar)
- Reduce traits's own dependency on `on_trait_change`
**Checklist**

Add 'observe' keyword to the Property trait for observation

---

traits/util/tests/test_trait_documenter.py
traits/util/trait_documenter.py

This PR modifies trait_documenter to be less fragile when a trait definition can't be found.
Previously, a failure to find a trait definition would raise `StopIteration` and cause the entire documentation build to be aborted. With the changes in this PR, that failure will instead issue a warning, and the documentation build will continue.
The PR also includes some refactoring to make it easier to add unit tests: in particular, the `_get_trait_definition` method, which depended on hard-to-set-up objects like the `ClassLevelDocumenter`, has had its logic moved into a standalone function `trait_definition` that doesn't need to know anything about Sphinx.
This PR fixes the aspect of #1238 that a failed definition retrieval breaks the doc build. It doesn't fix the underlying issue that caused …

Fix trait_documenter to be less fragile

---

CHANGES.rst
setup.py

This PR updates the release/6.1.x branch for continued development towards a possible 6.1.2 bugfix release (which may never happen).
- Bump micro version number
- Fill in the correct release date for Traits 6.1.1

Bump version for 6.1.2; also fix 6.1.1 release date

---

README.rst

We're no longer running automated coverage, so the coverage statistic on the badge in the README is out of date. This PR removes it.

Remove coverage badge from README

---

setup.cfg
traits/api.py

added a per-file-ignores line to https://github.com/enthought/traits/blob/master/setup.cfg to be able remove `# noqa: F401` comments in https://github.com/enthought/traits/blob/master/traits/api.py

adding per-file-ignores to clean up noqa:F401 comments in api

---

etstool.py
setup.py

For reasons which i'm not sure of, sphinx 2.3.1 works but sphinx 3.2.0 which is the latest version available on pypi doesn't work.
fixes #1273 
**Checklist**
~- [ ] Tests~

FIX : Pin sphinx version to get docs to build

---

docs/source/traits_user_manual/advanced.rst
docs/source/traits_user_manual/custom.rst
examples/tutorials/doc_examples/examples/trait_subclass.py
examples/tutorials/traits_4.0/getstate_setstate/getstate.py
examples/tutorials/traits_4.0/trait_types/new_types.py
examples/tutorials/traits_4.0/trait_types/trait_types.py
traits/adaptation/adapter.py
traits/etsconfig/tests/test_etsconfig.py
traits/has_traits.py
traits/testing/unittest_tools.py
traits/tests/test_copy_traits.py
traits/tests/test_extended_notifiers.py
traits/tests/test_pickle_validated_dict.py
traits/tests/test_python_properties.py
traits/tests/test_union.py
traits/trait_handlers.py
traits/trait_numeric.py
traits/trait_types.py
traits/traits_listener.py

This PR cleans up the usage of `super` - I noticed that the codebase was a mix of `super(ClassName, self)` and `super()` calls, which I have updated to use `super()` in this PR.
The update was done using regex-search and replace. The regex string that works for `super(ClassName, self)` is `(super)+\(+(\w+)(,)+\s(self)+\)+`, learnt/debugged using https://regex101.com/.
After making changed using the automated search/replace, the changes were manually checked using `git add -p *`.
Finally, I manually searched the codebase for uses of `super` which the regex didn't match e.g. `super( ClassName , self )` or `super(ClassName,self)` - which were manually updated.
**Checklist**

Update super usage

---

traits/tests/test_copy_traits.py

Discovered when working on #1280 
Not sure why it exists. Didn't check git log/blame. 
**Checklist**

Remove commented out dead code

---

traits/util/trait_documenter.py

Ref : https://docs.python.org/3.6/library/logging.html#logging.Logger.warning
**Checklist**

logger.warn is deprecated, use logger.warning instead

---

docs/Makefile

Fixes the path to the Enthought logo used the by `make docset` command in `/docs`.

FIX: Path to Enthought logo when building docset

---

traits/observation/_has_traits_helpers.py
traits/observation/tests/test_has_traits_helpers.py

Fixes #1277
`Undefined`, `Uninitialized`, `None` are sentinel values we should not observe. They are skipped in on_trait_change using identity check as well. This avoids errors like the one in #1277.
**Checklist**

Fix containment check relying on ability to check for equality

---

traits-stubs/traits_stubs_tests/test_all.py
traits-stubs/traits_stubs_tests/util.py
traits/testing/optional_dependencies.py

This PR makes `mypy` an optional dependency for the `mypy` tests.
This might seem like an odd thing to do, but some test runners (notably `pytest`) will discover those tests. If `pytest` is run on a clean Python environment with a freshly-installed Traits, then it should gracefully skip the tests for which the dependencies aren't installed. We already do this for Sphinx, numpy, and various other packages.
Related: #1288

Make mypy an optional dependency

---

traits/tests/test_regression.py

Use assertCountEqual rather than assertEqual so as not to depend on order. Should fix #1282.

Fix an order-dependency bug in the test_subclasses_weakref regression test

---

traits/trait_types.py

The docstring of the `Str` trait type has a minor typo.
**Checklist**

Fix a typo in Str docstring

---

etstool.py

This PR adds a new `shell` click command - which when run activates the development environment for traits. The usual command line options are available to choose the environment name and the runtime version of the development environment. Underneath the hood, the click command just uses the `edm shell` command with the appropriate environment name, which is why the docstring for the click command is _almost_ the same as that of `edm shell`.
**Checklist**

Add a shell click command

---

traits-stubs/traits_stubs_tests/test_all.py
traits/testing/optional_dependencies.py
traits/tests/test_historical_unpickling.py
traits/tests/test_version.py

Three of the tests require the `pkg_resources` package to be present in the environment. It usually will be (since it's a part of the `setuptools` distribution), but if it's not, then the tests should be skipped rather than causing the test run to fail.
This PR fixes that, adding `pkg_resources` to the existing optional imports machinery in `traits.testing`.
Part of the motivation here is to be able to create a test run that validates that Traits doesn't have any "accidental" dependencies. See #1299.
Closes #1300.

Fix tests that require pkg_resources

---

.github/workflows/run-traits-tests.yml
.travis.yml
appveyor.yml

Python 3.9 has been released, so we should update the GitHub Actions continuous integration to run on 3.9 proper instead of on a pre-release version.
This PR updates the GitHub Actions test script accordingly.
xref: https://github.com/actions/setup-python/issues/148
We should also update the Travis and Appveyor scripts, but I'm having difficulty finding evidence that the systems support Python 3.9 yet. I'll give it a try once the GitHub Actions change has completed.
---
EDIT: Updated to also drop Python 3.5 support for both Appveyor and Travis CI.

Use released Python 3.9 instead of prerelease

---

README.rst
setup.py
traits-stubs/setup.py

Python 3.5 is past end-of-life, we no longer get package builds for EDM on Python 3.5, and we have no information that anyone is using Traits on Python 3.5. This PR officially removes Python 3.5 support for Traits.
Closes #831.

Drop support for Python 3.5

---

traits/tests/test_directory.py
traits/tests/test_file.py
traits/tests/test_map.py
traits/tests/test_prefix_map.py
traits/trait_types.py

This is a follow-on PR to #1312. Strictly speaking, it probably shouldn't be merged until after #1312 (but the CI won't care, because we already removed the 3.5 runs).
This PR:
- Removes some test code that needed to worry about dictionary ordering.
- Removes conditional imports of `os.fspath`: with Python >= 3.6, we can assume the presence of `os.fspath`.
**Checklist**

Remove Python 3.5 compatibility code

---

traits/testing/tests/test_unittest_tools.py
traits/testing/unittest_tools.py

This PR :
- Deprecated the `UnittestTools._catch_warnings` method
- Replaces existing uses of this method with `warnings.catch_warnings`
- Adds a docstring to `UnittestTools._catch_warning` (but note that `_catch_warnings` doesn't appear in the current documentation build, so the docstring is only useful for code readers or those exploring at the prompt)
Closes #1270 
**Checklist**

CLN: Deprecate UnittestTools._catch_warnings

---

.github/workflows/run-core-traits-tests.yml

This PR adds a GitHub Actions workflow for running the test suite with none of the optional dependencies present in the environment.
The idea is to catch bugs where either a test or (worse) a piece of the core Traits functionality accidentally depends on another package being present.
It seems unnecessary to runs these tests on all possible combinations of Python version and platform (which would give 12 jobs), but given that there's potential for dependency bugs to be both platform-specific and Python-version specific, we compromise by testing only on Windows and Linux, and only on Python 3.6 and Python 3.9, for a total of four jobs.
Closes #1299.

BLD: Add CI runner for core test suite (no optional dependencies)

---

traits/tests/test_trait_dict_object.py
traits/trait_dict_object.py

This PR fixes `|=` operations on `TraitDict`. In Python 3.9, those operations mutate the dictionary, but without corresponding support in `TraitDict`, that mutation will not emit a notification. This PR adds the missing notification.
Fixes #1016.
**Checklist**
- ~[ ] Update API reference (`docs/source/traits_api_reference`)~ No update needed
- ~[ ] Update User manual (`docs/source/traits_user_manual`)~ No update needed
- ~[ ] Update type annotation hints in `traits-stubs`~ No stubs exist for TraitDict and friends

FIX: Add |= support to TraitDict for Python >= 3.9

---

traits/tests/test_trait_dict_object.py
traits/trait_dict_object.py

This PR modifies the `TraitDict.update` method so that notifications are not issues when updating with an empty argument. This is similar to the behaviour of extending a list or updating a set with an empty argument.
The PR also adds a test for the `TraitDict.clear` method, to verify that it doesn't notify when clearing an already-empty dictionary.
Fixes #1307
**Checklist**

FIX: Don't notify on empty 'update's of Dict traits

---

docs/source/traits_user_manual/testing.rst

There was a typo in the example of how to use mocking that meant that the example didn't work as written. This PR fixes that.
Thanks @xamcost for bringing this to my attention.

Fix typo in mocking example

---

README.rst
etstool.py
setup.py

We require Sphinx >= 2.1. That requirement used to be encoded in the `setup.py`, but was removed in #1276.
Related: #1216.

Correct the minimum Sphinx version in README

---

traits/tests/test_get_traits.py

This PR adds tests that should pass on master. It demonstrates the current behaviour of `HasTraits.traits`.
Related to #1329
**Checklist**

Add tests for HasTraits.traits and _items traits

---

traits/observation/_has_traits_helpers.py
traits/tests/test_observe.py

This PR fixes a new bug introduced by #1165 (hence not released).
The first commit adds a test that reveals the issue, it fails with the following error:
```
File "/Users/kchoi/Work/ETS/traits/traits/tests/test_observe.py", line 675, in test_observe_event_with_undefined_name_suffix_items
app.trait_property_changed("i_am_undefined_with_items", 1, 2)
File "/Users/kchoi/Work/ETS/traits/traits/observation/_trait_event_notifier.py", line 119, in __call__
if self.prevent_event(event):
File "/Users/kchoi/Work/ETS/traits/traits/observation/_has_traits_helpers.py", line 132, in ctrait_prevent_event
ctrait = event.object.traits()[event.name]
KeyError: 'i_am_undefined_with_items'
```
The second commit fixes it.
**Checklist**
- ~Update API reference …

Fix KeyError from observe trying to filter events for trait named "*_items"

---

traits/adaptation/adaptation_offer.py
traits/adaptation/tests/test_adaptation_offer.py
traits/observation/_dict_change_event.py
traits/observation/_list_change_event.py
traits/observation/_set_change_event.py
traits/tests/test_trait_dict_object.py
traits/tests/test_trait_list_object.py
traits/tests/test_trait_set_object.py
traits/trait_dict_object.py
traits/trait_list_object.py
traits/trait_set_object.py
traits/util/tests/test_weakidddict.py
traits/util/weakiddict.py

fixes #1333 
This PR simply updates repr implementations in a few classes to use `self.__class__.__name__` rather than hardcoding the class name, and adds simple tests.  Namely, it updates the `TraitListEvent`, `TraitDictEvent`, and `TraitSetEvent` classes as well as the `AdaptationOffer` and `WeakIDDict` classes.
**Checklist**

Don't hard-code class names in __repr__ implementations

---

traits/observation/parsing.py

related to #1316 
**Checklist**
~- [ ] Tests~
This is an alternate approach to what is done in #1343.  Here rather than moving the parsing logic into the decorator, we simply cache the results of parsing so that if many instantiations are done, we don't need to re-parse the expression every time.  This solution gives a comparable decrease in case (2) time to instantaite, without increasing the time it takes to construct the class (1). See benchmark reports with `n=100000` below:
On master:
<details>
Given a subclass of HasTraits with a trait defined, e.g. name = Str(),
compare having a method with no …

Add lru_cache on parse for observe to speed up instantiation time

---

traits/observation/parsing.py

This PR simply uses a module level constant for the cache size as discussed here: https://github.com/enthought/traits/pull/1344#discussion_r521265702
It was originally meant to be in #1344, but I forgot to push the change before merging. 
**Checklist**
~- [ ] Tests~

Replace lru cache size magic number of 128 with a module level constant

---

traits/tests/test_trait_dict_list_set_event.py
traits/tests/test_trait_list_object.py
traits/trait_list_object.py

fixes #1035 
This PR makes the `TraitListEvent` arguments keyword only to match what is done for `TraitSetEvent` and `TraitDictEvent`, and for safety.
**Checklist**

Make TraitListEvent arguments keyword only

---

etstool.py

(For @achabotl)
Currently, `python -m etstool --help` works for getting help but `python -m etstool -h` does not. This breaks user expectations when working with a command line application. This PR makes `-h` work as expected.
**Checklist**

Support -h for getting help

---

traits/tests/test_traits.py

Motivated by #1258, this PR adds a few tests that exercise the scenario where migration from TraitMap to Map is hard.
The difficulty here is that `Trait` can take a number of things, and when a mapping and a callable are given to it, it makes the trait a mapped trait because there is a mapping.  And when the callable is used for validation (and transformation), both the key value and the mapped value are the same. But when the callable fails, the mapping is used and the key value is not the same as the mapped value.
If we migrate to Map, then the key value would be different from the mapped value. If we use Union to combine them together, then the mapped trait is gone.  
I still haven't figured out a migration solution for this scenario that does not involve just reimplement a TraitType …

Add test for the use case of Trait with mapping and callable

---

docs/source/traits_user_manual/advanced.rst

fixes #149 
This PR simply makes a 1 line addition to the documentation by resetting `currentmodule` to `traits.has_traits` instead of `traits.adaptation.api` so that the Property Factory Function is correctly documented.  After building the docs this is what you now see:
Excuse the highlighted "Property" in the screenshot.
**Checklist**
~- [ ] Tests~

reset currentmodule to traits.has_traits so Property Factory function is correctly documented

---

traits/tests/test_enum.py

Fixes #1266 
In this PR I first simply broke `pyface.toolkit.toolkit_object` up into `from pyface.toolkit import toolkit_object` and then called `toolkit_object`.  This fixed the `AttributeError: module 'pyface' has no attribute 'toolkit'` error mentioned in the issue.  Currently `GUITestAssistant` is only implemented on Qt, so I also added an `is_qt` check before trying to get `GUITestAssistant` via `toolkit_object`, and I also skipped the test that needs `qt` if `qt` is not available.  This may or may not be the right solution as the code is basically coped over from https://github.com/enthought/traitsui/blob/770e94346e06dc70909f125ba7237edce90872da/traitsui/tests/_tools.py#L50-L54
The tests no longer failed if pyface is installed but traitsui is not, or if traitsui/pyface are installed …

Prevent test_enum failures if traitsui or GUI toolkit are not installed

---

traits/tests/test_map.py
traits/tests/test_prefix_list.py
traits/tests/test_prefix_map.py
traits/trait_types.py

fixes #1191
`PrefixList`, previously if no default was given and the given list of strings was empty, had a default default value of `None`.  In this PR, if the given list to `PrefixList` is empty an error is raised.  Likewise, if `Map` or `PrefixMap` are fed empty dicts a `ValueError` is also raised.  Previously, for `Map` and `PrefixMap` if an empty dictionary was given, it would raise a `StopIteration` exception.  In this PR that is changed to a `ValueError` with a message explicitly specifying that the dictionary of valid values can not be empty.  
Additionally, this PR adds trivial tests to ensure errors are raised when empty lists/dictionaries are used. 
**Checklist**
~- [ ] Update User manual …

Add errors for PrefixList, PrefixMap, and Map with empty lists/dicts

---

traits/adaptation/adaptation_manager.py

Fix poorly-formatted docstrings for the `AdaptationManager` class:
- Move `Parameters` section for `adapts` to the bottom
- Add missing `Returns` and `Raises` sections
- Some wordsmithing on the existing words.
Screenshot of the fixed docs:
Closes #1354.

Fix NumpyDoc errors in AdaptationManager docstrings

---

traits/examples/introduction/index.rst

Closes #1357
This PR moves the `__init__.py` file to an `index.rst`. Now the description is visible on etsdemo:
This does NOT _close_ #1356 (one can still import `traits.examples.introduction` for it is still considered a 'namespace package'?).
**Checklist**
- ~Tests~

Fix Traits introduction description not being visible on etsdemo

---

traits/observation/tests/test_named_trait_observer.py

Motivation: Earlier when I was looking into what we could do to optimize `observe` (e.g. #1343), I noticed that the code path for supporting `trait_added` takes a significant amount of time (relatively speaking), and I started wondering if that observer graph for supported `trait_added` is actually redundant when the trait is present (which is the majority of use case).
This PR simply adds the tests to demonstrate and preserve the existing behaviour when an existing trait is removed and added back, whether the handlers are still around.
This block of code is relevant:
https://github.com/enthought/traits/blob/d0b94558ed8f7005057228c9a01c52a59c6f4544/traits/has_traits.py#L2816-L2818
If a trait had been defined as a class trait, trait_added will not be fired even if the instance trait was …

Add tests to show observer handlers are gone when a simple trait is removed

---

setup.py

This PR fixes a minor `setup.py` nit: `package_data` should be listed by package. So now that `traits.examples` is a package, we can adjust the `package_data` listing accordingly.
xref: #1348, #1358
**Checklist**

Fix minor package_data nit

---

traits-stubs/traits-stubs/has_traits.pyi
traits/has_traits.py

The only internal use of `EmptyList` disappeared at some point between Traits 4.3.0 and Traits 4.4.0.
This change will break external code that's doing `from traits.has_traits import EmptyList`. I'm finding it hard to care much about that.
**Checklist**

Remove an unused module-level constant

---

docs/source/traits_api_reference/trait_handlers.rst
traits/tests/test_deprecated_handlers.py
traits/tests/test_traits.py
traits/trait_handlers.py

The deprecation of `TraitMap` in #974 was premature: Traits itself still uses `TraitMap` internally (through `Trait`), and the difficulty of removing that usage demonstrates that there isn't an obvious replacement.
This PR undoes the deprecation of `TraitMap`. Note that `TraitPrefixList` and `TraitPrefixMap` remain deprecated: those classes are not used internally, and `PrefixList` and `PrefixMap` should provide a reasonable replacement.
See also #1336.
Closes #1258.
**Checklist**

Revert the deprecation of TraitMap

---

traits/trait_type.py

Fix #1377
The singleton instance name is the same as its type name. This is confusing sphinx, and is causing the following error with Sphinx 3.4.1 while building doc:
```
reading sources... [ 51%] traits_api_reference/trait_type                                                                                                                                                                                 
Exception occurred:
File "/Users/kchoi/Work/ETS/py39-venv/traits-env/lib/python3.9/site-packages/sphinx/util/typing.py", line 160, in _restify_py37
return ':obj:`%s.%s`' % (cls.__module__, cls.__name__)
AttributeError: 'NoDefaultSpecified' object has no attribute '__name__'
The full traceback has been saved in /var/folders/_6/bw6pnpwx3pzfvhd20ffcpyjm0000gn/T/sphinx-err-4260mu_5.log, if you …
```

Fix documentation build due to class being name shadowed by a singleton

---

CHANGES.rst
docs/source/traits_api_reference/trait_type.rst
traits-stubs/traits-stubs/trait_type.pyi
traits/tests/test_readonly.py
traits/trait_type.py

Closes #1379
This PR fixes the issue by making `NoDefaultSpecified` and `no_default_specified` private by naming convention. We believe they are not (actively) used outside of traits. If they are indeed used, this PR will at least make those breakage fail in a more obvious and trackable fashion, and we will get to know why and how it gets used internally, and then we can fix the breakage accordingly.
Note that if I change this line to `if True:`:
https://github.com/enthought/traits/blob/a68bc501fddef1a7091c8748ed61d4793007a658/traits/trait_type.py#L297
I would get a test failure for the test that involves TraitsUI:
```
ERROR: test_create_editor (traits.tests.test_enum.TestGui) …
```

Make NoDefaultSpecified and no_default_specified private

---

traits/has_traits.py

This is a minor fix for a typo in the MetaHasTraits docstring. It references a "create_traits_meta_dict" function that does not seem to exist.

Fix typo in MetaHasTraits docstring

---

traits/util/trait_documenter.py

This PR removes a potentially confusing warning about TraitsDoc, which is now ancient history.
From some historical code diving and searching, TraitsDoc here refers to a single file `traitsdoc.py` which contained a Sphinx extension; the file was typically copied directly into the `docs` directory of projects that needed it. `traits.util.trait_documenter` is the official "right way" to do this.
**Checklist**

Remove warning about TraitsDoc

---

CHANGES.rst
docs/source/traits_api_reference/trait_type.rst
docs/source/traits_user_manual/custom.rst
traits-stubs/traits-stubs/trait_type.pyi
traits/api.py
traits/tests/test_trait_types.py
traits/trait_type.py

We recently made `NoDefaultSpecified` private. In hindsight, that was the wrong thing to do, for various reasons:
- It's part of the signature of `TraitType` (specifically, it's the default value for the optional `default_value` argument), which is a public class that's designed to be subclassed. As such, it's a little odd to have the value private.
- The rationale for making it private was questionable: the immediate need was to fix the doc build, but the doc build only needed to be fixed by fixing the documentation itself.
- There's an open issue (#1041) to do the opposite: make `NoDefaultSpecified` truly public by adding it to `traits.api`.
This PR:
- Reverts PRs #1380 and #1378 (but keeps the extra test added in #1380)
- Renames the `NoDefaultSpecified` _class_, to avoid confusion …

Make NoDefaultSpecified public

---

docs/source/traits_user_manual/defining.rst

This PR adds a note to the documentation about usage of the `api` modules, and makes it clear that recommended practice is to import from those modules rather than directly from the modules that define the given functionality.
Closes #1213.
**Checklist**

Add note about *.api usage

---

traits/tests/test_enum.py
traits/trait_types.py

This PR fixes validation of dynamic enumerations inside a Tuple. Previously, for the dynamic case of an `Enum`, no validation was performed until trait-set time. This PR changes the logic so that the validate method (which the Tuple uses for its item validation) is no longer None.
This fixes the issue originally reported in #1385. There are other issues identified in the #1385 comments that still need to be fixed (or have new issues opened) before #1385 can be closed.
**Checklist**

Fix validation of dynamic Enum inside a Tuple

---

traits/tests/test_range.py
traits/trait_types.py

This PR implements `r.validate` on a dynamic `BaseRange` instance `r`, so that the trait knows how to do validation. Previously, all validation was done at trait-set time, so a standalone dynamic `Range` trait would be validated correctly, but a dynamic `Range` inside a `List` or `Tuple`  (or other container) wouldn't be validated at all.
Fixes #1391.
**Checklist**

Fix dynamic range in container Trait

---

traits/ctraits.c
traits/tests/test_tuple.py

This PR fixes tuple validation so that exceptions that occur when validating tuple subitems are propagated, instead of swallowed and ultimately turned into `TraitError`s.
Fixes #1389.
**Checklist**

Fix exception-swallowing behaviour of tuple validation

---

docs/source/conf.py
docs/source/traits_user_manual/intro.rst

fixes #1373 
This PR removes an unnecessary link to the TraitsUI user manual on the Intro page of the traits user manual.  It also adds links to the bullets for "Traits API Reference" and "Traits Technical Notes".  "Traits Technical Notes" is now linked to the changelog (I wasn't exactly sure what this was intended to be a reference to, this change should be confirmed by a reviewed)
Additionally, the buttons at the top of the page labels are changed.  The first button is now labelled "Traits 6.1 Documentation" as that is where that actually links to.  The second link comes from the title tag of individual pages (see: https://www.sphinx-doc.org/en/master/usage/configuration.html).  Building the docs and navigating to different pages the links seem to be labelled correctly now to the pages …

Fix errors on front page of user manual

---

.github/workflows/upload-to-pypi.yml

This PR adds a workflow for automatically building and uploading source distribution and wheels to PyPI when a Traits release is published.
Still to do:
- On macOS, the Python builders we use have `MACOSX_DEPLOYMENT_TARGET=10.14`, so the wheels built won't work on macOS versions earlier than 10.14
- On Linux, we build manylinux1 and manylinux2010 wheels. That's probably good enough for now, but at some point in the future we'll likely also want manylinux2014 wheels.
- On Windows (and only on Windows), we build wheels for 32-bit Python as well as for 64-bit Python. I'm assuming that there's essentially zero demand for 32-bit wheels on Linux.
- No provision for ARM-based Macs yet.
Closes #357.

Add workflow for building and uploading wheels

---

.github/workflows/test-from-pypi.yml

This PR adds a workflow to regularly test an installation of Traits and its test dependencies from PyPI.
Plan:

Add workflow to regularly test PyPI install

---

traits/testing/unittest_tools.py

This PR fixes a bad Instance declaration that effectively declared that a _lock trait could only be assigned a built-in function or method (and in particular, could not be assigned a lock).
I really wanted to rename the events trait to _events too as part of this PR, but I can't be absolutely sure that it's not being used elsewhere. (And it is used in the tests, which isn't a great sign.)
No regression test, because I couldn't find a way to exercise the issue using only the public API, and I don't really want to add tests that test internal implementation details. However, if/when we deprecate Instance(some_instance), this code will now fail to give a DeprecationWarning, where the code in master would have given such.
Fixes #1408.
(Recreation of bad PR #1410)
Checklist
- ~[ ] Update API …

Fix bad trait declaration for a threading Lock

---

docs/source/traits_user_manual/advanced.rst

closes #1318 
This PR pulls some content from the `Property` function docstring into the user manual in the section directly before the discussion on caching.  It still mentions the use of observe metadata in the caching section, but with slightly less bulk to try to avoid being too repetitive.  
Also, in PR #1350, the currentmodule was reset to be `traits.HasTraits` so that the Property Factory function was correctly documented.  However, the `Property` factory function actually lives in `traits.traits`, so that is updated here as well.
**Checklist**
- ~[ ] Tests~

Doc: Describe Property depends_on / observe without caching context in User Manual

---

traits/has_traits.py

closes #1327 
This PR simply adds one sentence to the docstring of `HasTraits.traits` mentioning that any trait with a suffix of "_items" will be excluded.
**Checklist**
- ~[ ] Tests~

Document HasTraits.traits excluding traits with name containing suffix "_items"

---

traits/trait_types.py

closes #1226 
This PR adds a statement to the docstrings of `Dict`, `List`, and `Set` mentioning that they copy values on assignment.  It also adds very brief clarifying examples like the ones mentioned on the issue, although those may be overkill for the docstring.  I convinced myself they were useful additions, but if a reviewer disagrees I am happy to remove them.
Also, this content would better be detailed (or should additionally be detailed) somewhere in the used manual.  As mentioned on the issue though, we currently don't have good sections on collection types.  There should be a separate issue for adding those sections if there isn't one already opened (I will check shortly).
**Checklist**
- ~[ ] Tests~
- ~[ ] …

Document that the `Dict`, `List` and `Set` trait types copy on assignment

---

CHANGES.rst

This PR adds a first cut of the changelog for the 6.2.0 release. Note that pending PRs are not yet included, so the changelog will need to be updated for those prior to the final release.
**Checklist**
- ~[ ] Tests  N/A~
- ~[ ] Update API reference (`docs/source/traits_api_reference`)  N/A~
- ~[ ] Update type annotation hints in `traits-stubs`  N/A~

Update changelog for 6.2.0 release

---

setup.py

The master branch is now targeting the next feature release of Traits, which will presumably be 6.3.0 (though it could end up being retargeted to 7.0.0). This PR bumps the version number accordingly.
I'll make the release maintenance branch after this PR is merged, from the commit preceding this one.
~Not to be merged until after #1405 has gone in.~  (Update: #1405 is in.)

Bump version number for continued feature development

---

traits/examples/introduction/default.css

After the move of the tutorial into the `traits/examples` subpackage, the `default.css` file was no longer being picked up. This PR makes a copy of that file in `traits/examples/introduction`. That _seems_ to work, but it's not clear to me whether this is the place that the `etsdemo` app expects CSS files to be.
I've checked that the CSS file also ends up in the source distribution.
@corranwebster Please could you check that this has the desired effect?
Fixes #1418.

Add missing CSS file for the 'introduction' tutorial

---

.github/workflows/run-core-traits-tests.yml

Extend the core traits tests workflow to also run on Python 3.10, so that we get alerted early to problems with the upcoming Python release.

Run core tests on 3.10-dev

---

traits/etsconfig/etsconfig.py
traits/etsconfig/tests/test_etsconfig.py

See enthought/enable#570
**Checklist**

Remove pyglet from kiva_backend consideration

---

docs/source/traits_api_reference/trait_types.rst
traits-stubs/traits-stubs/trait_types.pyi
traits-stubs/traits_stubs_tests/examples/Date.py
traits/tests/test_date.py
traits/trait_types.py

This PR makes it possible to specify that a `Date` trait should not accept `datetime` instances, which is usually the behaviour that the user expects/wants.
- Adds an `allow_datetime` parameter to `Date`. It defaults to `True`, for backwards compatibility.
- To make this possible, converts `Date` to a proper `TraitType` subclass.
Closes some but not all of #398. I'd like to leave that issue open for the question of considering changing the `allow_datetime` default under a deprecation warning.
**Checklist**
- ~[ ] Update User manual (`docs/source/traits_user_manual`)~ N/A - no user documentation for `Date`

Allow Date trait type to reject datetime instances

---

docs/source/traits_api_reference/trait_types.rst
traits-stubs/traits-stubs/trait_types.pyi
traits-stubs/traits_stubs_tests/examples/Date.py
traits/tests/test_date.py
traits/trait_types.py

This PR makes it possible to prevent assignment of `None` to a `Date` trait. (As usual, it doesn't prevent a _default_ value of `None`.)
Note that before the recently-merged PR #1429, `Date` was an instance of `BaseInstance`, and so in theory should already have allowed and respected `allow_none`. But a different bug (#495) means that `allow_none` was not respected. So this PR actually introduces a change in behaviour (effectively a bugfix) for anyone already doing: `foo = Date(allow_none=False)`: before this PR, assignment of `None` would still have been permitted for such a trait declaration. After this PR, it won't be.
In detail, we:
- Add a new parameter `allow_none` to `Date`, defaulting to `True` for backwards compatibility reasons
- Prevent assignment of `None` if `allow_none` is …

Make allow_none functional in the `Date` trait type

---

traits/tests/test_date.py
traits/tests/test_datetime.py
traits/tests/test_instance.py
traits/tests/test_time.py
traits/trait_type.py
traits/trait_types.py

Currently instances of `BaseInstance` don't clone themselves correctly when called with a new version of `allow_none`. This means that `Time(allow_none=False)` and `Datetime(allow_none=False)` don't work as expected:
Example (on the master branch):
```python
>>> from traits.api import *
>>> Slice = BaseInstance(slice)
>>> SliceNotNone = Slice(allow_none=False)
>>> Slice.validate(None, "dummy", None)  # accepts None, as expected
>>> SliceNotNone.validate(None, "dummy", None)  # accepts None, but shouldn't
```
This PR fixes the issue by extending the base class `clone` method to add special handling of `allow_none`. With the PR, the above example becomes:
```python
>>> from traits.api import *
>>> Slice = BaseInstance(slice)
>>> SliceNotNone = Slice(allow_none=False)
>>> …
```

Fix allow_none to work correctly on BaseInstance objects

---

traits/examples/introduction/default.css

This fixes the distinct colours in the code samples, plus switches from the orange color scheme to a more usual Enthought blue.
This is a follow on from #1419 and should fix #1420.

Fix issues with tutorial CSS

---

traits/examples/introduction/1_validation.py
traits/examples/introduction/2_initialization.py

Drive-by typo fix: fix occurrences of "aquired" in the examples code and comments, replacing them with "acquired".

Typo fix: aquired -> acquired

---

traits/tests/test_directory.py
traits/tests/test_file.py
traits/trait_types.py

This PR customises the trait description for the `File` and `Directory` trait types to take into account whether `exists` was true or not.
For the `File` trait, the description has changed from "a filename or object implementing the os.PathLike interface" to "a string or os.PathLike object" in the normal case and "a string or os.PathLike object referring to an existing file" for the `File(exists=True)` case. The changes for `Directory` are analogous.
Before:
```python
>>> from traits.api import Directory, File, HasStrictTraits
>>> class A(HasStrictTraits):
...     home_dir = Directory(exists=True)
...     config_file = File(exists=True)
... 
>>> a = A()
>>> a.home_dir = 47
File "<stdin>", line 1, in <module>
File …
```

Change File and Directory trait descriptions to take into account the 'exists' flag.

---

traits/tests/test_date.py
traits/trait_types.py

This PR paves the way for eventually making it illegal to pass a `datetime.datetime` instance to a `Date` trait:
- Change the default for `allow_datetime` to `None` rather than `True`
- If `allow_datetime` is not supplied and the user tries to assign a `datetime.datetime` value to a `Date` trait, a `DeprecationWarning` is issued. In the future (ideally in Traits 7.0), a `TraitError` will be raised.
Rationale: right now, `Date` allows any value that's an instance of the Python std. lib. `datetime.date` class. Somewhat surprisingly, Python's `datetime.datetime` is a subclass of `datetime.date`. But in typical uses for the `Date` trait, we really do want to specify a date and not a datetime.
Users who do want to allow datetimes in addition to date can modify their code in a number of ways to …

Deprecate allowing datetime.datetime instances as values for Date traits

---

docs/source/traits_api_reference/trait_types.rst
traits-stubs/traits-stubs/trait_types.pyi
traits-stubs/traits_stubs_tests/examples/Datetime.py
traits-stubs/traits_stubs_tests/examples/Time.py
traits/tests/test_date.py
traits/tests/test_datetime.py
traits/tests/test_time.py
traits/trait_types.py

This PR builds on #1441 to also deprecate acceptance of `None` values for `Date` traits. While I think this is the right way to go, ~this does introduce a discrepancy with the `Datetime` and `Time` classes, where `None` is still accepted by default with no deprecation warning issued.~
Update: the PR has been extended to cover `Datetime` and `Time` classes; this required realising the `Datetime` and `Time` trait types (so that they're no longer instances of `BaseInstance`).
Closes #1438
**Checklist**

Deprecate None values for Date, Datetime and Time trait types

---

traits/etsconfig/etsconfig.py
traits/etsconfig/tests/test_etsconfig.py

This PR updates `ETSConfig` to support the use of `qt` as the toolkit name for Qt4 and Qt5 instead of only supporting `qt4` as the toolkit name for Qt4. This is in line with similar changes we have made in other ETS packages e.g. traitsui, enable.
**Checklist**

Support qt toolkit name for Qt5 and Qt4

---

traits/editor_factories.py
traits/tests/test_editor_factories.py

**Checklist**
This PR fixes https://github.com/enthought/traitsui/issues/1539
The `row_factory` for a `TableEditor` should be a callable if it is not None, see:
https://github.com/enthought/traitsui/blob/7a6d46ad10ea6c6b5a8dcc3b4939a9670c2a52ad/traitsui/editors/table_editor.py#L291-L296
Previously there was a case in which we used an `Instance` trait's `default_value`.  ~However, there is a situation in which this is an instance of `_InstanceArgs`, see:~
~https://github.com/enthought/traits/blob/2b62cd9b39bcb9e4998eeab0b32a4e3127b3df66/traits/trait_types.py#L3353-L3356~
EDIT: This was not correct, it was …

row_factory should be a callable for TableEditors 

---

docs/source/traits_user_manual/advanced.rst

Remove mentions of `HasTraits.get()`.
This PR closes issue #896.
There are a few other occurrences of `set()` functions:
- `threading.Event.set()` (unrelated)
- `set()` constructor (unrelated)
- implementation, test and Traits stubs for `HasTraits.set()` (scheduled to be removed, see #898)
- `TraitType.set()` used for property traits (unrelated)
- `Symbol.set()` and `WeakRef.set()` which are overwriting `TraitType.set()` (unrelated)
**Checklist**

Remove mentions of `HasTraits.get()`

---

traits/util/resource.py

Fixes https://github.com/enthought/traits/issues/1449
Removes the dependence on distutils, by replacing `distutils.sysconfig.get_python_lib` with `sysconfig.get_path`
`distutils.sysconfig.get_python_lib` with no flags defaults to `plat_specific=0, standard_lib=0`
https://github.com/pypa/distutils/blob/main/distutils/sysconfig.py
This is equivalent to `sysconfig.get_path('purelib')`
https://docs.python.org/3/library/sysconfig.html?highlight=purelib
**Checklist**
- [ n/a ] Tests
- [ n/a ] Update API reference (`docs/source/traits_api_reference`)
- [ n/a ] Update User manual (`docs/source/traits_user_manual`)
- [ n/a ] Update type annotation hints in `traits-stubs`

Replace distutils.sysconfig.get_python_lib with sysconfig.get_path

---

.github/workflows/test-documentation-build.yml

The documentation build is now picking up Sphinx 4.0.1, and is breaking as a result. We need to fix that, but short term we also need to pin Sphinx to a version < 4.0 so that other PRs (like #1461) can be merged.
I'm making this PR to both confirm the breakage independently of #1461, and to fix it. I'm expecting the doc build to fail until I pin Sphinx in a separate commit.

Fix documentation build

---

traits/has_traits.py
traits/tests/test_abc.py
traits/tests/test_has_traits.py

This PR fixes the issue described in #1460, and adds some tests for `add_class_trait`. Prior to this PR, there were no tests at all for `add_class_trait`.
The PR also does a drive-by fix of a bug involving prefix traits and an invalid use of `sort`, leading to the error `TypeError: sort() takes no positional arguments`.
Unfortunately, one of the newly added tests is failing as part of the full test suite, but passing standalone. It appears that we have a test interaction - some test somewhere in the test suite is mutating the class traits on `HasTraits`. I'll try to track it down.
**Checklist**

Fix add_class_trait in the presence of subclasses

---

traits/has_traits.py

Rival PR to #1453. This PR rewrites the docstring for `HasTraits.trait_get` to better explain the various different (and conflicting) ways it can be used.
**Checklist**

Rewrite the docstring for HasTraits.trait_get

---

traits/tests/check_observe_timing.py

This PR removes two out-of-date comments, which refer to a feature that's "available on master only"; that feature is now available in released versions of Traits.
(See also #1466.)

Remove out-of-date references to the master branch

---

traits/observation/_observe.py
traits/observation/observe.py

This PR fixes the docstring of the `dispatcher` argument on `traits.observation.api.observe` (not the decorator!).
The mention of dispatching onto a different thread is merely an example, the "i.e." is misleading.
This PR fixes that and also clarifies the default behavior.
**Checklist**
- ~Tests~

Fix docstring to observe's dispatcher callable

---

traits/etsconfig/etsconfig.py

closes #1454
This PR simply updates the uses of the `property` callable to use the `@property` decorator. 
**Checklist**
~- [ ] Tests~ Tests already exist for getting and setting these properties in https://github.com/enthought/traits/blob/master/traits/etsconfig/tests/test_etsconfig.py
~- [ ] Update User manual (`docs/source/traits_user_manual`)~ ETSConfig is not currently in the user manual (but it ideally should be! see #1427)

Use property decorators instead of property callable

---

traits/ctraits.c
traits/tests/test_ctraits.py

This PR changes attribute lookups on `CTrait` objects to raise `AttributeError` for names beginning and ending with a double underscore, and for which the normal attribute lookup rules don't return anything. Previously, those attribute lookups would return `None`, and this broke napoleon, which expected that a lookup of `__qualname__` on a `CTrait` object would either raise or return a string.
Attribute lookups for names that _don't_ begin and end with a double underscore are unchanged.
No documentation  update: it's not currently documented that arbitrary attribute accesses on a `CTrait` object return `None`, and I'm not sure that I really want it to be - it's not a "feature" of Traits that I'd want to encourage people to rely on.
Fixes #1463.
**Checklist**

Make accessing dunder-names on a CTrait object an AttributeError

---

.github/workflows/test-documentation-build.yml

This PR reverts the Sphinx version pin introduced in #1462: it should no longer be necessary since #1463 was fixed.
Undoes the effects of #1462.

Remove restriction on Sphinx version

---

traits/has_traits.py
traits/tests/test_has_traits.py

PR #1469 made accessing nonexistent double-underscore-named attributes on a cTrait instance an `AttributeError`. Unfortunately, Envisage uses a metadata attribute `__extension_point__` to identify extension points, and the filtering facilities of `HasTraits.traits` and `HasTraits.class_traits` fail as a result.
This PR fixes calls like `hastraits_obj.traits(__extension_point=True__)` and `hastraits_obj.class_traits(__extension_point__=True)` so that they no longer fail with an `AttributeError`.
Motivated by enthought/envisage#430, but may not fix it completely.

Fix trait selection by metadata

---

traits/util/trait_documenter.py

The `add_content` method in the `trait_documenter` Sphinx extension is causing a `DeprecationWarning`. It looks as though we don't need it, and this PR removes it.
In manual testing with a range of Sphinx versions from 1.8.5 onwards, after removing this method, I was unable to observe either documentation build failures or visible problems with the built documentation.
I'd be slightly happier if I understood why this code was there in the first place, but I've failed to discover the reason. @itziakos is the original author of this code, and may have some ideas.
It's also worth noting that since #1469, an attempt to access the `__doc__` attribute on a `CTrait` object will fail in the expected way, rather than potentially confusing Sphinx by returning `None`, so I can't think of any reason …

Remove unnecessary(?) method that's causing a deprecation warning

---

traits/ctraits.c

The `is_dunder` variable was left unused after a late refactor in #1469 (see https://github.com/enthought/traits/pull/1469/commits/a132475ef49798ec4490a91b33056b5f4d11cd4a); this PR removes it.

Remove unused variable

---

.readthedocs.yaml
docs/requirements.txt

This PR adds a basic configuration file for Read the Docs. This file was sufficient to get the RtD build passing. See https://traits.readthedocs.io/en/docs-readthedocs-config/ for the documentation built from this branch.

Add configuration file for Read the Docs

---

.github/workflows/test-from-pypi.yml

It's helpful to be able to trigger all the CI cron jobs manually (e.g., when debugging). This PR adds the 'workflow_dispatch:' trigger to the Traits cron job.

Add workflow_dispatch trigger to cron job

---

.github/workflows/test-from-pypi.yml

This PR sets up slack notifications for the cron jobs in this repository. I manually triggered the cron jobs on this branch to check that the slack notifications were fired as expected. Ref https://github.com/enthought/traits/actions/runs/1027333124.
This is one more step towards https://github.com/enthought/ets/issues/65
**Checklist**

Setup slack notifications for cron jobs

---

traits/traits_listener.py

This PR refactors the `ListenerParser` to turn it into a plain old Python class, rather than a `HasTraits` class.
This was mostly motivated by performance; this is only a small part of the performance story, but it is a part, and it's easy to fix. The overall goal is to speed up the creation of Traits listeners, since that was proving a bottleneck in some large Traits-using applications. This PR speeds up parsing of listener text strings like "foo.bar[]".
The behaviour of the old class also didn't make a lot of sense: in the `__init__` method, there was a line `self.text = text`, prior to calling the superclass `__init__`. That `self.text = text` assignment triggered the `_text_changed` method, which then did all the parsing. That meant that _all_ of the parsing had already taken place, …

Refactor ListenerParser to be a plain old Python class

---

traits/has_traits.py
traits/traits_listener.py

Context: This PR follows on from #1490. It's part of a larger effort to identify and ameliorate performance bottlenecks in the on_trait_change, while not changing the `on_trait_change` behaviour.
This PR changes the way that `ListenerItem`s are initialised. Previously, in the `on_trait_change` method:
* a `ListenerParser` created a tree of `ListenerBase` instances (`ListenerItem`s and `ListenerGroup`s),
* then the `handler`, `wrapped_handler_ref` and `dispatch` traits were set on the root node of the tree
* and static trait-change handlers took care of propagating those changes down the tree
Those static trait-change handlers are one cause of slowness in a large Traits-using system.
With this PR, the `ListenerParser` takes care of provisioning all the `ListenerItem`s at creation time, …

Speed up on_trait_change, part II

---

traits/has_traits.py
traits/traits_listener.py

~[PR against branch for #1491, for ease of review]~
This PR continues the work in #1491, removing more after-the-fact trait setting in the `ListenerItem` and `ListenerGroup`.
It addresses the three traits `priority`, `deferred` and `type` on the `ListenerItem`. With this PR, the need for the `trait_set` operation after creating the listener is completely removed.
Handling `priority` is straightforward, and the approach taken is similar to the approach taken in #1491: the `priority` value is stored on the `ListenerParser`, and injected into the `ListenerItem` objects as they're created.
The other two traits can't be handled in the same way, since their value differs depending on where in the listener tree we are.  Instead, we pass the `type` and `deferred` values through the parsing …

Speed up on_trait_change, part III

---

traits/tests/test_traits_listener.py
traits/traits_listener.py

Fixes #1494.
I've added a couple of unit tests for `ListenerHandler`, testing the two main use-cases (methods and functions as handlers). I don't have a regression test for the race condition - the race condition exists, but is almost impossible to reproduce programmatically.

Fix ListenerHandler race condition

---

traits/adaptation/api.py
traits/etsconfig/api.py
traits/observation/api.py
traits/testing/api.py
traits/util/api.py

This is a drive-by cleanup PR that removes unnecessary "#  noqa: F401" comments from `api.py` files. We already have a [per-file-ignores setting](https://github.com/enthought/traits/blob/b343ea87a02c74f9b74c16efe6a02bd3d883eccb/setup.cfg#L4) in our `setup.cfg` for this.

Remove unnecessary 'noqa' markers

---

traits/has_traits.py
traits/traits_listener.py

This PR completes the removal of `HasTraits` machinery from the traits minilanguage parsing machinery.

Speed up on_trait_change, part IV

---

traits/util/resource.py
traits/util/tests/test_resource.py

This PR deprecates `traits.util.resource.find_resource` and `traits.util.resource.store_resource`. New code should use `importlib.resources` or its fallback `importlib_resources` instead.
The only existing uses of `find_resource` I could find either in ETS projects or internal Enthought projects were in Chaco example code. There appear to be no uses of `store_resource` in current code.
Related: enthought/chaco#657.
Closes #1500.

Deprecate find_resource and store_resource

---

docs/source/traits_api_reference/trait_notifiers.rst
docs/source/traits_user_manual/listening.rst
traits-stubs/traits-stubs/has_traits.pyi
traits/has_traits.py
traits/tests/test_traits_listener.py
traits/trait_notifiers.py
traits/traits_listener.py

The existing anytrait-handling machinery sometimes spells related objects and names using `any_trait` and sometimes using `anytrait`. The user-facing portion is always spelled `anytrait`; this PR changes related internal occurrences of `any_trait` to `anytrait`.
Includes one actual fix to a documentation index entry.

Use anytrait consistently

---

traits/observation/parsing.py
traits/observation/tests/test_parsing.py

This PR updates the `parse` method in `traits.observation.api` to raise `ValueError` instead of `LarkError`. The `LarkError` exception is an implementation detail that users should be shielded from - we may replace the lark-based parser with some other parser in the future, and users shouldn't have to change their code in that case.
I made this change because I found myself wanting to writing tests to check that particular expressions were invalid, and neither of `self.assertRaises(LarkError)` nor `self.assertRaises(Exception)` seemed like a palatable option for those tests.
Fixes #1504.

Raise ValueError on parse failure

---

traits/observation/_dict_item_observer.py
traits/observation/_filtered_trait_observer.py
traits/observation/_list_item_observer.py
traits/observation/_metadata_filter.py
traits/observation/_named_trait_observer.py
traits/observation/_observer_graph.py
traits/observation/_set_item_observer.py
traits/observation/tests/test_dict_item_observer.py
traits/observation/tests/test_filtered_trait_observer.py
traits/observation/tests/test_list_item_observer.py
traits/observation/tests/test_metadata_filter.py
traits/observation/tests/test_named_trait_observer.py
traits/observation/tests/test_observer_graph.py
traits/observation/tests/test_set_item_observer.py

This PR adds `__slots__` to seven key classes related to the observe machinery, namely the `ObserverGraph` and all the objects that it has references to in normal use.
This is a partial fix for #1511. We probably want to add `__slots__` to the various expression classes too, though that will have a smaller benefit.

Add __slots__ to key observation classes

---

traits/observation/expression.py
traits/observation/tests/test_expression.py

Along with #1513, this closes #1511.

Add __slots__ to ObserverExpression and its subclasses

---

traits/has_traits.py
traits/observation/expression.py
traits/observation/parsing.py

This PR adds an LRU cache to the `compile_str` function that compiles an observe mini-language expression in text form to a collection of `ObserverGraphs`.
In testing on a medium-sided Traits-using application, this reduced the number of calls to `ObserverExpression._as_graphs` from `221` to `90` at application startup time.
The PR also hoiks compilation of the expression provided to an `observe` decorator up a level: in code like:
```
@observe("foo:bar.baz")
def _some_method(self, event):
...
```
compilation currently (in main) occurs when `observe("foo:bar.baz")` is applied to the `_some_method` function. With this PR, it occurs as part of the `observe("foo:bar:baz")` call instead. This will rarely make a difference to real code, but it does allow the possibility of sharing …

Cache calls to compile_str

---

traits/observation/expression.py
traits/observation/tests/test_expression.py
traits/observation/tests/test_parsing.py

The current `ObserverExpression` implements equality via `_as_graphs`, I suspect purely as a convenience for testing purposes. This PR replaces that equality check with a simple structural equality. It also:
- makes all expressions hashable, to make caching easier
- adds convenience `__repr__` implementations
- renames the `observer` attribute to `_observer`, for consistency with the other expression classes, to emphasize that it's not used outside this module, and to discourage users from modifying the value
- fixes one (recently-introduced) test

Replace equality definition on ObserverExpression

---

traits/has_traits.py

From #1486: `sync_trait` synchronises items for `List` traits, but not for `Dict` and `Set` traits. This PR documents that fact.

Note that sync_trait only synchronises items for List traits

---

traits-stubs/traits-stubs/trait_types.pyi

This PR fixes some IDE complaints in `trait_types.pyi`: it removes an unused import ("Generic") and fixes some line-spacing issues.

Style fixes in trait_types.pyi

---

traits/tests/test_tuple.py
traits/trait_types.py

This PR fixes the `Tuple` trait type so that it only uses a constant default value when all of its component traits can use a constant default value. This includes simple cases like `Tuple(Int(), Str())` as well as nested cases like `Tuple(Int(), Tuple(Int(), Str()))`.
Fixes #1520.

Make Tuple use a dynamic default when necessary

---

traits/tests/test_has_traits.py

This PR fixes a bad handler signature in a test. The bad signature was detected by the code in PR #1529.

Fix a handler signature in a test

---

traits/observation/expression.py
traits/observation/observe.py
traits/observation/parsing.py

This PR adds an LRU cache for the `compile_expr` function, to eliminate unnecessary calls to `_as_graph`. I also made a one-line change in the `observe` function so that all expression compilation goes through `compile_expr`.
I've also boosted the size of the three parsing-related caches from 128 entries to 256.
I opted not to do a per-Expression-object caching of the result of the `_as_graphs` call (as [suggested](https://github.com/enthought/traits/pull/1516#issuecomment-916089926) in the #1516 discussion); it adds extra complication in that it makes the `Expression` objects mutable, and so introduces potential thread-safety concerns; in contrast, `lru_cache` has thread-safety provisions built in. There's benefit in keeping the `Expression` objects as simple immutable pure data …

Cache the result of the compile_expr function

---

traits/util/clean_strings.py
traits/util/tests/test_clean_strings.py

The `clean_filename` and `clean_timestamp` utility functions have nothing to do with Traits and are not documented or exposed in any of the `api` modules; additionally, `clean_timestamp` has no tests. This PR deprecates those functions, so that they can be removed in Traits 7.0.0.
A check of ETS and private ETS-using projects that I have access to turned up no uses of either function.
Closes #1447.
**Checklist**

Deprecate the clean_filename and clean_timestamp utilities

---

traits/has_traits.py
traits/tests/test_observe.py

This PR adds a runtime warning for an observe-decorated method whose signature is incompatible with 'observe'.
I'm in two minds about whether this is a good idea - it's unnecessary runtime overhead, but on the other hand that runtime overhead should be small and will typically only apply at import time.
One the other hand, forgetting the `event` parameter is a very common mistake with `observe`-decorated methods, especially since the event-less signature is compatible with `on_trait_change`.
I haven't extended the fix to dynamic applications of `observe`: `a.observe(handler, expression)`; that does seem like a case where we don't want the extra runtime overhead, since there may be many hidden calls to `observe` in a codebase, but occurrences of the `observe` decorator are limited in …

Warn on a bad signature for an 'observe'-decorated function

---

traits/tests/test_union.py
traits/trait_types.py

The logic introduced in #1522 for handing dynamic defaults in `Union` traits was buggy. This PR fixes that logic and improves the test.
Closes #1533 .
**Checklist**

Fix bug in handling of Union default value

---

traits/tests/test_constant.py
traits/trait_types.py

[Part of #1538]
This PR bypasses default_value_type inference for the `Constant` trait type. It also adds tests to check that default values are shared. Those tests reflect the behaviour both prior and post PR - the PR shouldn't change the behaviour here.

Bypass default_value_type inference for Constant

---

traits/tests/test_any.py
traits/trait_types.py

The `Any` trait type currently goes through the normal inference for `default_value_type`. The only cases where this inference is likely to produce something other than `DefaultValue.constant` are traits of the form `Any(some_list)` or `Any(some_dict)`. In those cases, we end up with `DefaultValue.list_copy` and `DefaultValue.dict_copy` respectively. This means that the default is copied for each `HasTraits` instance, so we end up with a per-instance non-shared default instead of a per-class shared default value.
This PR moves the inference from the `TraitType` base class to `Any.__init__`, and deprecates the use of the `DefaultValue.list_copy` and `DefaultValue.dict_copy` default value types. The intent is to use `DefaultValue.constant` consistently in Traits >= 7.0.
Rationale for the …

Limit, document, test and deprecate default_value_type inference for 'Any'

---

traits/tests/test_regression.py
traits/tests/test_trait_types.py
traits/tests/test_union.py
traits/trait_types.py

Another step towards #1538:
- Don't infer the default value type for `BaseType`, `Function`, `Method` and `Module`
- Fix some `TraitType` subclasses used in testing to avoid the inference
- Tangential fix: fix a place where `TraitType` was being used directly in tests. (In general, `TraitType` should be seen as an abstract base class, and should not be instantiated directly.)

Fix more cases where the default_value_type is inferred unnecessarily

---

traits/trait_types.py

The `TraitType` base class currently has a `default_value_type` of `DefaultValue.unspecified`; as a result, most `TraitType` subclasses do a collection of `isinstance` checks at trait type instantiation time, in order to infer the appropriate default value type to use.
But for most concrete trait types, the appropriate `default_value_type` is already known (and in almost all cases it's `DefaultValue.constant`).
This PR overrides `default_value_type` for most of the concrete trait types. There are some trait types that are messier (notably `Any` and `Instance`, and I'm deferring those for a separate PR. Eventually, I'd like to be able to ensure that we're never using the default value type inference for `TraitType` subclasses and relegate that code to the old `TraitHandler`s. The wider …

Don't infer the default value type when it's clear from context

---

traits/tests/test_trait_types.py
traits/trait_types.py

The `Function` and `Method` trait types were deprecated in #1397 and #1399 (respectively), but the `__init__` method introduced wasn't general enough - it prevented uses of `Function` and `Method` with a default value or with metadata. This PR fixes that.

Fix deprecation of Function and Method

---

traits/tests/test_trait_types.py
traits/trait_types.py

This PR deprecates the `Symbol` trait type, which was untested, unused in code that I have access to (with one exception, where it can be easily replaced), and has some slightly dangerous eval-based semantics. It's also not really a good fit for a trait, since it involves neither validation nor notification.
- ~[ ] Update User manual (`docs/source/traits_user_manual`)~ N/A
- ~[ ] Update type annotation hints in `traits-stubs`~ N/A

Deprecate the Symbol trait type

---

traits/tests/test_none.py
traits/tests/test_union.py

Drive-by cleanup: some time ago we removed all the `if __name__ == "__main__"` blocks from test modules; it appears a couple have crept back in. This PR removes them.

Remove unnecessary unittest.main blocks

---

traits/tests/test_enum.py

Following #1532, this PR fixes an instance of the `DeprecationWarning` from one of the tests. This warning doesn't usually show up in the test run, because it's triggered at import time rather than during the test run. However, it can be seen when running the tests under `python -Wd -m unittest`.

Fix a DeprecationWarning from a test

---

docs/source/traits_user_manual/defining.rst
examples/tutorials/doc_examples/examples/metadata.py

A belated followup to #1532: fix occurrences of `Any(some_list)` from the documentation.

Fix occurrences of Any(some_list) in docs

---

traits/has_traits.py

Drive-by cleanup for `HasTraits`: use better trait definitions for `trait_added` and `trait_modified`.

Use a proper trait type for the inner trait in trait_added

---

traits/has_traits.py
traits/tests/test_has_traits.py

Deprecate MetaHasTraits.add_listener and MetaHasTraits.remove_listener

---

traits-stubs/traits-stubs/trait_types.pyi

Fix parameter name typo in stubs

---

docs/source/traits_user_manual/defining.rst
traits-stubs/traits-stubs/trait_types.pyi
traits-stubs/traits_stubs_tests/examples/Any.py
traits/tests/test_any.py
traits/trait_types.py

This PR adds `factory`, `args` and `kw` keyword-only arguments to the `Any` trait type initializer, allowing a default value for an `Any` trait to be specified via a factory, in much the same way as this already works for the `Instance` trait type.
The main goal is to provide a clean migration path for existing code using `Any({})` or `Any([])`. With Traits 6.3, such code will run into the deprecation introduced in #1532, and can now use `Any(factory=dict)` or `Any(factory=list)` as a suitable replacement that won't warn.
**Checklist**

Add 'factory' support for the Any trait type

---

traits/trait_types.py

Now that #1557 is merged, this PR updates the deprecation messages issued by `Any` to suggest using `factory`.

Update Any deprecation messages to mention 'factory'.

---

docs/source/traits_user_manual/listening.rst
traits/has_traits.py
traits/tests/test_has_traits.py

This PR changes the behaviour of a method that's decorated with `observe` but also has the magic `_somename_changed` naming.
Prior to this PR, such a method would be registered twice by the Traits machinery, and called once with a `TraitChangeEvent` and once with the new value of the trait:
```python
>>> from traits.api import *
>>> class A(HasTraits):
...     foo = Int()
...     @observe("foo")
...     def _foo_changed(self, arg):
...         print(arg)
... 
>>> a = A()
>>> a.foo = 23  # Expect one call to `print`; get two calls.
23
TraitChangeEvent(object=<__main__.A object at 0x10ad14450>, name='foo', old=0, new=23)
```
With this PR, it will only be called once, with the `TraitChangeEvent`: the `observe` decorator supersedes and nullifies the magic naming. This is the same behaviour …

Fix an observe-decorated _name_changed method

---

traits/trait_types.py

This PR completes the removal of `default_value_type` inference for the remaining `TraitType` subclasses that still use it: `Delegate`, `Event` and `Disallow`. I wanted to use a type of `DefaultValue.disallow` for these instead of `DefaultValue.constant`, but that caused issues in TraitsUI `ViewSubElement`, here: https://github.com/enthought/traitsui/blob/114b29131c1fe92eb945bf1118574f1732b3fa15/traitsui/view_element.py#L184. That code relies on being able to call `default_value_for` and get a meaningful result for any trait.
After this PR, the `_infer_default_value_type` function in `trait_type.py` is only exercised by a single test.

Bypass default_value_type inference for remaining TraitType subclasses

---

traits/tests/test_prefix_list.py
traits/tests/test_prefix_map.py
traits/trait_types.py

This PR does some refactoring and cleanup on the `PrefixList` and `PrefixMap` trait types. It's a more careful re-invention of the changes in #1563 (extended to `PrefixMap`).
Principal user-facing changes:
- The cache for value completion, which was questionable from a thread-safety point of view (see #1561) has been removed, but validation for a value that's in the list / map rather than just a prefix will still be O(1), not O(n). Validation for a value that has to be completed will now be O(n) in every case rather than being O(n) on the first use and O(1) thereafter. However, we're not expecting these trait types to be used with value lists big enough for this to make a difference.
- A bad static default value in the trait type definition will now consistently raise `ValueError` rather …

Clean up PrefixList and PrefixMap

---

setup.py

This PR bumps the version on the main branch; the main branch now targets the Traits 6.4.0 release (or possibly Traits 7.0.0).

Bump version for continued development towards Traits 6.4

---

.github/workflows/test-from-pypi.yml

Now that wheels for Traits 6.3 have been uploaded to PyPI, this PR re-adds Python 3.10 as a target for testing those wheels. This undoes the effects of #1572.

Include Python 3.10 in install-from-pypi tests

---

CHANGES.rst
traits/tests/test_prefix_map.py
traits/trait_types.py

This PR makes `PrefixMap._map` available again (following its removal in #1564), to avoid breaking Mayavi.
**Checklist**
Closes #1577.

Backwards compatibility fix: make `PrefixMap._map` available

---

setup.py

The maint/6.3 branch is now open for development towards a possible 6.3.2 release. This PR bumps the version number accordingly.

Bump version for development towards 6.3.2

---

docs/source/traits_user_manual/listening.rst

Document the '-' pattern for on_trait_change.

---

setup.py

We were excluding NumPy as a test dependency for Python 3.10 because PyPI wheels weren't yet available on all platforms we were testing on. Those wheels are now available, so the restriction can be removed.

Re-include NumPy as a test dependency on Python 3.10

---

CHANGES.rst

This PR is a backport of #1596 to the maint/6.3 branch, in preparation for the 6.3.2 release.

Backport #1596 to the 6.3 maintenance branch

---

.github/workflows/run-core-traits-tests.yml

This PR extends the run-core-traits-tests workflow to include testing on Python 3.11-dev.

Run core tests on Python 3.11

---

traits/ctraits.c
traits/tests/test_float.py
traits/trait_types.py

The validations of the `Float` and `BaseFloat` trait types previously didn't match: in particular, for Python >= 3.8, `Float` accepts objects whose type is equipped an `__index__` method, while `BaseFloat` does not. That was partly to do with the difficulty of expressing the condition to be accepted as a float in pure Python.
This PR sidesteps that difficulty by exposing the `Float` validation check to Python via a new private function `traits.ctrait._number_to_float`.
See also #1594, which makes essentially the same change to ensure that `Complex` and `BaseComplex` match. These two PRs will cause merge conflicts with each other, but they shouldn't be too difficult to resolve.
**Checklist**

Fix BaseFloat validation to match Float validation

---

traits/constants.py
traits/ctraits.c
traits/tests/test_complex.py
traits/trait_types.py

This PR changes the validation of the `Complex` trait type to use a duck-typed approach instead of the current white-list-of-accepted-types approach. All values that were previously accepted in a `Complex` trait will continue to be accepted, but objects whose type implements `__complex__` will now also be accepted. Essentially, `Complex` will accept any non-string-type that the `complex` built-in accepts.
This parallels similar changes made a while ago for the `Int` and `Float` trait types (see #104, #393), both of which already do duck-typed checks. It makes it clearer that the behaviour of the `Complex` trait type does not depend on whether NumPy is available or not, and it ensures that `Complex` will accept complex-like objects from other frameworks.
Implementation notes:
- I've added …

Make Complex trait type validation duck-typed.

---

traits-stubs/traits-stubs/trait_types.pyi
traits/tests/test_trait_types.py
traits/trait_types.py

This PR removes some constants that are no longer needed within Traits, namely `int_fast_validate`, `float_fast_validate` and `complex_fast_validate`. The need for `complex_fast_validate` was removed in #1594. The other constants haven't been used for some time, except that `float_fast_validate` is used in a test that verifies validation in the presence of NumPy - I've switched that test to check `bool_fast_validate` instead.
These constants aren't exported in any of the `api` modules, so they shouldn't be being used by any other package. A check through the source available to me shows no uses in other packages.

Remove unused fast validation tuples

---

etstool.py

The `ci-src-requirements.txt` file isn't used anywhere, despite comments in `etstool.py` saying that it is. This PR removes the unused file, and the comments that refer to it.

Remove unused ci-src-requirements.txt file

---

.github/workflows/run-traits-tests.yml

It's occasionally useful to be able to run the main test workflow manually (e.g., if there have been environmental changes, like the recent change from macOS 10 to macOS 11 for GitHub Actions workers).
This PR adds a "workflow_dispatch" trigger to the main workflow.

Allow running the main test workflow manually

---

traits/tests/test_regression.py
traits/tests/test_trait_dict_object.py
traits/tests/test_trait_list_object.py
traits/tests/test_trait_set_object.py
traits/trait_dict_object.py
traits/trait_list_object.py
traits/trait_set_object.py

This PR makes a shallow fix for problems with `clone_traits` applied to `List`, `Dict` and `Set` traits. It doesn't try to touch deeper issues of disconnection of `TraitsListObject`, `TraitDictObject` and friends from their owning `HasTraits` object.
Closes #1622. The cause of that issue is that we were [using a function](https://github.com/enthought/traits/blob/c8bd6e5f332d44b512b79f0bee3cb814b9125352/traits/trait_list_object.py#L815) `lambda: None` for `object` where a `HasTraits` object was expected. Inside `TraitListObject` we then [take a weakref](https://github.com/enthought/traits/blob/c8bd6e5f332d44b512b79f0bee3cb814b9125352/traits/trait_list_object.py#L572) to that function. In most cases, the `lambda` function has no other references to it, so it's garbage collected immediately …

Fix cloning issue with container traits

---

docs/source/traits_user_manual/listening.rst

This PR builds on #1617 to make more extensive updates and fixes to the `on_trait_change` documentation:
- Many things that apply to `List` and `Dict` also apply to `Set`; fix missing mentions of `Set`
- The `trait_name[]` pattern applies to both `List` and `Set` (but not `Dict`); fix docs accordingly
- Some minor style, consistency and typographical fixes.

Fix more missing mentions of Set in notification docs

---

traits/tests/test_tuple.py
traits/trait_types.py

This PR changes the `Tuple` trait type so that it only ever accepts instances of type `tuple`. Previously, the argument-less trait type `Tuple()` would accept (and coerce) `list` instances in addition to `tuple` instances, while with arguments (e.g., `Tuple(Int(), Int())`, only tuples would be accepted.
Work towards #1626, but this PR doesn't change the behaviour of the `BaseTuple` trait type at all.
**Checklist**

Deprecate acceptance of lists by Tuple traits

---

setup.cfg

A combination of recent versions of `setuptools` and `pip` results in `pip install -e .` creating a local `build` directory. This PR prevents flake8 from attempting to check files in that directory.
**Checklist**

Exclude build directory in flake8 configuration

---

docs/source/traits_user_manual/defining.rst
traits/trait_numeric.py

This PR removes the long-deprecated 'typecode' parameter to `AbstractArray` and its subclasses.
**Checklist**

Remove the deprecated 'typecode' parameter to Array trait types

---

traits/ctraits.c
traits/tests/test_ctraits.py
traits/tests/test_list.py
traits/tests/test_trait_types.py
traits/trait_type.py

This is a two-part fix for #1629:
- Part 1: fix `ctraits.c` to validate the input to `set_default_value` in the case where the given default value type is `DefaultValue.callable_and_args`. This fixes the segfault reported in #1629, replacing it with a more scrutable Python-level exception.
- Part 2: in the `TraitType.clone` base class implementation, when we set a default value, also set the default value type to be consistent with that default value. This still leaves open the possibility for `TraitType` subclasses to do their own thing in their `clone` methods (and in particular, the `List`, `Dict` and `Set` trait types will probably want to take advantage of that - see #1630).
**Checklist**

Fix invalid specification of default_value without regard to default_value_type

---

CHANGES.rst
traits/tests/test_trait_dict_object.py
traits/tests/test_trait_list_object.py
traits/tests/test_trait_set_object.py
traits/trait_dict_object.py
traits/trait_list_object.py
traits/trait_set_object.py
traits/trait_types.py

This PR fixes `TraitListObject`, `TraitSetObject` and `TraitDictObject` to perform item / key / value validation using the `validate` method of the appropriate `CTrait` instance instead of the `validate` method of the handler. Using the handler's validation is not the right thing to do, because the CTrait validation may or may not delegate to the handler's validate method : in particular, in the case where there's a fast validator, CTrait validation uses that fast validator, and so should the list / set / dict validation.
This fixes one of the issues identified in #1619. (In particular, it fixes the particular example that @mdsmarte gives in that issue.)
**Checklist**

Make TraitListObject use the CTrait to validate items, not the handler

---

docs/source/traits_user_manual/defining.rst

fixes #1445
This PR documents the `Date`, `Datetime` and `Time` trait types in the "Predefined Trait Types" section of the user documentation.
**Checklist**

Document "Date", "Datetime" and "Time" trait types

---

traits/ctraits.c

As mentioned in an earlier comment https://github.com/enthought/traits/pull/1631#discussion_r853688685, this PR returns `PyErr_Format` instead of explicitly returning `NULL`.
**Checklist**

Return "PyErr_Format" calls in "traits/ctraits.c"

---

.github/workflows/test-from-pypi.yml

Results of our scheduled GitHub Action builds (and particularly failures) risk going unnoticed.
This PR changes the notifications for failure reports to a more visible Slack channel. Success reports are still sent to the noisy-bots channel.

Switch Slack channel used to report failures

---

docs/source/conf.py

This PR simply removes the `sphinx-copybutton` extension-specific configuration from the sphinx configuration file.
This is because the configuration was in some cases returning bad data. See for example the `all_wildcard.py` code block at https://traits.readthedocs.io/en/latest/traits_user_manual/advanced.html#trait-attribute-name-wildcard. Trying to copy that codeblock returns only the code within `"""` and not the actual class. The prompt text configuration seems complicated and difficult to get "right" to support the wide range of code samples we have in the documentation.
For now, having a copy button that copies the entire code sample is better than a smart copy button that only copies the "right" piece of code
**Checklist**

Don't configure the "sphinx-copybutton" extension

---

traits-stubs/setup.py
traits-stubs/traits-stubs/trait_types.pyi
traits-stubs/traits_stubs_tests/examples/Float.py
traits-stubs/traits_stubs_tests/examples/Int.py

This PR improves the type stubs for `Int` and `Float`, being more accurate about what's accepted for those trait types.
We need `SupportsIndex`, which is only available in `typing` from Python 3.8 onwards. So I've added `typing-extensions` as a dependency for `traits-stubs`. We can drop the dependency once we no longer support Python 3.6 and Python 3.7.

Improve Int and Float type stubs

---

traits-stubs/README.rst
traits-stubs/traits-stubs/api.pyi
traits-stubs/traits_stubs_tests/examples/completeness.py

Projects using `traits-stubs` reported that mypy was complaining about not having information about `TraitError`. This PR should fix that.
I've also added some instructions on local development to the README, since I have to figure this out every time.

Fix mypy complaints about TraitError

---

.github/workflows/test-from-pypi.yml

The run https://github.com/enthought/traits/actions/runs/2716205488 of the test-from-pypi workflow has started failing, as a result of #1660.
It doesn't make a lot of sense to test the 3.11 wheels when there aren't any 3.11 wheels ...
This PR removes 3.11-dev from the test matrix for the binary install. Separately, though, we should build 3.11 wheels at some point.

Remove 3.11-dev from test-pypi-wheel matrix

---

traits/etsconfig/tests/test_etsconfig.py

The test name started with an underscore which is why unittest wasnt discovering it.
Once the leading underscore is removed, we noticed that the test assertion fails - because the `app_name` that the code infers by default is different.
We update the assertion to pass - with the strong assumption that the tests are run using `unittest` - which traits uses for test discovery and to run the tests.
**Checklist**

Reveal and fix a masked test

---

.github/workflows/run-core-traits-tests.yml
.github/workflows/run-traits-tests.yml
pyproject.toml

Long overdue PR to add a `pyproject.toml`, containing build configuration and basic `black` and `isort` configurations, for those who want to use `black` and `isort` on new files in this repository. (Note that many existing files don't conform to those configurations. We have no immediate plans to rectify that, but the configurations may be useful for new code.)
With the build dependencies explicitly mentioned in `pyproject.toml`, there should be no need to pre-install `setuptools` and/or `wheel` in the test environments, so we've updated the workflows accordingly.

Add pyproject.toml

---

traits/observation/_observer_change_notifier.py
traits/observation/exception_handling.py

The most recent version of flake8 (v5.0.4) picks up some long line errors that weren't picked up by previous versions. This PR fixes those long lines.

Fix some long lines in docstrings

---

traits/util/tests/test_resource.py

Require the pkg_resources module to be present for find_resource and store_resource tests

---

traits/trait_base.py

This PR removes an `enumerate = enumerate` assignment that should no longer be necessary.
Technically, this is a backwards incompatible change: anyone who imports `enumerate` from `traits.trait_base` will no longer be able to do so. However, the workaround is immediate (just delete that import so that you pick up the built-in `enumerate`), and code that's doing this is already wrong on so many levels, so I don't feel bad about making this change without a deprecation period.
**Checklist**

Remove outdated alias

---

traits-stubs/pyproject.toml

This PR adds a minimal `pyproject.toml` for the traits-stubs package; without this, `pip` enters "legacy mode" when trying to build the stubs, and it's conceivable that at some point in the future that legacy mode will go away altogether.

Add minimal pyproject.toml for the traits-stubs package

---

.gitignore

This PR updates `.gitignore` to ignore the traits-stubs build directory in addition to the main Traits build directory.

Ignore the traits-stubs build directory in .gitignore

---

traits/etsconfig/etsconfig.py
traits/etsconfig/tests/test_etsconfig.py

Fix some nits noticed during reviewing #1670. (But sufficiently unrelated to #1670 that I couldn't justify squeezing them into that PR.)
- Fix weird docstring end-quote indentations
- Fix overriding of `TestCase.run`, which implicitly assumes that we'll be using `unittest` as our test runner.
- Fix another test that assumed that the test runner would be unittest.

Fix some ETSConfig and test nits

---

traits/testing/tests/test_unittest_tools.py
traits/tests/test_automatic_adaptation.py
traits/tests/test_property_notifications.py
traits/util/tests/test_record_events.py

This PR renames a mixin class to avoid Pytest trying to run it as a test class in its own right.
EDIT: Updated to rename a few more classes that Pytest otherwise tries to interpret as test classes.

Rename various test-related classes to avoid pytest treating them as tests

---

etstool.py

This makes Python 3.8 the default runtime to use, and updates the dependencies appropriately.  I think I don't need to make any changes to the github workflows for this - this change is mainly a developer convenience.

Update etstool.py for Python 3.8

---

pyproject.toml

This PR adds a pytest configuration to ignore traits-stubs when running the Traits tests. (It's fine to run the traits-stubs tests under pytest, but it needs to be done from the traits-stubs directory as a separate test run.)
Together with #1684 and #1683, this closes #1288.

Don't collect traits-stubs tests under pytest

---

docs/source/traits_api_reference/traits.etsconfig.rst
traits/etsconfig/etsconfig.py

This PR provides an alternative to #1669. The goal is to make the `ETSConfig` docstrings available in the API docs, so that a search for `ETSConfig` in the online documentation gives useful results.
To that end, this PR:
- Renames the `ETSConfig` _class_ to `ETSConfigFactory`
- Keeps the `ETSConfig` instance the same as before (previously, the created instance shadowed the class)
- Updates the main docstrings of `ETSConfigFactory` and `ETSConfig`.
There shouldn't be backwards-compatibility concerns with the rename: the `ETSConfig` class wasn't available before (since it was shadowed by the instance), and the trick of using `type(ETSConfig)` to get the class will still work.
I'm deliberately not exposing `ETSConfigFactory` in `traits.api`, since in most circumstances it shouldn't be used …

Make ETSConfig class documentation visible in the API docs

---

docs/source/traits_api_reference/trait_types.rst
docs/source/traits_user_manual/defining.rst
traits/trait_numeric.py
traits/trait_types.py

This PR adds notes to the user manual and API documentation to discourage users from using `Either` in new code. (`Union` should be preferred.)
Closes #1610

Document that Either should not be used in new code

---

traits-stubs/traits_stubs_tests/test_all.py
traits/testing/optional_dependencies.py

PR #1682 introduced what should have been a check for `numpy.typing`, that ended up as a check for `numpy.testing` instead. This PR fixes that.
Also, PR #1682 _should_ have failed on Python 3.6 because of the above, since on Python 3.6 the latest version of NumPy available doesn't have type hints. It didn't fail because we weren't populating the package data with the new `numpy_examples` directory, so the numpy-based tests weren't run. That's fixed in #1709.

Fix and rename requires_numpy_typing decorator

---

CHANGES.rst
traits-stubs/setup.py

This PR updates the traits stubs `setup.py` file in preparation for releasing stubs to go alongside the Traits 6.4.0 release.
We also remove the redundant `__init__.py` file from the `examples` directory - the Python files in this directory aren't intended to be used via import.

Update traits-stubs setup.py file for release

---

.github/workflows/release-to-pypi.yml

This PR updates `cibuildwheel` to the latest version, so that we can build Python 3.11 wheels when the time comes.

Update cibuildwheel to the latest version

---

.github/workflows/release-to-pypi.yml

This PR brings the wheel-build-and-PyPI-upload workflow in line with modern standards.
* Future proofing: use latest versions of Python and the various actions, so that with luck we don't need to update this workflow again for a while.
* Use `python -m build --sdist` instead of `python setup.py sdist` to build packages
* Remove unnecessary package installs.

Modernize the PyPI release workflow

---

traits/has_traits.py
traits/tests/test_interface_checker.py

This PR removes the long-deprecated ability to do adaptation by calling an interface class (i.e., doing `adapted = IFoo(myobject)` instead of `adapted = adapt(myobject, IFoo)`).

Remove the deprecated adapt-by-calling ability of Interfaces

---

pyproject.toml

There's an incompatibility between setuptools version 65.2 and later and current EDM runtimes. Until that incompatibility is resolved, building Traits (with `pip install .`) in an EDM environment fails.
As a temporary workaround, we constrain the setuptools version in `pyproject.toml`.
Should fix #1721.

Avoid incompatibility between setuptools >= 65.2 and EDM runtimes

---

.github/workflows/run-core-traits-tests.yml
.github/workflows/run-traits-tests.yml
.github/workflows/test-from-pypi.yml

Python 3.11 is now supported by the setup-python action (see https://github.com/actions/python-versions/pull/193). This PR replaces uses of 3.11-dev with 3.11 final.

Upgrade workflows to use Python 3.11 final

---

traits/util/event_tracer.py

This PR replaces uses of the deprecated (as of Python 3.12) `datetime.utcnow` method. Note that this isn't quite a like-for-like change: there's a slight difference in the output format. Given that the event tracer is barely used in practice, I doubt this change matters much.
```
>>> from datetime import datetime, timezone
>>> datetime.now(timezone.utc).isoformat(" ")
'2023-09-11 16:31:35.534330+00:00'
>>> datetime.utcnow().isoformat(" ")
'2023-09-11 16:31:56.798474'
```

Fix use of the deprecated datetime.utcnow method

---

.github/workflows/release-to-pypi.yml
.github/workflows/run-core-traits-tests.yml
.github/workflows/run-traits-tests.yml
.github/workflows/test-from-pypi.yml
pyproject.toml
setup.py

Python 3.12 is imminent. This is an experimental PR to add Python 3.12 support:
- Add 3.12 to the trove classifiers
- Add 3.12 to CI test matrices
- Allow running tests with PySide6 on Python 3.11, but not on Python 3.12
- Update cibuildwheel to latest version so that Python 3.12 eggs are built when making a release
Making this as a draft PR for now, since the possible failure modes are many and varied.

Update CI and workflows for Python 3.12 support

---

.github/workflows/release-to-pypi.yml
.github/workflows/run-core-traits-tests.yml
.github/workflows/run-style-checks.yml
.github/workflows/run-traits-tests.yml
.github/workflows/test-documentation-build.yml
.github/workflows/test-from-pypi.yml
CHANGES.rst
pyproject.toml
setup.py
traits/util/event_tracer.py
traits/util/tests/test_trait_documenter.py

This PR:
- backports PR #1755 to the release branch
- updates the version and changelog in preparation for a Traits 6.4.3 release
EDIT: Updated 2023-09-11 to backport PRs #1757  and #1758.

Release Traits 6.4.3

---

.github/workflows/test-from-pypi.yml

Our "test from PyPI" workflow was failing with Python 3.12 because it exercised the Cython tests, which use `cython.inline`, and `cython.inline` in turn uses `distutils`, which no longer exists in the Python 3.12 standard library.
As a temporary workaround, this PR adds `setuptools` to the list of packages installed into the test environment; `setuptools` provides a shim for `distutils`.
I'd guess that at some point in the reasonably near future the dependence of Cython on `distutils` will be fixed.
Closely related upstream issue: https://github.com/cython/cython/issues/5751

Fix Cython tests on Python 3.12

---

traits/tests/test_observe.py
traits/trait_list_object.py

When using nested list: `ta.List(trait=ta.List(trait=ta.Int, items=False), items=False)`, _inserting_ an inner list failed to register observers on that list. _Appending_ and _extending_ works as expected. The culprit was that the item validation was performed twice, thus probably registering the observers on the wrong object.
Sample code illustrating the behavior:
```python
import traits.api as ta
class Provider(ta.HasTraits):
l = ta.List(trait=ta.List(trait=ta.Int, items=False), items=False)
def __init__(self, **kwargs) -> None:
super().__init__(**kwargs)
self.observe(self.assigned, "l")
self.observe(self.outer_changed, "l:items")
self.observe(self.inner_changed, "l:items:items")
def assigned(self, event):
print("assigned", event)
def outer_changed(self, event):
print("outer changed", …
```

Fix missing observer registration when inserting into nested list

---

traits/ctraits.c
traits/tests/test_property_notifications.py
traits/tests/test_regression.py

Closes #1747 
This PR issues a `UserWarning` when a `*_default` trait default method raises an `AttributeError`, to help detect an otherwise easy-to-miss failure mode.
**Checklist**

Warn if a Trait default method raises AttributeError

---

.github/workflows/run-core-traits-tests.yml
.github/workflows/run-traits-tests.yml
.github/workflows/test-from-pypi.yml
README.rst
docs/source/traits_user_manual/intro.rst
etstool.py
setup.py
traits/ctraits.c
traits/tests/test_complex.py
traits/tests/test_extended_trait_change.py
traits/tests/test_float.py
traits/tests/test_map.py
traits/tests/test_prefix_map.py
traits/tests/test_regression.py
traits/trait_base.py
traits/trait_types.pyi

This PR drops support for Python versions older than 3.8.

Drop support for Python versions earlier than 3.8

---

docs/source/traits_user_manual/notification.rst
traits/observation/observe.py
traits/observation/tests/test_observe.py
traits/tests/test_observe.py

This adds basic support for async coroutines as trait observe handlers, as discussed in #1770 
This is designed to be the smallest thing that will work.
**Checklist**

Add basic support for async dispatch

---

.github/workflows/run-core-traits-tests.yml

We'd pinned Python 3.13 to avoid an issue on Windows with the 3.13.0a4 build.
Now that 3.13.0a5 is available, that issue should be resolved, so that we can remove the pin.

Remove pin on Python 3.13 version

---

.github/dependabot.yml

This PR adds a minimal dependabot configuration for keeping workflow actions up to date.

Add dependabot config for automatically updating GitHub Actions versions

---

.github/workflows/run-core-traits-tests.yml
.github/workflows/run-traits-tests.yml
traits/ctraits.c

This PR fixes some compiler warnings that I noticed in the failed Windows build in PR #1773. There are two classes of fixes:
- Fix occurrences of `int` used to represent the size of a tuple / list / dict. Those should be `Py_ssize_t`
- Fix two functions that treat a mask as having type `int`, when it should be `unsigned int`. All the actual masks used have type `unsigned int`.
The warnings themselves are relatively harmless, but silencing them gives us a better chance of noticing warnings that we _should_ be taking notice of.
The PR also adds a `-v` flag to the `pip install` commands that install Traits, so that compiler warnings will always be visible in the build log. Without the `-v`, we only get to see the warnings for failed builds.

Fix some compiler warnings

---

setup.py
traits/tests/test_enum.py

This PR removes a test that's using `UITester` from TraitsUI. This test exposed the Traits test suite to a class of possible issues with 3rd party GUI frameworks (in this case PySide6); historically, `UITester` has also been a particularly fragile part of TraitsUI.
In its place is a test that at least executes the `Enum.create_editor` method, but doesn't attempt to create an instance of the editor.
We also fix an issue with test dependencies and the latest release of Sphinx: `defusedxml` is now required to run the tests for the Traits documenter.
Closes #1787

Remove a test that uses UITester

---

traits/api.py
traits/api.pyi
traits/tests/test_new_notifiers.py
traits/tests/test_ui_notifiers.py
traits/trait_notifiers.py
traits/traits_notifiers.pyi

Since #1788, we have only one test module that makes use of the Qt event loop. That test module contains tests for the behaviour of handlers that use `dispatch='ui'` mechanism to redispatch off-thread notifications to the ui thread.
This PR reworks that test module, with some significant collateral damage along the way.
In detail:
- reworks that test module (`test_ui_notifiers`) to avoid the need for the Qt event loop; instead, it tests against a `ui_handler` based on asyncio, which redispatches to the running asyncio event loop
- adds a `get_ui_handler` counterpart to `set_ui_handler`, and exposes both functions in `traits.api`
- adds type hints for `get_ui_handler` and `set_ui_handler`
- removes two public module globals from `trait_notifiers`: `ui_handler` has been made private, while …

Rework ui_dispatch tests to avoid need for Qt

---

.github/workflows/test-from-pypi.yml

This PR attempts to fix the architectures in the test-from-pypi.yml workflow. The intent is to run tests on the following combinations:
- windows-latest: x86 and x64
- ubuntu-latest: x64
- macos-latest: arm64
- macos-13: x64
We also:
- clean up the workflow to remove PySide6-related pieces that are no longer necessary
- add defusedxml as a test dependency
Test run: https://github.com/enthought/traits/actions/runs/8998474167

Fix architectures in PyPI workflow

---

docs/source/traits_user_manual/notification.rst

Adds a small clarification to when `attr1:attr2` syntax triggers a notification.

DOC: Clarify `attr1:attr2` notification trigger behavior

---

changelog.d/20240621_105210_mdickinson_add_event_types_to_api.rst
traits/observation/api.py
traits/observation/tests/test_dict_change_event.py
traits/observation/tests/test_list_change_event.py
traits/observation/tests/test_set_change_event.py
traits/observation/tests/test_trait_change_event.py

This PR exports observer event types (`TraitChangeEvent`, `ListChangeEvent`, `DictChangeEvent`, `SetChangeEvent`) in `traits.observation.api`, so that they can be easily used in type hints in client code.
The event types are already documented. I've updated some tests to ensure that the test suite exercises the import from `test.observation.api`.
Closes #1802

Export event types in traits.observation.api.

---

traits/ctraits.c

This PR silences warning messages from `PyDict_GetItem` in cases where we're trying to look up something that's not hashable.
Note that replacing `PyDict_GetItem` with `PyDict_GetItemWithError` means replacing something that can't raise an exception with something that can, but in both cases we already have error paths present that handle the case where an exception is set. (In the `validate_trait_map` case, `raise_traits_error` takes care of clearing any existing error. Arguably it should chain the errors instead, but that's a separate discussion.)
Closes #1817

Fix warning messages from PyDict_GetItem

---

.github/workflows/release-to-pypi.yml
CHANGES.rst
pyproject.toml
setup.py

This PR attempts to fix the current wheel-building workflow. That workflow is failing on manylinux-aarch64 builds with a gcc internal compiler error, so until we can understand the problem better we'll drop those builds and the QEMU emulation.
While we're here, we also perform separate macOS Intel and ARM builds.

Fix the wheel-building workflow

---

CHANGES.rst
traits/trait_notifiers.py

In #1792 we made `traits.trait_notifiers.ui_handler` private, renaming it to `_ui_handler`. However, it turns out that Pyface wants to access the value of `ui_handler` directly, so this change breaks current Pyface.
This PR reverts that change.
Pyface code links:
- https://github.com/enthought/pyface/blob/46f700999284c8104fb2a5468f549677dfadf063/pyface/ui/qt/init.py#L15
- https://github.com/enthought/pyface/blob/46f700999284c8104fb2a5468f549677dfadf063/pyface/ui/wx/init.py#L14

Make ui_handler publicly available again

---

.github/workflows/run-traits-tests.yml
.github/workflows/test-from-pypi.yml

This PR updates all workflows to support 3.13.
We may run into issues with the full test workflow on Python 3.13.

Include Python 3.13 in all workflows

---

.github/workflows/run-traits-tests.yml
.github/workflows/test-from-pypi.yml
CHANGES.rst
setup.py
traits/trait_notifiers.py

This PR prepares for a Traits 7.0.2 release:
* Backport PR #1827 and PR #1826
* Bump the version number

Prepare for Traits 7.0.2 release

---

CHANGES.rst

This changelog entry should have gone in before #1826 was backported.

Fix missing changelog entry for #1826

---

etstool.py

`lark-parser` is an invalid EDS dependency; it should be `lark_parser`. This PR fixes that.
Prior to this fix, `python etstool.py install` failed; I've verified that it works after the fix.

Fix spelling of lark_parser dependency in etstool.py

---

traits/stubs_tests/util.py

The traits stubs tests have been passing without actually running mypy on the target example files, since:
- we're passing `--show-error-code` to `mypy`,
- that generates a usage error about an ambiguous option (on stderr) with no output on stdout,
- so our code deduces that there were no mypy errors reported
Aside from the `--show-error-code` mistake (it should be `--show-error-codes`), there are two other problems that allowed this to go undetected:
- we don't check the stderr output in `assertRaisesMypyError`
- we don't check that we got all of the _expected_ failures in `assertRaisesMypyError`
This PR:
- adds an extra check in `assertMypyError` to make sure that we catch this and future similar usage errors as report them as test failures
- adds another extra check in …

Fix silent mypy failures

---

traits/adaptation/adaptation_manager.py
traits/tests/check_timing.py
traits/trait_factory.py

A recent release of `flake8` started complaining about redundant uses of `global` inside functions/methods, causing `flake8` errors in the Traits style checks. (The relevant change is in pyflakes 3.3.0: see https://github.com/PyCQA/pyflakes/pull/825.)
This PR removes those `global` declarations.

Remove unnecessary uses of 'global'

---

traits/trait_notifiers.py

Follow-up PR to #1850: that PR removed one redundant check for `__self__` not being `None` on a bound method. This PR removes the other such check in the same module.

Remove an 'if' where the condition is always true

---

traits/stubs_tests/examples/Instance.py
traits/trait_types.pyi

~Note: #1838 should be merged first - we can't trust the type hint tests until it is.~ Done.
Closes #1839 
Closes #1764 
Closes #1673 
This PR provides a better type-hinting experience for `Instance` (and `BaseInstance`) traits:
- fixes inclusion of `str` in the inferred type for the value of an `Instance` trait
- adds an overload for the case `allow_none=False`, so that type checkers can infer that the value of the trait is not `None` (and `None` may not be assigned) in this case. Note: this technically isn't true (since a default of `None` can still be provided even when `allow_none=False`), but it's a safe bet that if the user is explicitly stating `allow_none=False` then the intent is that the trait value is never `False`
- adds an overload for the forward reference case where the …

Make Instance type hints more useful
